### ISSUE TITLE
Human readable error message for absent original read information

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#100]
Exception in thread "main" java.lang.NullPointerException
  at com.milaboratory.mixcr.cli.ActionExportCloneReads.writeSingle(ActionExportCloneReads.java:133)
  at com.milaboratory.mixcr.cli.ActionExportCloneReads.go(ActionExportCloneReads.java:57)
  at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:145)
  at com.milaboratory.mixcr.cli.Main.main(Main.java:66)

**Comment by dbolotin** [comment]
In hotfix/1.7.4 branch
