### ISSUE TITLE
Input file has no tags

### ISSUE THREAD

**Issue by malonzm1** [milaboratory/mixcr#1073]
Hi,

When I run mixcr, `mixcr analyze smartseq2-vdj-full-length -s hsa --rna --threads 4 fastq_1.fastq.gz fastq_2.fastq.gz outdir` it throws the error Error while running command refineTagsAndSort java.lang.IllegalArgumentException: input file has no tags. The full log report is:

LINFO: Stat2 sent in 121ms
Running:
mixcr align --report /scratch/cs/pan-autoimmune/data/mixcr/scRNAseq/GSE104782/SRR6155080.align.report.txt --json-report /scratch/cs/pan-autoimmune/data/mixcr/scRNAseq/GSE104782/SRR6155080.align.report.json --threads 4 --preset smartseq2-vdj-full-length --rna --species hsa /scratch/cs/pan-autoimmune/data/raw_data/scRNAseq/GSE104782/SRR6155080/SRR6155080_pass_1.fastq.gz /scratch/cs/pan-autoimmune/data/raw_data/scRNAseq/GSE104782/SRR6155080/SRR6155080_pass_2.fastq.gz /scratch/cs/pan-autoimmune/data/mixcr/scRNAseq/GSE104782/SRR6155080.vdjca
LINFO: Stat2 sent in 28ms
Alignment: 0%
LINFO: Stat2 sent in 106ms
LINFO: Stat2 sent in 136ms
Alignment: 2.1%  ETA: 01:31:05
LINFO: Stat2 sent in 130ms
Alignment: 4.4%  ETA: 01:23:33
Alignment: 6.7%  ETA: 01:22:09
LINFO: Stat2 sent in 124ms
Alignment: 9%  ETA: 01:18:57
Alignment: 11.3%  ETA: 01:16:57
Alignment: 13.6%  ETA: 01:14:42
Alignment: 15.9%  ETA: 01:14:02
LINFO: Stat2 sent in 139ms
Alignment: 18.2%  ETA: 01:11:15
Alignment: 20.5%  ETA: 01:09:00
Alignment: 22.8%  ETA: 01:06:59
Alignment: 25.1%  ETA: 01:05:29
Alignment: 27.4%  ETA: 01:02:47
Alignment: 29.7%  ETA: 01:01:27
Alignment: 32%  ETA: 00:59:15
Alignment: 34.3%  ETA: 00:56:23
LINFO: Stat2 sent in 133ms
Alignment: 36.7%  ETA: 00:54:00
Alignment: 39%  ETA: 00:52:00
Alignment: 41.3%  ETA: 00:50:33
Alignment: 43.6%  ETA: 00:49:06
Alignment: 46%  ETA: 00:46:04
Alignment: 48.3%  ETA: 00:44:13
Alignment: 50.6%  ETA: 00:42:23
Alignment: 53%  ETA: 00:40:41
Alignment: 55.3%  ETA: 00:38:15
Alignment: 57.6%  ETA: 00:36:32
Alignment: 59.9%  ETA: 00:34:16
Alignment: 62.3%  ETA: 00:32:30
Alignment: 64.6%  ETA: 00:30:10
Alignment: 66.9%  ETA: 00:28:23
Alignment: 69.2%  ETA: 00:26:41
Alignment: 71.6%  ETA: 00:24:18
LINFO: Stat2 sent in 105ms
Alignment: 73.9%  ETA: 00:22:18
Alignment: 76.3%  ETA: 00:20:18
Alignment: 78.6%  ETA: 00:18:27
Alignment: 80.9%  ETA: 00:16:31
Alignment: 83.2%  ETA: 00:14:17
Alignment: 85.6%  ETA: 00:12:14
Alignment: 87.9%  ETA: 00:10:22
Alignment: 90.2%  ETA: 00:08:24
Alignment: 92.6%  ETA: 00:06:20
Alignment: 94.9%  ETA: 00:04:20
Alignment: 97.3%  ETA: 00:02:20
Alignment: 99.6%  ETA: 00:00:20
 Align Report 
Analysis time: 86.38m
Total sequencing reads: 133030951
Successfully aligned reads: 439054 (0.33%)
Alignment failed: no hits (not TCR/IG?): 132591897 (99.67%)
Overlapped: 48282703 (36.29%)
Overlapped and aligned: 55473 (0.04%)
Overlapped and not aligned: 48227230 (36.25%)
Alignment-aided overlaps, percent of overlapped and aligned: 2 (0%)
No CDR3 parts alignments, percent of successfully aligned: 437875 (99.73%)
Partial aligned reads, percent of successfully aligned: 1179 (0.27%)
V gene chimeras: 10 (0%)
Paired-end alignment conflicts eliminated: 48 (0%)
Realigned with forced non-floating bound: 169496500 (127.41%)
Realigned with forced non-floating right bound in left read: 34 (0%)
Realigned with forced non-floating left bound in right read: 34 (0%)
TRA chains: 2269 (0.52%)
TRA non-functional: 0 (0%)
TRB chains: 4651 (1.06%)
TRB non-functional: 0 (0%)
TRD chains: 100 (0.02%)
TRD non-functional: 0 (0%)
TRG chains: 386587 (88.05%)
TRG non-functional: 0 (0%)
TRAD chains: 41787 (9.52%)
TRAD non-functional: 0 (0%)
IGH chains: 1407 (0.32%)
IGH non-functional: 0 (0%)
IGK chains: 1104 (0.25%)
IGK non-functional: 0 (0%)
IGL chains: 1149 (0.26%)
IGL non-functional: 0 (0%)
Running:
mixcr refineTagsAndSort --report /scratch/cs/pan-autoimmune/data/mixcr/scRNAseq/GSE104782/SRR6155080.refine.report.txt --json-report /scratch/cs/pan-autoimmune/data/mixcr/scRNAseq/GSE104782/SRR6155080.refine.report.json /scratch/cs/pan-autoimmune/data/mixcr/scRNAseq/GSE104782/SRR6155080.vdjca /scratch/cs/pan-autoimmune/data/mixcr/scRNAseq/GSE104782/SRR6155080.refined.vdjca
4.3.1; built=Mon Mar 27 16:30:00 EEST 2023; rev=601813069a; lib=repseqio.v2.2
picocli.CommandLine$ExecutionException: Error while running command refineTagsAndSort java.lang.IllegalArgumentException: input file has no tags
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-13(SourceFile:320)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:365)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-27(SourceFile:409)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:100)
Caused by: java.lang.IllegalArgumentException: input file has no tags
        at com.milaboratory.mixcr.cli.CommandRefineTagsAndSort$Cmd.run1(SourceFile:255)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-27(SourceFile:409)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 12 more

Please advise.

Thanks and good day.

**Comment by PoslavskySV** [comment]
Hi,

for SmartSeq2 protocol you should have multiple files: different files corresponding to different cells with row and column cell barcodes. Please see here how to run SmartSeq2 data:

https://mixcr.com/mixcr/reference/overview-built-in-presets/#smart-seq2

**Comment by malonzm1** [comment]
Hi,

I downloaded these fastq files from NCBI GEO. I took a look at the original submission (Data access) and there are only 2 fastq files originally submitted for this SRA ID https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=SRR6155080&display=data-access. Can you please advise how to find multiple files from SmartSeq2 in NCBI GEO?

Thanks and good day.
