### ISSUE TITLE
Read-only file system at com.milaboratory.o.df.a(SourceFile:146)

### ISSUE THREAD

**Issue by UMR1098** [milaboratory/mixcr#1090]
## Checklist before submitting the issue:

 - [ ] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [ ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*Does any one can help me ?*

## Actual Result

*When i used the following command of mixcr i have this error*

## Exact MiXCR commands 

"mixcr analyze rnaseq-cdr3 -Xmx30g"

## MiXCR report files 

"""
Exception in thread "main" java.lang.RuntimeException: java.nio.file.FileSystemException: /Home/Users/bndao/.mi/com.milaboratory.mixcr.cli.Main: Read-only file system
        at com.milaboratory.o.df.a(SourceFile:146)
        at com.milaboratory.o.di.<init>(SourceFile:90)
        at com.milaboratory.o.di.<init>(SourceFile:75)
        at com.milaboratory.milm.MiXCRMain.a(SourceFile:26)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:91)
Caused by: java.nio.file.FileSystemException: /Home/Users/bndao/.mi/com.milaboratory.mixcr.cli.Main: Read-only file system
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:690)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
        at java.base/java.nio.file.Files.createDirectories(Files.java:783)
        at com.milaboratory.o.df.a(SourceFile:144)
"""

**Comment by UMR1098** [comment]
even if I execute the command chmod  -R +x /Home/Users/bndao/.mi/com.milaboratory.mixcr.cli.Main,  the error persists

**Comment by PoslavskySV** [comment]
Hi,

It looks like the issue is related to your computing environment but not to MiXCR itself. Can you check with your sysadmin or try on another machine?
