### ISSUE TITLE
Error when using preset 10x-5gex-full-length

### ISSUE THREAD

**Issue by malonzm1** [milaboratory/mixcr#1120]
Hi,

When I run mixcr, mixcr analyze 10x-5gex-full-length -s hsa --rna --threads 4 fastq_3.fastq.gz outdir it throws the error Error while running command align java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1. The full log report is:

LINFO: Stat2 sent in 542ms
====================
Running:
mixcr align --report GSE159117/SRR12781504/SRR12781504.align.report.txt --json-report GSE159117/SRR12781504/SRR12781504.align.report.json --threads 4 --preset 10x-5gex-full-length --rna --species hsa GSE159117/SRR12781504/SRR12781504_2.fastq.gz GSE159117/SRR12781504/SRR12781504.vdjca
The following tags and their roles were recognised:
  Payload tags: R2
  Cell tags: CELL
  Molecule tags: UMI
LINFO: Stat2 sent in 28ms
Alignment: 0%
4.3.1; built=Mon Mar 27 16:30:00 EEST 2023; rev=601813069a; lib=repseqio.v2.2
picocli.CommandLine$ExecutionException: Error while running command align java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-13(SourceFile:320)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:365)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-27(SourceFile:409)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:100)
Caused by: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at cc.redberry.pipe.blocks.ParallelProcessor.take(ParallelProcessor.java:246)
        at cc.redberry.pipe.CUtils$UnChunkingPort.take(CUtils.java:304)
        at cc.redberry.pipe.util.OrderedOutputPort.take(OrderedOutputPort.java:95)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd.run1(SourceFile:1248)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-27(SourceFile:409)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 12 more
        Suppressed: java.lang.RuntimeException: java.lang.IllegalStateException: Footer not set
                at com.milaboratory.mixcr.cli.CommandAlign$Cmd$Writers.close(SourceFile:1199)
                at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:64)
                at com.milaboratory.mixcr.cli.CommandAlign$Cmd.run1(SourceFile:1230)
                ... 23 more
        Caused by: java.lang.IllegalStateException: Footer not set
                at com.milaboratory.o.kd.close(SourceFile:202)
                at com.milaboratory.mixcr.cli.CommandAlign$Cmd$Writers.close(SourceFile:1191)
                ... 25 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.base/java.util.Collections$SingletonList.get(Collections.java:4849)
        at com.milaboratory.o.dP.a(SourceFile:3073)
        at com.milaboratory.mixcr.cli.CommandAlignPipeline$TagsExtractor.parse(SourceFile:429)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd$run1$lambda-8$$inlined$mapUnchunked$1.process(SourceFile:36)
        at cc.redberry.pipe.CUtils.lambda$chunked$2(CUtils.java:177)
        at cc.redberry.pipe.util.SimpleProcessorWrapper.take(SimpleProcessorWrapper.java:43)
        at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:302)
        at java.base/java.lang.Thread.run(Thread.java:829)

Please advise. Thanks.

**Comment by PoslavskySV** [comment]
Hi,

Did you use the most recent version of MiXCR?

**Comment by malonzm1** [comment]
Hi,

I used MiXCR v4.3.1.

**Comment by PoslavskySV** [comment]
Hi, 

please try to reproduce with MiXCR v4.4.1 - it should be fixed now.
