### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by weshorton** [milaboratory/mixcr#117]
#### System
java version 1.7.0_101
mixcr version 1.8.1

#### Commands
`usr/bin/java -Xmx15g -jar /path/to/mixcr-1.8.1/mixcr.jar align -f --loci TRB --species mmu --save-description --save-reads --report /path/to/report.txt /path/to/fastq /path/to/align.vdjca`

`usr/bin/java -Xmx15g -jar /path/to/mixcr-1.8.1/mixcr.jar assemble -f --index /path/to/index.txt --report /path/to/report.txt --threads 4 /path/to/align.vdjca /path/to/assemble.clns`

#### Description
I'm running the mixcr align-assemble-export pipeline on 155 samples of mouse T-Cell Receptor beta data. Samples were created using a multiplex PCR reaction to amplify all 20 V and 13 J genes within this locus. Using the pipeline without the index step works just fine for all samples, it's when we attempt to add the `-index [index file]` option that we get the issue.

The error originally occurred for 3 samples out of 155. After re-running with just those 3 samples, one of them was recovered, but the other two still throw errors

##### Trial 1
1. Run **mixcr align** 
     A) "Problem samples" (S33, S74, S93) have no error in stderr and stdout is identical to other samples

2. Run **mixcr assemble**
     A) "Problem samples" have identical stdout to other samples
     B) "Problem samples" have errors in stderr:

`Exception in thread "main" java.lang.NullPointerException
	at com.milaboratory.mixcr.assembler.IO.write0(IO.java:122)
	at com.milaboratory.mixcr.assembler.IO.access$000(IO.java:45)
	at com.milaboratory.mixcr.assembler.IO$ReadToCloneMappingBtreeSerializer.serialize(IO.java:81)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:385)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:288)
	at org.mapdb.Store.serialize(Store.java:154)
	at org.mapdb.StoreDirect.put(StoreDirect.java:365)
	at org.mapdb.Caches$HashTable.put(Caches.java:216)
	at org.mapdb.Pump.buildTreeMap(Pump.java:470)
	at org.mapdb.DB.createTreeSet(DB.java:1072)
	at org.mapdb.DB$BTreeSetMaker.make(DB.java:749)
	at com.milaboratory.mixcr.cli.ActionAssemble.go(ActionAssemble.java:141)
	at com.milaboratory.mitools.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:145)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:69)`

##### Trial 2
1. Run **mixcr align**  with just problem samples (S33, S74, S93)
     A) Same as above, no stderr and stdout is the same

2. Run **mixcr assemble** with just problem samples
     A) Same as above, but one sample (S33) does not produce error

##### Trial 3
1. Run **mixcr align**  with just problem samples (S74, S93)
     A) Same as above, no stderr and stdout is the same

2. Run **mixcr assemble** with just problem samples
     A) Same error message as above.

**Comment by PoslavskySV** [comment]
Could you please paste your `mixcr -v` output? From the text of error I see that your mixcr version is below 1.8 (dependency on `com.milaboratory.mitools` is excluded since version 1.8), and I hope that in mixcr 1.8+ this issue is resolved.

**Comment by weshorton** [comment]
I'm running on a cluster so I don't have it installed per se, I just have the unzipped mixcr.1.8.1.zip which contains the jar file. There are no other mixcr files in that directory. Also the assemble report file seems to be from a new version, as there are more lines in it than before:

#### Assemble Report
`Analysis Date: Mon Jul 18 08:18:37 PDT 2016
Input file(s): /home/exacloud/lustre1/CompBio/data/tcrseq/dhaarini/DNA160708LC/mixcr//alignments/DNA160708LC_S74_alignment.vdjca
Output file: /home/exacloud/lustre1/CompBio/data/tcrseq/dhaarini/DNA160708LC/mixcr//assemblies/DNA160708LC_S74_alignment_clones.clns
Command line arguments: assemble -f --index /home/exacloud/lustre1/CompBio/data/tcrseq/dhaarini/DNA160708LC/mixcr/indexes/S74_index.txt --report /home/exacloud/lustre1/CompBio/data/tcrseq/dhaarini/DNA160708LC/mixcr/reports/assemble/S74_assemble_report.txt --threads 4 /home/exacloud/lustre1/CompBio/data/tcrseq/dhaarini/DNA160708LC/mixcr//alignments/DNA160708LC_S74_alignment.vdjca /home/exacloud/lustre1/CompBio/data/tcrseq/dhaarini/DNA160708LC/mixcr//assemblies/DNA160708LC_S74_alignment_clones.clns
Final clonotype count: 853
Average reads per clonotype: 1.91
Total reads used in clonotypes: 1625
Reads used in clonotypes, percent of total: 3.89%
Clonal sequences analysed, percent of total: 3.95%
Reads used as core, percent of used: 77.01%
Mapped low quality reads, percent of used: 22.99%
Reads clustered in PCR error correction, percent of used: 1.69%
Reads pre-clustered due to the similar VJC-lists, percent of used: 0%
Percent of reads dropped due to the lack of clonal sequence: 11.63%
Percent of reads dropped due to low quality: 0%
Percent of reads dropped due to failed mapping: 83.14%
Reads dropped with low quality clones: 0%
Clonotypes eliminated by PCR error correction: 14
Clonotypes dropped as low quality: 0
Clonotypes pre-clustered due to the similar VJC-lists: 0
======================================`

So although it gives me the error after the assemble step, it still produces an output. When I try to use that output for export_alignments, however, it does not work.

### Export Alignments Error
`Exception in thread "main" java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:269)
	at org.mapdb.StoreDirect.<init>(StoreDirect.java:207)
	at org.mapdb.DBMaker.extendStoreDirect(DBMaker.java:971)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:758)
	at org.mapdb.DBMaker.make(DBMaker.java:701)
	at com.milaboratory.mixcr.export.FieldExtractors$AlignmentToCloneExtractor.<init>(FieldExtractors.java:642)
	at com.milaboratory.mixcr.export.FieldExtractors$27.create(FieldExtractors.java:625)
	at com.milaboratory.mixcr.export.FieldExtractors.parse(FieldExtractors.java:450)
	at com.milaboratory.mixcr.cli.ActionExportParameters.parseFields(ActionExportParameters.java:132)
	at com.milaboratory.mixcr.cli.ActionExportParameters.parse(ActionExportParameters.java:101)
	at com.milaboratory.mixcr.cli.ActionExport.parseParameters(ActionExport.java:55)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:99)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:73)
Caused by: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	... 13 more`

#### Export Clones Error
`Exception in thread "main" java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:269)
	at org.mapdb.StoreDirect.<init>(StoreDirect.java:207)
	at org.mapdb.DBMaker.extendStoreDirect(DBMaker.java:971)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:758)
	at org.mapdb.DBMaker.make(DBMaker.java:701)
	at com.milaboratory.mixcr.export.FieldExtractors$CloneToReadsExtractor.<init>(FieldExtractors.java:692)
	at com.milaboratory.mixcr.export.FieldExtractors$24.create(FieldExtractors.java:404)
	at com.milaboratory.mixcr.export.FieldExtractors.parse(FieldExtractors.java:450)
	at com.milaboratory.mixcr.cli.ActionExportParameters.parseFields(ActionExportParameters.java:125)
	at com.milaboratory.mixcr.cli.ActionExportParameters.parse(ActionExportParameters.java:101)
	at com.milaboratory.mixcr.cli.ActionExport.parseParameters(ActionExport.java:55)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:99)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:73)
Caused by: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	... 13 more`

**Comment by PoslavskySV** [comment]
Could you please also paste an output to stderr which mixcr 1.8 produces for the problem samples at `assemble` step?

**Comment by weshorton** [comment]
I copied the files to my local machine to try. 

### Mixcr Location
`/usr/local/bin/mixcr/mixcr.jar`

in .bash_profile:
`export PATH="$PATH:/usr/local/bin/mixcr"`

java -version:
`java version "1.8.0_66"  
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)  
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)`

mixcr -v:
`MiXCR v1.8.1 (built Wed Jun 29 01:35:12 PDT 2016; rev=d7c1254; branch=hotfix/v1.8.1)  
Components:   
MiLib v1.5-SNAPSHOT (rev=27a3ea6; branch=develop)`


### Align command and output

mixcr align -f --loci TRB --species mmu --save-description --save-reads --report reports/align/S93_align_report.txt ./despiked_fastqs/DNA160708LC_S93.assembled.removed.fastq ./alignments/DNA160708LC_S93_alignment.vdjca

Alignment: 1.8%
Alignment: 25.3%  ETA: 00:00:09
Alignment: 55.9%  ETA: 00:00:02
Alignment: 86.6%  ETA: 00:00:00

### Assemble command and output

mixcr assemble -f --index ./indexes/S93_index.txt --report ./reports/assemble/S93_assemble.report.txt --threads 4 ./alignments/DNA160708LC_S93_alignment.vdjca ./assemblies/DNA160708LC_S93_alignment_clones.clns

Initialization: progress unknown
Assembling initial clonotypes: 92.3%
Clustering: 94.3%  ETA: 00:00:02
Writing clones: 0%
Exception in thread "main" java.lang.NullPointerException
	at com.milaboratory.mixcr.assembler.IO.write0(IO.java:122)
	at com.milaboratory.mixcr.assembler.IO.access$000(IO.java:45)
	at com.milaboratory.mixcr.assembler.IO$ReadToCloneMappingBtreeSerializer.serialize(IO.java:81)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:385)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:288)
	at org.mapdb.Store.serialize(Store.java:154)
	at org.mapdb.StoreDirect.put(StoreDirect.java:365)
	at org.mapdb.Caches$HashTable.put(Caches.java:216)
	at org.mapdb.Pump.buildTreeMap(Pump.java:470)
	at org.mapdb.DB.createTreeSet(DB.java:1072)
	at org.mapdb.DB$BTreeSetMaker.make(DB.java:749)
	at com.milaboratory.mixcr.cli.ActionAssemble.go(ActionAssemble.java:157)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:147)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:73)

**Comment by dbolotin** [comment]
@weshorton, MiXCR 1.8.3 was just released. It should fix the problem with index.

**Comment by weshorton** [comment]
Great, thank you. Can't wait to use it!
