### ISSUE TITLE
mixcr analyze : error while loading sequence set (whitelist)

### ISSUE THREAD

**Issue by hilalga** [milaboratory/mixcr#1231]
Hi,

I have been using this command (see below) to extract TCR information from my sequencing data. R1 has a barcode (32 nt) and UMI (9nt). I have confirmed that R1 starts with the barcodes. R2 has the VDJ sequence, starting with the V chain (3' capture approach). Our barcode whitelist is A0024_006_BeadBarcodes_linker.txt. It's just a text file with each line having one barcode. 

`mixcr analyze generic-tcr-amplicon-umi --species hsa --rna --verbose --floating-left-alignment-boundary --rigid-right-alignment-boundary  --tag-pattern "^(CELL:N{32})(UMI:N{9})\^(R2:*)" --set-whitelist CELL=file:A0024_006_BeadBarcodes_linker.txt --threads 30 -f TCR1_S1_L001_R1_001.fastq.gz TCR1_S1_L001_R2_001.fastq.gz results/TCR1`

The code runs fine until I get the error that there is a problem in loading the sequences from my whitelist. 

>... 
The following tags and their roles were recognised:
  Payload tags: R2
  Cell tags: CELL
  Molecule tags: UMI
WARNING: 63 non-functional genes excluded.
4.3.2; built=Tue Apr 11 20:35:07 CEST 2023; rev=123d699964; lib=repseqio.v2.2
picocli.CommandLine$ExecutionException: Error while running command align java.lang.RuntimeException: Error while loading sequence set from ./A0024_006_BeadBarcodes_linker.txt
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-13(SourceFile:322)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:365)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-27(SourceFile:430)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:102)
Caused by: java.lang.RuntimeException: Error while loading sequence set from ./A0024_006_BeadBarcodes_linker.txt
        at com.milaboratory.o.ff.a(SourceFile:122)
        at com.milaboratory.mitool.pattern.WhitelistFromAddress.load(SourceFile:167)
        at com.milaboratory.mitool.pattern.WhitelistFromAddress.pack(SourceFile:171)
        at com.milaboratory.mixcr.presets.RefineTagsAndSortMixins$SetWhitelist.pack(SourceFile:651)
        at com.milaboratory.mixcr.presets.RefineTagsAndSortMixins$SetWhitelist.pack(SourceFile:627)
        at com.milaboratory.mixcr.presets.MiXCRMixinPacker.pack(SourceFile:100)
        at com.milaboratory.mixcr.presets.MiXCRMixinPacker.pack(SourceFile:99)
        at com.milaboratory.cli.AbstractPresetBundleRaw$a.a(SourceFile:3037)
        at com.milaboratory.mixcr.presets.MiXCRParamsSpec.pack(SourceFile:73)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd$paramsSpecPacked$2.invoke(SourceFile:750)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd$paramsSpecPacked$2.invoke(SourceFile:750)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd.getParamsSpecPacked(SourceFile:750)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd.createReader(SourceFile:862)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd.run1(SourceFile:977)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-27(SourceFile:430)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 12 more

Not sure what went wrong here. The whitelist file is a basic text file. I also tried with another test file but had the same result. Does anyone have any input how to solve this issue?

Thanks!

**Comment by mizraelson** [comment]
Hi,
For this type of data, you should use a different preset (the one we just added in the latest version 4.4), because the one you used is intended for non-single-cell data. How many cells do you expect? Is it a high-throughput protocol?

```
mixcr analyze generic-ht-single-cell-amplicon-with-umi -f \
  --threads 30 \
  --species hsa \
  --rna \
  --verbose \
  --floating-left-alignment-boundary \
  --rigid-right-alignment-boundary  \
  --tag-pattern "^(CELL:N{32})(UMI:N{9})\^(R2:*)" \
   --set-whitelist CELL=file:A0024_006_BeadBarcodes_linker.txt \
   TCR1_S1_L001_R1_001.fastq.gz \
   TCR1_S1_L001_R2_001.fastq.gz \
   results/TCR1
```

Please let me know if it works. The file you have should work, but just in case, I'm attaching the sample file that I used to test this command.


[whitelist.txt](https://github.com/milaboratory/mixcr/files/11985289/whitelist.txt)

**Comment by hilalga** [comment]
Thank you very much! I will get the new version and try it out!

**Comment by hilalga** [comment]
Hi, 

I have tried the new command in version 4.4 as you suggested. However, I get the same error.

> WARNING: 63 non-functional genes excluded because they are not covering feature to align.
4.4.0; built=Wed Jul 05 20:34:56 CEST 2023; rev=29721c996b; lib=repseqio.v3.0.1
picocli.CommandLine$ExecutionException: Error while running command align java.lang.RuntimeException: Error while loading sequence set from ./wo_space.txt
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-12(SourceFile:323)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$PlanBuilder.executeSteps(SourceFile:470)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:371)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-26(SourceFile:426)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:98)
Caused by: java.lang.RuntimeException: Error while loading sequence set from ./wo_space.txt
        at com.milaboratory.o.dU.a(SourceFile:122)
        at com.milaboratory.mitool.pattern.WhitelistFromAddress.load(SourceFile:167)
        at com.milaboratory.mitool.pattern.WhitelistFromAddress.pack(SourceFile:171)
        at com.milaboratory.mixcr.presets.RefineTagsAndSortMixins$SetWhitelist.pack(SourceFile:624)
        at com.milaboratory.mixcr.presets.RefineTagsAndSortMixins$SetWhitelist.pack(SourceFile:600)
        at com.milaboratory.mixcr.presets.MiXCRMixinPacker.pack(SourceFile:105)
        at com.milaboratory.mixcr.presets.MiXCRMixinPacker.pack(SourceFile:104)
        at com.milaboratory.cli.AbstractPresetBundleRaw$a.a(SourceFile:2037)
        at com.milaboratory.mixcr.presets.MiXCRParamsSpec.pack(SourceFile:76)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd$paramsSpecPacked$2.invoke(SourceFile:816)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd$paramsSpecPacked$2.invoke(SourceFile:816)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd.getParamsSpecPacked(SourceFile:816)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd.createReader(SourceFile:917)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd.run1(SourceFile:1062)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-26(SourceFile:426)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 13 more

Afterwards, I tried to use your whitelist file. Then the command runs successfully, but I really don't understand why. Apart from the length of the barcodes, the files are the same. I double checked for differences in file format and extra spaces but didn't get anywhere. Could the barcode length be the issue? Due to a linker sequence in the middle, they are 32nt, instead of the usual 8-16nt.  I have attached my barcode file below: [](url)
[wo_space.txt](https://github.com/milaboratory/mixcr/files/12037828/wo_space.txt)

Any help would really be appreciated! I am at the end of my wits here. 

Thanks!

**Comment by mizraelson** [comment]
Hi,
You are correct. Currently, there is a limit on the length of tags, and tags with 32 characters or longer are not supported. We are working on fixing this limitation soon.

However, in your specific case, there is an alternative and more suitable approach. I have prepared a dedicated preset for your protocol. Please find the YAML file attached, named "hilalga-sc.yaml.zip". Unzip the file and place it either in your working directory where you run the `mixcr` command from or in the `~/.mixcr/presets/` directory.

Afterward, you can execute the following command (please use the latest mixcr develop version that can be downloaded via this [link](https://link.milaboratory.com/software/mixcr/mixcr-develop.zip)):

```
mixcr analyze local:hilalga-sc \
    TCR1_S1_L001_R1_001.fastq.gz \
    TCR1_S1_L001_R2_001.fastq.gz \
    results/TCR1
```

Feel free to modify this according to your needs.

The preset already includes all the protocol-specific options such as species information, alignment boundary parameters, and your whitelists. In the output clonotype table file, you will find a column called `tagValueCELLID`, which will contain the serial number of the barcode from the provided list.

PS: Just to confirm, are you using an amplicon-based protocol where R2 is a payload read that always starts from a fixed position (likely the C-primer)? 

Please let me know how it works for you.

Mark
[hilalga-sc.yaml.zip](https://github.com/milaboratory/mixcr/files/12071772/hilalga-sc.yaml.zip)
