### ISSUE TITLE
Error MIXCR when using generic amplicon preset

### ISSUE THREAD

**Issue by SandravanW** [milaboratory/mixcr#1238]
Hi all,

I am new to MIXCR and tried to use it to align my fastq files and assemble clonotypes, but received the following error:

4.4.0; built=Wed Jul 05 20:34:56 CEST 2023; rev=29721c996b; lib=repseqio.v3.0.1
picocli.CommandLine$ExecutionException: Error while running command analyze java.lang.RuntimeException: For file: protocols\generic-amplicon.yaml
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-12(SourceFile:323)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:98)
Caused by: java.lang.RuntimeException: For file: protocols\generic-amplicon.yaml
        at com.milaboratory.mixcr.presets.Presets.rawResolve$lambda-4(SourceFile:181)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at com.milaboratory.mixcr.presets.Presets.rawResolve(SourceFile:176)
        at com.milaboratory.mixcr.presets.Presets.access$rawResolve(SourceFile:120)
        at com.milaboratory.mixcr.presets.Presets$MiXCRBundleResolver.resolvePreset(SourceFile:276)
        at com.milaboratory.mixcr.presets.Presets$MiXCRBundleResolver.resolvePreset(SourceFile:271)
        at com.milaboratory.o.s.resolve(SourceFile:1145)
        at com.milaboratory.o.s.resolve$default(SourceFile:170)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:321)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-26(SourceFile:426)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 1 more
Caused by: java.lang.IllegalStateException: No protocols\generic-amplicon.yaml
        at com.milaboratory.mixcr.presets.Presets.rawResolve$lambda-4(SourceFile:178)
        ... 19 more

I used shell in windows and entered the following code:

java -jar .\mixcr.jar analyze generic-amplicon --species HomoSapiens --rna --floating-left-alignment-boundary --floating-right-alignment-boundary J --assemble-clonotypes-by VDJRegion TCRseqdata\sample1_R1_001.fastq.gz TCRseqdata\sample1_R2_001.fastq.gz result

I am not sure what the error means: am I doing something wrong or is there something wrong with the generic-amplicon preset?

Thanks in advance for your help!

**Comment by dbolotin** [comment]
Hi!
Thank you for reporting!
That was a bug related to Windows, we just fixed it and made a dedicated release. Please try [MiXCR v4.4.1](https://github.com/milaboratory/mixcr/releases/tag/v4.4.1).
All the best,
Dmitry.
