### ISSUE TITLE
Exception in thread "main" java.util.zip.ZipException: invalid distance too far back

### ISSUE THREAD

**Issue by SolaimanR** [milaboratory/mixcr#124]
I am trying to run ` mixcr align --library local -s musmusculus ...` after I have imported from IMGT. I get following error message now:

```
Exception in thread "main" java.util.zip.ZipException: invalid distance too far back
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
	at com.milaboratory.core.io.sequence.fastq.FastqRecordsReader$1.read(FastqRecordsReader.java:266)
	at com.milaboratory.core.io.sequence.fastq.FastqRecordsReader$InputDataWrapper.readFully(FastqRecordsReader.java:250)
	at com.milaboratory.core.io.sequence.fastq.FastqRecordsReader.fillBuffer(FastqRecordsReader.java:124)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.<init>(SingleFastqReader.java:256)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.<init>(SingleFastqReader.java:65)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.<init>(SingleFastqReader.java:79)
	at com.milaboratory.mixcr.cli.ActionAlign$AlignParameters.createReader(ActionAlign.java:430)
	at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:181)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:147)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:73)
```

I use java 1.8.0, however also tried it with 1.7.0 (OpenJDK Runtime Environment). Same error message for both.

**Comment by SolaimanR** [comment]
Apologies, my file was corrupted.

**Comment by dbolotin** [comment]
No problem. Cheers.
