### ISSUE TITLE
java.lang.IllegalStateException  error with mixcr-4.4.1

### ISSUE THREAD

**Issue by xmy1990** [milaboratory/mixcr#1312]
Hi,

The command I used mixcr-4.4.1:

```
mixcr analyze exome-seq \
--species hsa \
--threads 8 \
$bam \
$prefix 
```
- I ran my jobs using the above command with **qsub**, and set the **vf=32g,p=16**.
- My input bam data size was among **30~50Gb**.

But an error was as follow

```
java.lang.IllegalStateException: Unexpected buffer behaviour. This might be a sign that you ran out of storage in the output or tmp folder.
        at com.milaboratory.o.zR.completed(SourceFile:1582)
        at com.milaboratory.o.Bk$a.completed(SourceFile:1163)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
        at java.base/sun.nio.ch.SimpleAsynchronousFileChannelImpl$3.run(SimpleAsynchronousFileChannelImpl.java:389)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
I know it may be  the problem with storage, I just found the **--threads**  to set  thread and can not found any other prams.
With **My input bam data among 30~50Gb**, how to set  appropriate  **threads， vf , p ** ？

Thank you for your kind  help!

**Comment by mizraelson** [comment]
Hi, it looks like the issue is not with CPU or memory, but the storage. Can you try the following option:
`--use-local-temp` and let me know if it works.

**Comment by xmy1990** [comment]
hi @mizraelson,
I added `--use-local-temp`, but another error was as follow:

```Not enough memory for run command, try to increase -Xmx. Available memory: 65536 Mb
Example: mixcr -Xmx40g analyze exome-seq --species hsa --threads 8 --use-local-temp test.bam out
This run used approximately 308m of memory
```
Then I tried 

```
mixcr -Xmx40g analyze exome-seq --species hsa --threads 8 --use-local-temp test.bam out
```
The error befor happened again:
```
java.lang.IllegalStateException: Unexpected buffer behaviour. This might be a sign that you ran out of storage in the output or tmp folder.
        at com.milaboratory.o.zR.completed(SourceFile:1582)
        at com.milaboratory.o.Bk$a.completed(SourceFile:1163)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
        at java.base/sun.nio.ch.SimpleAsynchronousFileChannelImpl$3.run(SimpleAsynchronousFileChannelImpl.java:389)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
Thanks!

**Comment by mizraelson** [comment]
Whats the difference between the commands you have tried? Can you please share what another error you got?

**Comment by mizraelson** [comment]
Hi, were you able to resolve the issue?

**Comment by xmy1990** [comment]
Hi @mizraelson,

I have not resolved the storage issue which may be caused by our **50+ Gb WES data**.
Even though some samples successfully got VDJ rearrangement results with MIXCR, **the time is as long as 10+ hours** which was unbearable.
I have just done an initial exploration for VDJ rearrangement and I may continue to solve this issue in the future.

Thank you for your kind help!
