### ISSUE TITLE
problem installation on MAC

### ISSUE THREAD

**Issue by silvia1234567890** [milaboratory/mixcr#1391]
Hello,

I just installed MiXCR on my mac. But when I want to check if mixcr works with the command: 
`> ~/mixcr/mixcr -v`

I get this error:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/milaboratory/mixcr/cli/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:635)
```
I have the latest version of JAVA installed.. I don't know where is the problem..please help me.

Thank you

**Comment by li1311139481** [comment]
Hi, I have the same problem, how did you solve it ?

**Comment by mizraelson** [comment]
What JAVA version do you have?

**Comment by li1311139481** [comment]
> What JAVA version do you have?

My java version is 
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)

my mixcr version is 4.6.0.
I know that mixcr4.6.0 need openjdk>11.0. but when I install java11. I get 
```
java.lang.RuntimeException: java.io.IOException: Input/output error
        at com.milaboratory.o.cy.a(SourceFile:137)
        at com.milaboratory.o.cB$a.run(SourceFile:420)
Caused by: java.io.IOException: Input/output error
        at java.base/sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
        at java.base/sun.nio.ch.FileDispatcherImpl.lock(Unknown Source)
        at java.base/sun.nio.ch.FileChannelImpl.lock(Unknown Source)
        at java.base/java.nio.channels.FileChannel.lock(Unknown Source)
        at com.milaboratory.o.cy.a(SourceFile:116)
        ... 1 more
License manager thread died.
License error: UnknownError
```
When i use java1.8 
i get 
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/milaboratory/mixcr/cli/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:635)
```
BTW. I do not have permission to install mixcr using docker and brew. I downloaded java myself, and I downloaded mixcr in conda with `conda install -c milaboratories mixcr --no-deps`

**Comment by mizraelson** [comment]
Can you please try downloading the latest Java from [here](https://www.oracle.com/java/technologies/downloads/) and see if the error persists. Also, can you download MiXCR using the direct link: https://github.com/milaboratory/mixcr/releases/download/v4.6.0/mixcr-4.6.0.zip

And then run it as:

`java -jar mixcr.jar -h`

**Comment by li1311139481** [comment]
> Can you please try downloading the latest Java from [here](https://www.oracle.com/java/technologies/downloads/) and see if the error persists. Also, can you download MiXCR using the direct link: https://github.com/milaboratory/mixcr/releases/download/v4.6.0/mixcr-4.6.0.zip
> 
> And then run it as:
> 
> `java -jar mixcr.jar -h`

Thanks for your reply
I tried install java and mixcr according your instrction. 
but i get error when i run` java -jar mixcr.jar -h`

```
[01:32:58][hlhuang][68]:mixcr$ java -jar "/cluster/facility/hlhuang/miniconda3/envs/mixcr/share/mixcr-4.6.0-0/mixcr.jar" -h
java.lang.RuntimeException: java.io.IOException: Input/output error
        at com.milaboratory.o.cy.a(SourceFile:137)
        at com.milaboratory.o.cB$a.run(SourceFile:420)
Caused by: java.io.IOException: Input/output error
        at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock0(Native Method)
        at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock(UnixFileDispatcherImpl.java:99)
        at java.base/sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1487)
        at java.base/java.nio.channels.FileChannel.lock(FileChannel.java:1240)
        at com.milaboratory.o.cy.a(SourceFile:116)
        ... 1 more
License manager thread died.
License error: UnknownError
```

my java version:
```
[01:29:38][hlhuang][59]:mixcr$ javac -version
javac 21.0.1
[01:29:50][hlhuang][60]:mixcr$ java -version
java version "21.0.1" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)

```

my ~/.bash_profile file 

```
export JAVA_HOME=/cluster/facility/hlhuang/APP/java/jdk-21.0.1/
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
export PATH=${JAVA_HOME}/bin:$PATH
```

**Comment by mizraelson** [comment]
It seems like there is an issue with permissions to the directory with license `~/.mi/`. 

Can you try running:
`chmod -R 777 ~/.mi/`

It can also be due to issues with disk mount or lack of storage space.

**Comment by li1311139481** [comment]
Thank you. Still not working
```
[12:26:40][hlhuang][213]:mixcr$ ls -lh ~/.mi
total 512
drwxrwxrwx 2 hlhuang hlhuang 3 Jan  3 00:22 com.milaboratory.mixcr.cli.Main
[12:26:58][hlhuang][214]:mixcr$ ls -lh ~/.mi/*
total 512
-rwxrwxrwx 1 hlhuang hlhuang 0 Jan  3 00:22 milicenashfingprintlock

[12:26:40][hlhuang][213]:mixcr$ ls -lh ~/.mi
total 512
drwxrwxrwx 2 hlhuang hlhuang 3 Jan  3 00:22 com.milaboratory.mixcr.cli.Main
[12:26:58][hlhuang][214]:mixcr$ ls -lh ~/.mi/*
total 512
-rwxrwxrwx 1 hlhuang hlhuang 0 Jan  3 00:22 milicenashfingprintlock
[12:27:04][hlhuang][215]:mixcr$ java -jar "/cluster/facility/hlhuang/APP/mixcr/mixcr.jar" activate-license
Please enter the license:
************************************ my license*****************************************
Checking the license...
java.lang.RuntimeException: java.io.IOException: Input/output error
        at com.milaboratory.o.cy.a(SourceFile:137)
        at com.milaboratory.o.cB$a.run(SourceFile:420)
Caused by: java.io.IOException: Input/output error
        at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock0(Native Method)
        at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock(UnixFileDispatcherImpl.java:99)
        at java.base/sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1487)
        at java.base/java.nio.channels.FileChannel.lock(FileChannel.java:1240)
        at com.milaboratory.o.cy.a(SourceFile:116)
        ... 1 more
License manager thread died.
License Error:
UnknownError
null

```

**Comment by silvia1234567890** [comment]
Hi, I think your problem is related to the license.. I don't remember well how I solved this problem, because I tried different things.. If your problem is about the license:

I activated the license for academics through this link: https://licensing.milaboratories.com/
And then, in the terminal:
```
> mixcr activate-license

  Please enter the license: ...
```
And in my case, I use mixcr through anaconda:
In the terminal (Mac) I just run:
```
> conda activate /Users/Silvia/anaconda3
> mixcr
```

**Comment by li1311139481** [comment]
I tried install mixcr  using conda. and the same error happened. 
I'm sure there's nothing wrong with my license, because i can activate mixcr in docker environment. but I don't like use docker. 
```
(mixcr) [06:27:29][hlhuang][9]:~$ which mixcr
/cluster/facility/hlhuang/miniconda3/envs/mixcr/bin/mixcr
(mixcr) [06:27:31][hlhuang][10]:~$ mixcr  -v
MiXCR v4.6.0 (built Sun Dec 10 03:48:42 CST 2023; rev=c9fafa41fe; branch=no_branch; host=fv-az520-378)
RepSeq.IO v2.4.0 (rev=5b5b4475b8)
MiLib v3.4.0 (rev=d42f072b23)
Built-in V/D/J/C library: repseqio.v4.0

Library search path:
- built-in libraries
- /cluster/home/hlhuang/.
(mixcr) [06:27:37][hlhuang][11]:~$ mixcr activate-license
Please enter the license:

Checking the license...
java.lang.RuntimeException: java.io.IOException: Input/output error
        at com.milaboratory.o.cy.a(SourceFile:137)
        at com.milaboratory.o.cB$a.run(SourceFile:420)
Caused by: java.io.IOException: Input/output error
        at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock0(Native Method)
        at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock(UnixFileDispatcherImpl.java:99)
        at java.base/sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1487)
        at java.base/java.nio.channels.FileChannel.lock(FileChannel.java:1240)
        at com.milaboratory.o.cy.a(SourceFile:116)
        ... 1 more
License manager thread died.
License Error:
UnknownError
null
(mixcr) [06:27:54][hlhuang][12]:~$ which java
/cluster/facility/hlhuang/miniconda3/envs/mixcr/bin/java

```

**Comment by silvia1234567890** [comment]
I just checked and we have the same java version and mixcr version... 
```
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)
```

```
MiXCR v4.6.0 (built Sat Dec 09 20:48:42 CET 2023; rev=c9fafa41fe; branch=no_branch; host=fv-az520-378)
RepSeq.IO v2.4.0 (rev=5b5b4475b8)
MiLib v3.4.0 (rev=d42f072b23)
Built-in V/D/J/C library: repseqio.v4.0

Library search path:
- built-in libraries
- /Users/Silvia/.
```
Which java version do you have in conda?
Mine is:
```
openjdk 21.0.1 2023-10-17 LTS
OpenJDK Runtime Environment Zulu21.30+15-CA (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu21.30+15-CA (build 21.0.1+12-LTS, mixed mode, sharing)
```

**Comment by li1311139481** [comment]
because i install mixcr using miniconda. so when I activate the environment of mixcr. it contain a openjdk. so my versionn like this:
```
(mixcr) [09:16:51][hlhuang][33]:20241231_B22GY5KLT3_U1244_ZF084_M_IV_TCRab$ which java
/cluster/facility/hlhuang/miniconda3/envs/mixcr/bin/java
(mixcr) [09:16:53][hlhuang][34]:20241231_B22GY5KLT3_U1244_ZF084_M_IV_TCRab$ java -version
openjdk version "21.0.1-internal" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1-internal-adhoc.conda.src)
OpenJDK 64-Bit Server VM (build 21.0.1-internal-adhoc.conda.src, mixed mode, sharing)
(mixcr) [09:16:57][hlhuang][35]:20241231_B22GY5KLT3_U1244_ZF084_M_IV_TCRab$ javac -version
javac 21.0.1-internal
(mixcr) [09:17:39][hlhuang][36]:20241231_B22GY5KLT3_U1244_ZF084_M_IV_TCRab$ mixcr -v
MiXCR v4.6.0 (built Sun Dec 10 03:48:42 CST 2023; rev=c9fafa41fe; branch=no_branch; host=fv-az520-378)
RepSeq.IO v2.4.0 (rev=5b5b4475b8)
MiLib v3.4.0 (rev=d42f072b23)
Built-in V/D/J/C library: repseqio.v4.0

Library search path:
- built-in libraries
- /cluster/facility/hlhuang/zifeng001/ZF084_maxima_SSIV_bulk_TCRseq/20241231_B22GY5KLT3_U1244_ZF084_M_IV_TCRab/.
```

I have java version:
```
java version "21.0.1" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)

```
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)

```
but all java can't work

**Comment by mizraelson** [comment]
The issue appears to stem from the inability to lock a file in the `.mi` directory. This could be due to one of two reasons:

   1) The lock might have been placed by another process. To investigate this possibility, please try deleting the .mi directory and then rerunning `mixcr`.
   2) The filesystem in use might not support file locking. Could you specify where you are running mixcr? Are you using a standard filesystem like Mac's APFS, Linux, or Windows' NTFS, which generally support file locking? Or are you using a different filesystem such as FAT32, or a networked and distributed filesystem like GlusterFS, which typically do not support file locking?

**Comment by li1311139481** [comment]
@mizraelson  Thanks for your reply
1. **I tried rm -rf ~/.mi. and rerun the code below. but not work**
```
java -jar "/cluster/facility/hlhuang/APP/mixcr/mixcr.jar" activate-license
input my license
```
or using mixcr installed from conda
```
mixcr activate-license
input my license
```
I get same error 
```
Checking the license...
java.lang.RuntimeException: java.io.IOException: Input/output error
        at com.milaboratory.o.cy.a(SourceFile:137)
        at com.milaboratory.o.cB$a.run(SourceFile:420)
Caused by: java.io.IOException: Input/output error
        at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock0(Native Method)
        at java.base/sun.nio.ch.UnixFileDispatcherImpl.lock(UnixFileDispatcherImpl.java:99)
        at java.base/sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1487)
        at java.base/java.nio.channels.FileChannel.lock(FileChannel.java:1240)
        at com.milaboratory.o.cy.a(SourceFile:116)
        ... 1 more
License manager thread died.
License Error:
UnknownError
null
```

2. **I am new to linux and I looked up some commands and I think my file system is XFS?**
```
(mixcr) [01:07:00][hlhuang][154]:APP$ df -h
Filesystem                    Size  Used Avail Use% Mounted on
/dev/sda1                     187G   71G  116G  38% /
devtmpfs                      599G     0  599G   0% /dev
tmpfs                         599G  240K  599G   1% /dev/shm
tmpfs                         599G  179M  598G   1% /run
tmpfs                         599G     0  599G   0% /sys/fs/cgroup
head1-10g0:/cluster            62T   46T   17T  74% /cluster
head1-10g0:/cluster/home       18T  456G   17T   3% /cluster/home
head1-10g0:/cluster/huanglab  108T   91T   17T  85% /cluster/huanglab
node3:/cluster2                99T   57T   42T  58% /cluster2
(mixcr) [01:21:30][hlhuang][155]:APP$ df -T
Filesystem                   Type        1K-blocks        Used   Available Use% Mounted on
/dev/sda1                    xfs         195216252    73730788   121485464  38% /
devtmpfs                     devtmpfs    627174264           0   627174264   0% /dev
tmpfs                        tmpfs       627189376         240   627189136   1% /dev/shm
tmpfs                        tmpfs       627189376      183016   627006360   1% /run
tmpfs                        tmpfs       627189376           0   627189376   0% /sys/fs/cgroup
head1-10g0:/cluster          nfs4      66542997504 48725812224 17817185280  74% /cluster
head1-10g0:/cluster/home     nfs4      18295302144   478116864 17817185280   3% /cluster/home
head1-10g0:/cluster/huanglab nfs4     115289069568 97471884288 17817185280  85% /cluster/huanglab
node3:/cluster2              nfs4     105461161984 60475267072 44985894912  58% /cluster2
(mixcr) [01:23:25][hlhuang][156]:APP$ lsblk -f
NAME   FSTYPE LABEL UUID                                 MOUNTPOINT
sda
└─sda1 xfs          c1761d3e-bbf1-461e-8a94-f7214206242e /
(mixcr) [01:23:48][hlhuang][157]:APP$ blkid
(mixcr) [01:23:56][hlhuang][158]:APP$ cat /etc/fstab

UUID=c1761d3e-bbf1-461e-8a94-f7214206242e /                       xfs     defaults        0 0
```

**Comment by mizraelson** [comment]
From your output, I see that your home folder resides on `nfs` network drive.
Please provide the output of the:
- `pwd` and `ls -la` commands in the terminal after you log into the server
- `mount` command

 It seems that it's a permission error.

**Comment by li1311139481** [comment]
> From your output, I see that your home folder resides on `nfs` network drive. Please provide the output of the:
> 
> * `pwd` and `ls -la` commands in the terminal after you log into the server
> * `mount` command
> 
> It seems that it's a permission error.

```
[11:45:01][hlhuang][1]:~$ pwd
/cluster/home/hlhuang
[11:45:04][hlhuang][2]:~$ ls -la
total 500
drwx------ 41 hlhuang hlhuang     73 Jan  5 23:44 .
drwxr-xr-x 69 root    root        69 Nov  4 15:14 ..
drwxrwxr-x  3 hlhuang hlhuang      3 Sep 24  2022 .anaconda_backup
drwx------  4 hlhuang hlhuang      4 Jan  2 01:59 .apptainer
-rw-------  1 hlhuang hlhuang 207213 Jan  5 02:03 .bash_history
-rw-r--r--  1 hlhuang hlhuang     18 Aug  3  2016 .bash_logout
-rw-r--r--  1 hlhuang hlhuang    417 Jan  4 13:02 .bash_profile
-rw-------  1 hlhuang hlhuang  12288 Aug 14  2022 .bash_profile.swo
-rw-------  1 hlhuang hlhuang  12288 Aug 14  2022 .bash_profile.swp
-rw-rw-r--  1 hlhuang hlhuang   4458 Jan  2 00:15 .bashrc
-rw-r--r--  1 hlhuang hlhuang  12288 Aug 25  2022 .bashrc.swo
-rw-r--r--  1 hlhuang hlhuang  12288 Aug  4  2022 .bashrc.swp
drwxr-xr-x  6 hlhuang hlhuang      9 Nov  7 00:04 bin
drwxr-xr-x 19 hlhuang hlhuang     20 Nov  9 17:40 .cache
drwxrwxr-x  2 hlhuang hlhuang     34 Apr  4  2023 code
drwxrwxr-x  4 hlhuang hlhuang      5 Aug 18 11:14 .conda
-rw-rw-r--  1 hlhuang hlhuang     78 Sep  3 02:19 .condarc
-rw-------  1 hlhuang hlhuang  12288 Aug 10  2022 .condarc.swo
-rw-------  1 hlhuang hlhuang  12288 Aug 10  2022 .condarc.swp
drwxr-x--- 16 hlhuang hlhuang     16 Nov 17  2022 .config
drwx------  3 hlhuang hlhuang      3 Aug  9  2022 .dbus
drwxr-xr-x  3 hlhuang hlhuang      3 Oct 19  2022 Desktop
drwx------  3 hlhuang hlhuang      4 Oct 19  2022 Downloads
-rw-------  1 hlhuang hlhuang     16 Aug 10  2022 .esd_auth
-rw-rw-r--  1 hlhuang hlhuang     78 Nov  6  2022 .gitconfig
drwxrwxr-x  3 hlhuang hlhuang      3 Nov 17  2022 go
drwxrwxr-x  4 hlhuang hlhuang      5 Apr  3  2023 gsea_home
drwxrwxr-x  3 hlhuang hlhuang      6 Jan 13  2023 igv
drwxrwxr-x  2 hlhuang hlhuang      3 Jan 13  2023 .igv
lrwxrwxrwx  1 hlhuang hlhuang     35 Feb 15  2023 .ipython -> /cluster/facility/hlhuang/.ipython/
drwxrwxr-x  4 hlhuang hlhuang      4 Oct 27  2022 .java
drwx------  4 hlhuang hlhuang      6 Oct 14 12:17 .jupyter
-rw-rw-r--  1 hlhuang hlhuang  39392 Nov  6 21:44 jupyter_lab_config1.py
-rw-rw-r--  1 hlhuang hlhuang  37752 May  7  2023 jupyter_lab_config.py
-rw-------  1 hlhuang hlhuang    306 Jul  5  2023 .lesshst
drwxr-x---  5 hlhuang hlhuang      5 Dec 22  2022 .local
drwxrwxr-x  3 hlhuang hlhuang      3 Apr 22  2023 .matplotlib
drwxrwxr-x  3 hlhuang hlhuang      3 Jan  4 13:04 .mi
-rw-r--r--  1 hlhuang hlhuang    619 Dec 24 10:58 mi.license
drwxrwxr-x  3 hlhuang hlhuang      3 Apr 22  2023 .mozilla
drwx------  2 hlhuang hlhuang      3 Aug 10  2022 .ncbi
-rw-rw-r--  1 hlhuang hlhuang    705 Feb  3  2023 .ncbirc
drwxrwxr-x  7 hlhuang hlhuang      8 Apr  9  2023 .nextflow
drwxrwxr-x  4 hlhuang hlhuang      5 Oct 20  2022 .npm
drwxrwxr-x  2 hlhuang hlhuang      4 Jun 26  2022 .oracle_jre_usage
drwxrw----  3 hlhuang hlhuang      3 Sep 13  2022 .pki
-rw-------  1 hlhuang hlhuang   3180 Oct 14 03:40 .python_history
drwxr-xr-x  3 hlhuang hlhuang      3 Jul 18  2022 .R
-rw-rw-r--  1 hlhuang hlhuang  10099 Sep  7 09:59 .radian_history
drwxrwxr-x  2 hlhuang hlhuang     14 Apr 23  2023 rgtdata
-rw-------  1 hlhuang hlhuang     66 Aug 25 17:09 .Rhistory
drwxrwxr-x  3 hlhuang hlhuang      3 Aug 25  2022 RNAseq
-rw-------  1 hlhuang hlhuang  12288 Oct 19  2022 .rserver.conf.swp
drwxr-xr-x 20 hlhuang hlhuang     27 Dec 29 23:53 .rstudio
-rw-rw-r--  1 hlhuang hlhuang     44 Sep  5  2022 .screenrc
drwxrwxr-x 11 hlhuang hlhuang     11 Jul 26  2022 .sdkman
drwx------  3 hlhuang hlhuang      3 Nov  8 12:43 .singularity
drwx------  2 hlhuang hlhuang      8 Aug 19 01:37 .ssh
drwxrwxr-x  3 hlhuang hlhuang      5 May  8  2023 ssh_copy
-rwxrwxr-x  1 hlhuang hlhuang   8672 Nov  6 21:56 tempCodeRunnerFile
-rw-rw-r--  1 hlhuang hlhuang    234 Nov  6 21:56 tempCodeRunnerFile.c
-rwS--s---  1 hlhuang hlhuang      0 Nov  6 21:56 test.db
drwxrwxr-x  6 hlhuang hlhuang      6 Oct 19 00:35 .transfer_client
-rw-------  1 hlhuang hlhuang   4172 Aug 10  2022 .viminfo.tmp
drwxrwxr-x  2 hlhuang hlhuang      2 Nov 11  2022 .virtual_documents
drwxrwxr-x  2 hlhuang hlhuang      5 Apr 22  2023 .vscode-R
drwxrwxr-x  5 hlhuang hlhuang     20 Dec 25 01:06 .vscode-server
-rw-rw-r--  1 hlhuang hlhuang    320 Oct  3 11:48 .wget-hsts
-rw-rw-r--  1 hlhuang hlhuang      0 Jun 27  2023 withCallingHandlers
drwxrwxr-x  9 hlhuang hlhuang      9 Nov 18  2022 work
-rw-------  1 hlhuang hlhuang   1020 Jan  5 23:44 .Xauthority
drwxrwxr-x  4 hlhuang hlhuang      4 Oct  6 14:23 .yarn
-rw-rw-r--  1 hlhuang hlhuang    717 Aug 14  2022 .zshrc
[11:45:08][hlhuang][3]:~$ mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=627174264k,nr_inodes=156793566,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio,net_cls)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/sda1 on / type xfs (rw,relatime,attr2,inode64,noquota)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
head1-10g0:/cluster on /cluster type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.1.2.1,local_lock=none,addr=10.1.0.1)
head1-10g0:/cluster/home on /cluster/home type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.1.2.1,local_lock=none,addr=10.1.0.1)
head1-10g0:/cluster/huanglab on /cluster/huanglab type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.1.2.1,local_lock=none,addr=10.1.0.1)
node3:/cluster2 on /cluster2 type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.0.2.1,local_lock=none,addr=10.0.2.3)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)

```

**Comment by Coke-Zhang** [comment]
Hello, @mizraelson 
 I have the same error with @li1311139481 , my home folder resides on `nfs` network drive, and when I run `mixcr `still have the error:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/milaboratory/mixcr/cli/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:641)

```
Please give me suggestions. Thanks!

**Comment by Coke-Zhang** [comment]
> Hello, @mizraelson I have the same error with @li1311139481 , my home folder resides on `nfs` network drive, and when I run `mixcr `still have the error:
> 
> ```
> Exception in thread "main" java.lang.UnsupportedClassVersionError: com/milaboratory/mixcr/cli/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:641)
> ```
> 
> Please give me suggestions. Thanks!

I have tried all the above-mentioned inquiry and troubleshooting processes, and almost all of the above errors occurred on my Linux operating system, but I am currently unable to resolve them.

**Comment by mizraelson** [comment]
Can you share the output of `java -version`
