### ISSUE TITLE
exportClonesOverlap fails when output directory does not exist

### ISSUE THREAD

**Issue by vincentwalter** [milaboratory/mixcr#1401]
exportClonesOverlap fails when the output directory does not exist. This is inconsistent behavior because pretty much all other commands create the output directory if it does not exist.

## Expected Result

Exporting clone overlap via exportClonesOverlap should create the output directory if it does not exist.

## Actual Result

A FileNotFoundException is thrown

## Exact MiXCR commands 

`mixcr exportClonesOverlap --chains TRB *.clns tables/output.tsv`

## MiXCR report files 

````
vwalter@work:~/projects/mixcr$ ls
sample1.clns  sample2.clns
vwalter@work:~/projects/mixcr$ mixcr exportClonesOverlap --chains TRB *.clns tables/output.tsv
Calculating dataset counts: progress unknown
Please copy the following information along with the stacktrace:
   Version: 4.5.0; built=Fri Sep 22 14:39:05 CEST 2023; rev=cdb24b4fb7; lib=repseqio.v3.0.1
        OS: Linux
      Java: 11.0.20.1
  Cmd args: exportClonesOverlap --chains TRB sample1.clns sample2.clns tables/output.tsv
picocli.CommandLine$ExecutionException: Error while running command exportClonesOverlap java.io.FileNotFoundException: /home/vwalter/projects/mixcr/tables/output.TRB.tsv (No such file or directory)
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-12(SourceFile:340)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:98)
Caused by: java.io.FileNotFoundException: /home/vwalter/projects/mixcr/tables/output.TRB.tsv (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
        at com.milaboratory.mixcr.cli.CommandExportOverlap$InfoWriter.<init>(SourceFile:249)
        at com.milaboratory.mixcr.cli.CommandExportOverlap.run1(SourceFile:226)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-26(SourceFile:447)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 1 more
vwalter@work:~/projects/mixcr$ tree
.
├── sample1.clns
└── sample2.clns

0 directories, 2 files
vwalter@work:~/projects/mixcr$ mkdir tables
vwalter@work:~/projects/mixcr$ mixcr exportClonesOverlap --chains TRB *.clns tables/output.tsv
Calculating dataset counts: progress unknown
Calculating overlap: 9%
vwalter@work:~/projects/mixcr$ tree
.
├── sample1.clns
├── sample2.clns
└── tables
    └── output.TRB.tsv

1 directory, 3 files
```

**Comment by mizraelson** [comment]
Thank you for bringing this up. We fixed the issue in the develop version.
