### ISSUE TITLE
Error analyzing bam file

### ISSUE THREAD

**Issue by malonzm1** [milaboratory/mixcr#1428]
Hi,

When I run the following:

```
mixcr -Xmx60g analyze 10x-sc-xcr-vdj -s hsa --rna --threads 4 --force-overwrite PM1_CD4_SF_p3.possorted_genome_bam.bam SRR12898554
```

I get the following error:

```
The following tags and their roles will be associated with each output alignment:
  Payload tags: R2
  Cell tags: CELL(SQ)
  Molecule tags: UMI(SQ)
Alignment: 0%
4.4.1; built=Thu Jul 06 20:36:41 EEST 2023; rev=f7cd556c6c; lib=repseqio.v3.0.1
picocli.CommandLine$ExecutionException: Error while running command align java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-12(SourceFile:323)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$PlanBuilder.executeSteps(SourceFile:470)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:371)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-26(SourceFile:426)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:98)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.base/java.util.Collections$SingletonList.get(Collections.java:4849)
        at com.milaboratory.o.cY.a(SourceFile:3082)
        at com.milaboratory.mixcr.cli.CommandAlignPipeline$TagsExtractor.parse(SourceFile:380)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd$run1$lambda-11$$inlined$mapUnchunked$1.process(SourceFile:36)
        at cc.redberry.pipe.CUtils.lambda$chunked$2(CUtils.java:182)
        at cc.redberry.pipe.util.SimpleProcessorWrapper.take(SimpleProcessorWrapper.java:43)
        at cc.redberry.pipe.util.SimpleProcessorWrapper.take(SimpleProcessorWrapper.java:40)
        at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:306)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
Please advise.

Thanks and good day.

**Comment by mizraelson** [comment]
Can you confirm the issue still occurs with the latest MiXCR v 4.5?

**Comment by malonzm1** [comment]
Yes, it still occurs.

```
Please copy the following information along with the stacktrace:
   Version: 4.5.0; built=Fri Sep 22 15:39:05 EEST 2023; rev=cdb24b4fb7; lib=repseqio.v3.0.1
        OS: Linux
      Java: 11.0.13
picocli.CommandLine$ExecutionException: Error while running command align java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
     at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-12(SourceFile:340)
     at picocli.CommandLine.execute(CommandLine.java:2088)
     at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$PlanBuilder.executeSteps(SourceFile:478)
     at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:368)
     at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
     at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
     at picocli.CommandLine.access$1300(CommandLine.java:145)
     at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
     at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
     at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
     at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
     at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
     at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-26(SourceFile:447)
     at picocli.CommandLine.execute(CommandLine.java:2078)
     at com.milaboratory.mixcr.cli.Main.main(SourceFile:98)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
     at java.base/java.util.Collections$SingletonList.get(Collections.java:4849)
     at com.milaboratory.o.df.a(SourceFile:3081)
     at com.milaboratory.mixcr.cli.CommandAlignPipeline$TagsExtractor.parse(SourceFile:409)
     at com.milaboratory.mixcr.cli.CommandAlign$Cmd$run1$lambda-15$$inlined$mapUnchunked$1.process(SourceFile:36)
     at cc.redberry.pipe.CUtils.lambda$chunked$2(CUtils.java:182)
     at cc.redberry.pipe.util.SimpleProcessorWrapper.take(SimpleProcessorWrapper.java:43)
     at cc.redberry.pipe.util.SimpleProcessorWrapper.take(SimpleProcessorWrapper.java:40)
     at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:306)
     at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mizraelson** [comment]
Currently we do not support using 10x `bam` files, because CELL and UMI tags are saved as separate fields in it and not as a read sequence. We will add such feature in the future, please use FASTQ files with 10x data for now.

**Comment by ggruenhagen3** [comment]
Is this still a known issue? I'm getting this error (`java.lang.IndexOutOfBoundsException`) and am guess it's because 10x `bam` files are still not supported.

**Comment by mizraelson** [comment]
Yes, it depends on the way BAM file was created. If the tags were not extracted it should work. But recommend using raw FASTQ files.
