### ISSUE TITLE
Error while running command exportClones: While adding VEndTrimmed error: Wrong position value

### ISSUE THREAD

**Issue by FreundLab-Michal** [milaboratory/mixcr#1510]
## Expected Result

Export all 27663 clones with mutations information to tsv file

## Actual Result

Exported only 3073 clones and stopped with an error 

## Exact MiXCR commands and error

```
Version: 4.6.0; built=Sat Dec 09 21:48:42 IST 2023; rev=c9fafa41fe; lib=repseqio.v4.0
        OS: Mac OS X
      Java: 21.0.1
  Cmd args: exportClones --drop-default-fields -cloneId -readCount -uniqueTagCount Molecule -vHit -dHit -jHit -cHit -aaFeature CDR3 -nLength CDR3 -aaLength CDR3 -allNMutations -allAAMutations HD11_S5_L001.clns ../Sequences/HD11.tsv
picocli.CommandLine$ExecutionException: Error while running command exportClones java.lang.IllegalArgumentException: While adding VEndTrimmed error: Wrong position value: -4
	at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-12(SourceFile:395)
	at picocli.CommandLine.execute(CommandLine.java:2088)
	at com.milaboratory.mixcr.cli.Main.main(SourceFile:101)
Caused by: java.lang.IllegalArgumentException: While adding VEndTrimmed error: Wrong position value: -4
	at com.milaboratory.o.FM.a(SourceFile:75)
	at com.milaboratory.o.ur.a(SourceFile:1586)
	at com.milaboratory.o.ur.b(SourceFile:1480)
	at com.milaboratory.o.ur.b(SourceFile:1468)
	at com.milaboratory.o.uc.invoke(SourceFile:1701)
	at com.milaboratory.o.lt.extractValue(SourceFile:1216)
	at com.milaboratory.mixcr.export.FieldWithParameters$create$2.invoke(SourceFile:583)
	at com.milaboratory.mixcr.export.FieldWithParameters$create$2.invoke(SourceFile:582)
	at com.milaboratory.o.lE.a(SourceFile:25)
	at com.milaboratory.o.mp.put(SourceFile:40)
	at cc.redberry.pipe.CUtils.drain(CUtils.java:82)
	at cc.redberry.pipe.util.PipeExtensionsKt.drainToAndClose(PipeExtensions.kt:155)
	at com.milaboratory.mixcr.cli.CommandExportClones$Cmd.run1$runExport(SourceFile:322)
	at com.milaboratory.mixcr.cli.CommandExportClones$Cmd.run1(SourceFile:369)
	at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-27(SourceFile:514)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	... 1 more
```

When trying to export without the mutations data, it works well. 

Defult setting of ExportClones tsv file - [HD11_S5_L001.clones_IGH.tsv.zip](https://github.com/milaboratory/mixcr/files/13975666/HD11_S5_L001.clones_IGH.tsv.zip)
Short file with mutations - [HD11_IGH.tsv.zip](https://github.com/milaboratory/mixcr/files/13975678/HD11_IGH.tsv.zip)
cln file - [HD11_S5_L001.clns.zip](https://github.com/milaboratory/mixcr/files/13975681/HD11_S5_L001.clns.zip)
Assemble report - [HD11_S5_L001.assemble.report.txt](https://github.com/milaboratory/mixcr/files/13975688/HD11_S5_L001.assemble.report.txt)

Michal

**Comment by mizraelson** [comment]
Hi, can you please try using the latest [develop version](https://link.milaboratory.com/software/mixcr/mixcr-develop.zip). It seems like a bug that we have just fixed.

**Comment by FreundLab-Michal** [comment]
great, it works! thank you!

**Comment by FreundLab-Michal** [comment]
great, it works! thank you!
