### ISSUE TITLE
Java run issue

### ISSUE THREAD

**Issue by Gaut1993** [milaboratory/mixcr#1516]
Hello,

I have an issue when I try to run mixcr for the first time, it appears to be related to java version : 

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/milaboratory/mixcr/cli/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:635)

What should I do to correct this issue ? Thank you !

**Comment by mizraelson** [comment]
Hi,
What Java version do you have?

**Comment by Gaut1993** [comment]
Hello I'm using :
java version "1.8.0_401"
Java(TM) SE Runtime Environment (build 1.8.0_401-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.401-b10, mixed mode)

**Comment by mizraelson** [comment]
MiXCR is not compatible with 1.8. I recommend updating to the [latest version](https://www.oracle.com/java/technologies/downloads/).
