### ISSUE TITLE
Error while running command buildLibrary java.lang.IllegalArgumentException: Unknown symbol " "

### ISSUE THREAD

**Issue by silvia1234567890** [milaboratory/mixcr#1550]
Hello,

I'm making a library for another species, and I'm getting this error, could you help me please?

Code:

```
mixcr buildLibrary --debug \
  --v-genes-from-fasta TRAV.fasta \
  --v-gene-feature VExon2 \
  --j-genes-from-fasta TRAJ.fasta \
  --chain TRA \
  --taxon-id 8022 \
  --species Oncorhynchus_mykiss \
  Omykiss-TRA.json.gz
```

Error message:
```
Please copy the following information along with the stacktrace:
   Version: 4.6.0; built=Sat Dec 09 20:48:42 CET 2023; rev=c9fafa41fe; lib=repseqio.v4.0
        OS: Mac OS X
      Java: 21.0.2
  Cmd args: buildLibrary --debug --v-genes-from-fasta TRAV.fasta --v-gene-feature VExon2 --j-genes-from-fasta TRAJ.fasta --chain TRA --taxon-id 8022 --species Oncorhynchus_mykiss Omykiss-TRA.json.gz
picocli.CommandLine$ExecutionException: Error while running command buildLibrary java.lang.IllegalArgumentException: Unknown symbol " "
	at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-12(SourceFile:395)
	at picocli.CommandLine.execute(CommandLine.java:2088)
	at com.milaboratory.mixcr.cli.Main.main(SourceFile:101)
Caused by: java.lang.IllegalArgumentException: Unknown symbol " "
	at com.milaboratory.o.bJ.dataFromChars(SourceFile:90)
	at com.milaboratory.o.bJ.<init>(SourceFile:31)
	at com.milaboratory.core.sequence.NucleotideSequence.<init>(SourceFile:135)
	at io.repseq.cli.FromFastaActionAbstract.go(SourceFile:87)
	at io.repseq.cli.jcomander.JCommanderBasedMain.main(SourceFile:157)
	at io.repseq.cli.Main.main(SourceFile:94)
	at com.milaboratory.mixcr.cli.CommandBuildLibrary.fromFasta(SourceFile:362)
	at com.milaboratory.mixcr.cli.CommandBuildLibrary.mkLibraryForGeneType(SourceFile:312)
	at com.milaboratory.mixcr.cli.CommandBuildLibrary.run1(SourceFile:381)
	at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-27(SourceFile:514)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	... 1 more

```
Thank you in advance!

**Comment by mizraelson** [comment]
Hi, could it be that you have some extra space in your command that is not shown here. I have copy pasted your command and it works fine (I only changed the fasta files' names to the one I have).

**Comment by silvia1234567890** [comment]
Hi, the problem was in the fasta files because I found some blank spaces there. Sorry for the inconvenience!

**Comment by silvia1234567890** [comment]
Hi, one question related to this. 
When I run the code above (build a library for TCR alfa), the fact that it does not find any alignment with any of the V segments in the fasta file is not normal, isn't it? 
I tried `--v-gene-feature VRegion`  and `--v-gene-feature VExon2` and I get the same for every V segment:
For example:
```
Processing: aOncmyk_Chr8_CM023226.2_TRAV17-3_TRAV_130-35_F_61467747_61468085 (F) TRA
No alignments found.
```
I send you the command line in pdf and the library I got by executing this command... 
[Oncorhynchus_mykiss-TRA.json.gz](https://github.com/milaboratory/mixcr/files/14403977/Oncorhynchus_mykiss-TRA.json.gz)
[library_terminal.pdf](https://github.com/milaboratory/mixcr/files/14404121/library_terminal.pdf)

And when I run `debugLibrary` with the library (using `--v-gene-feature VRegion`):
`mixcr debugLibrary Oncorhynchus_mykiss-TRA.json.gz`
for each V segment, I get this at the beginning:
```
aOncmyk_Chr8_CM023226.2_TRAV17-3_TRAV_130-35_F_61467747_61468085 (F) TRA : 8022

WARNINGS: 
Unable to find CDR3 start
VRegion contains a stop codon
```
And with the library (using `--v-gene-feature VExon2`), I get this for each V segment:
```
aOncmyk_Chr8_CM023226.2_TRAV17-3_TRAV_130-35_F_61467747_61468085 (F) TRA : 8022

WARNINGS: 
Unable to find CDR3 start

```

Maybe I'm using the wrong commands... Could you help me please?
Thank you in advance!

**Comment by mizraelson** [comment]
can you share the FASTA files for V genes?

**Comment by silvia1234567890** [comment]
> can you share the FASTA files for V genes?

[docs.zip](https://github.com/milaboratory/mixcr/files/14447510/docs.zip)

Hi, 
I modified the headers of the fasta files just in case, and I reran the code again and nothing, same problem again... And also for the TRB... I send you the V and J segments for TRA, a copy of the terminal when running the code and the library that I get as output... Please, help me!

Thank you in advance!

**Comment by mizraelson** [comment]
Hi, so the main issue here is that sequences seem to have some extra nucleotides before the first FR1 position. Thats why FR1 is identified erroneously. You can either fix it in the FASTA, or use `{CDR1Begin:VEnd} ` feature instead.
[Oncorhynchus_mykiss-TRA.json](https://github.com/milaboratory/mixcr/files/14453233/Oncorhynchus_mykiss-TRA.json)
