### ISSUE TITLE
Floating Alignment Boundaries 

### ISSUE THREAD

**Issue by bshim181** [milaboratory/mixcr#1603]
I am running MiXCR with 
tag_pattern='^(UMI:N{12})(R1:*)\(R2:*)'

java -Xmx16g -jar $mixcr analyze generic-amplicon-with-umi \
        --species hsa \
        --assemble-clonotypes-by CDR3 \
        --export-productive-clones-only \
        --rna \
        -f \
        --tag-pattern $tag_pattern \
        --floating-left-alignment-boundary \
        --floating-right-alignment-boundary C \

I have also tried out rigid-left-alignment-boundary but receiving the same error. Is there a solution to this?

Current Read Architecture looks somewhat similar to this. 
<img width="543" alt="Screenshot 2024-03-27 at 11 06 07 AM" src="https://github.com/milaboratory/mixcr/assets/53489568/6ead2638-3596-46f6-ae6a-ec1192201504">

4.4.2; built=Sun Jul 30 08:17:59 UTC 2023; rev=cd7ea52e83; lib=repseqio.v3.0.1
picocli.CommandLine$ExecutionException: Error while running command align java.lang.IllegalArgumentException: Can't build search plan for the pattern. Leftmost part of the pattern has no anchor to the right.
	at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-12(SourceFile:323)
	at picocli.CommandLine.execute(CommandLine.java:2088)
	at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$PlanBuilder.executeSteps(SourceFile:470)
	at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:371)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-26(SourceFile:426)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.milaboratory.mixcr.cli.Main.main(SourceFile:98)

**Comment by mizraelson** [comment]
Hi, the tag pattern should be as follows: `^(UMI:N{12})(R1:*)\^(R2:*)`
