### ISSUE TITLE
Nanopore Data 

### ISSUE THREAD

**Issue by bshim181** [milaboratory/mixcr#1604]
This problem has been posted few days ago, but I am also facing the same issue when running 
Generic-ont preset on the Nanopore data. I was wondering if there is a reason to this error and how can it be fixed?

```
`The following tags and their roles will be associated with each output alignment:
  Payload tags: R1
  Molecule tags: UMI(SQ)
Alignment: 0%
Alignment: 10%  ETA: 00:08:50
Alignment: 20.1%  ETA: 00:06:16
Alignment: 30.2%  ETA: 00:05:37
Alignment: 40.3%  ETA: 00:04:28
java.lang.AssertionError
	at com.milaboratory.o.bN.a(SourceFile:95)
	at com.milaboratory.o.aY.c(SourceFile:3067)
	at com.milaboratory.o.aY.e(SourceFile:99)
	at com.milaboratory.o.aT.c(SourceFile:41)
	at com.milaboratory.mixcr.cli.CommandAlignPipeline$ProcessingBundle.<init>(SourceFile:464)
	at com.milaboratory.mixcr.cli.CommandAlign$Cmd$createReader$4.invoke(SourceFile:995)
	at com.milaboratory.mixcr.cli.CommandAlign$Cmd$createReader$4.invoke(SourceFile:995)
	at com.milaboratory.o.Ck.process(SourceFile:31)
	at cc.redberry.pipe.util.SimpleProcessorWrapper.take(SimpleProcessorWrapper.java:43)
	at com.milaboratory.o.Cn.take(SourceFile)
	at cc.redberry.pipe.util.Chunk.readChunk(Chunk.java:78)
	at cc.redberry.pipe.CUtils$2.take(CUtils.java:169)
	at cc.redberry.pipe.CUtils$2.take(CUtils.java:161)
	at cc.redberry.pipe.blocks.O2ITransmitter.run(O2ITransmitter.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1623)`
```

**Comment by 2003100127** [comment]
The same problem I am having as well.

**Comment by mszelest** [comment]
Hi, do you know any other tool to analyze IGHV from nanopore data?

**Comment by mizraelson** [comment]
Hi, this is a known bug related to extremely long reads. We will fix it in the upcoming MiXCR version. I will follow up on this here.

**Comment by mizraelson** [comment]
Hi, we have added a fix in [the latest develop version](https://link.milaboratory.com/software/mixcr/mixcr-develop.zip). Please try and let me know if it works. I will close this issue for now. Feel free to reopen if needed.
