### ISSUE TITLE
Unexpected behavior when running mixcr analyze from a script

### ISSUE THREAD

**Issue by kvegesan-stjude** [milaboratory/mixcr#1606]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

When I run mixcr analyze on a single sample(paired end fastq), it runs successfully with no issues. When I run multiple samples from a shell script it throws an error. However, if I run the commands separately, one after another, they run with no issues.

Mixcr:
MiXCR v4.6.0 (built Sat Dec 09 13:48:42 CST 2023; rev=c9fafa41fe; branch=no_branch; host=fv-az520-378)
RepSeq.IO v2.4.0 (rev=5b5b4475b8)
MiLib v3.4.0 (rev=d42f072b23)
Built-in V/D/J/C library: repseqio.v4.0

Java:
openjdk version "17.0.3-internal" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 17.0.3-internal+0-adhoc..src, mixed mode, sharing)

## Actual Result

*A description of what actually happened*

## Exact MiXCR commands 

`mixcr analyze -f biomed2-human-rna-igh data/ERR10704565_1.fastq.gz data/ERR10704565_2.fastq.gz output/ERR10704565/ERR10704565`

## MiXCR report files 

```
Please copy the following information along with the stacktrace:
   Version: 4.6.0; built=Sat Dec 09 13:48:42 CST 2023; rev=c9fafa41fe; lib=repseqio.v4.0
        OS: Linux
      Java: 17.0.3-internal
  Cmd args: analyze -f biomed2-human-rna-igh data/ERR10704565_1.fastq.gz data/ERR10704565_2.fastq.gz output/ERR10704565/ERR10704565
picocli.CommandLine$ExecutionException: Error while running command analyze java.lang.IllegalArgumentException: Failed requirement.
	at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-12(SourceFile:395)
	at picocli.CommandLine.execute(CommandLine.java:2088)
	at com.milaboratory.mixcr.cli.Main.main(SourceFile:101)
Caused by: java.lang.IllegalArgumentException: Failed requirement.
	at com.milaboratory.mixcr.cli.CommandAlign.listSamplesForSeedFileName(SourceFile:1445)
	at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$PlanBuilder.setActualAlignOutputs(SourceFile:446)
	at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:372)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-27(SourceFile:514)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	... 1 more
```

**Comment by mizraelson** [comment]
Hi, can you please share the script that you are running when it fails?

**Comment by kvegesan-stjude** [comment]
This is embarrassing, but probably a good reminder for windows users. The file with the commands was created in windows before being run on the HPC. Windows automatically added a carriage return, so all the alignment files had '\r' appended to the output files of the alignment.  This threw errors in the assembly process because it was trying to read files that didn't exist. You can close this issue.
