### ISSUE TITLE
Index file creation problem

### ISSUE THREAD

**Issue by Alex-Davydov** [milaboratory/mixcr#165]
Index file is not created if mapping is turned off during clones assemble (maxBadPointsPercent=0).
```
Exception in thread "main" java.lang.NullPointerException at com.milaboratory.mixcr.assembler.CloneAssembler.getAssembledReadsPort(CloneAssembler.java:304)
	at com.milaboratory.mixcr.cli.ActionAssemble.go(ActionAssemble.java:148)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:147)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:108)
```

**Comment by Alex-Davydov** [comment]
new error
```
Exception in thread "main" java.lang.IllegalArgumentException
	at com.milaboratory.mixcr.assembler.AlignmentsToClonesMappingContainer.writeMapping(AlignmentsToClonesMappingContainer.java:267)
	at com.milaboratory.mixcr.assembler.AlignmentsToClonesMappingContainer.writeMapping(AlignmentsToClonesMappingContainer.java:147)
	at com.milaboratory.mixcr.assembler.AlignmentsToClonesMappingContainer.writeMapping(AlignmentsToClonesMappingContainer.java:140)
	at com.milaboratory.mixcr.cli.ActionAssemble.go(ActionAssemble.java:149)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:147)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:113)
```

**Comment by dbolotin** [comment]
Now it is really fixed.
