### ISSUE TITLE
The problem of mixcr exportPlots shmTrees

### ISSUE THREAD

**Issue by WZQ6** [milaboratory/mixcr#1686]
When I run commandline with  "mixcr exportPlots shmTrees --metadata /home/EXP0033VH/metadata.tsv --node-color sample --line-color sample --node-label sample --alignment-aa CDR3  /home/EXP0033VH/findalle/findshmt/output.shmt /home/EXP0033VH/findalle/findshmt/tree_plot.pdf"
I can't get the output results , with the wrong message:
 Version: 4.6.0-209-develop; built=Thu May 30 18:50:11 CST 2024; rev=015a589864; lib=repseqio.v5.0
        OS: Linux
      Java: 21.0.3
  Abs path: /home/EXP0033VH/findalle/findshmt
  Cmd args: exportPlots shmTrees --metadata /home/EXP0033VH/metadata.tsv --node-color sample --line-color sample --node-label sample --alignment-aa CDR3 /home/EXP0033VH/findalle/findshmt/output.shmt /home/EXP0033VH/findalle/findshmt/tree_plot.pdf
picocli.CommandLine$ExecutionException: Error while running command shmTrees java.lang.NullPointerException
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-17(SourceFile:419)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.Main.execute(SourceFile:105)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:101)
Caused by: java.lang.NullPointerException
        at com.milaboratory.o.wr.a(SourceFile:191)
        at com.milaboratory.o.wr.a(SourceFile:200)
        at com.milaboratory.o.wr.a(SourceFile:200)
        at com.milaboratory.o.wr.a(SourceFile:200)
        at com.milaboratory.o.wD.invoke(SourceFile:4165)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
        at com.milaboratory.o.wy.a(SourceFile:159)
        at com.milaboratory.o.wy.invoke(SourceFile:145)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.milaboratory.mixcr.cli.CommandExportShmTreesPlots.run1(SourceFile:1145)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-32(SourceFile:538)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 2 more
Please help me.
Thanks a lot.

**Comment by mizraelson** [comment]
Hi,
Is it possible that the metadata and the sample files' names in the output.shmt do not match? Can you share the metadata file and the output.shmt file? You can reach us out at support@milaboratories.com

**Comment by mizraelson** [comment]
Hi,
I wanted to follow up on that. Is the issue still present?

**Comment by mizraelson** [comment]
I will close this for now. Feel free to reopen if the issue persists.
