### ISSUE TITLE
ERROR: picocli.CommandLine$ExecutionException: Error while running command align java.lang.IllegalStateException: Check failed.

### ISSUE THREAD

**Issue by liu9756** [milaboratory/mixcr#1713]
Hi ! I am trying to run the align command:
```
mixcr align --preset takara-mouse-rna-bcr-umi-smarseq --report results/S5.align.report.txt --save-output-file-names results/S5.align.list Y10701_WuJ_1-BCR_V1G_1_S5_L001_I1_{{n}}.fastq.gz 
Y10701_WuJ_1-BCR_V1G_1_S5_L{{n}}_I2_001.fastq.gz 
Y10701_WuJ_1-BCR_V1G_1_S5_L001_I1_001.fastq.gz 
Y10701_WuJ_1-BCR_V1G_1_S5_L{{n}}_R2_001.fastq.gz 
results/S5_alignments.vdjca
```

However, it gives me error like this: 
  Abs path: /users/PAS2177/liu9756/BCR_S5_MIXCR/S5
  Cmd args: align --preset takara-mouse-rna-bcr-umi-smarseq --report results/S5.align.report.txt --save-output-file-names results/S5.align.list Y10701_WuJ_1-BCR_V1G_1_S5_L001_I1
_{{n}}.fastq.gz Y10701_WuJ_1-BCR_V1G_1_S5_L{{n}}_I2_001.fastq.gz Y10701_WuJ_1-BCR_V1G_1_S5_L001_I1_001.fastq.gz Y10701_WuJ_1-BCR_V1G_1_S5_L{{n}}_R2_001.fastq.gz results/S5_align
ments.vdjca
picocli.CommandLine$ExecutionException: Error while running command align java.lang.IllegalStateException: Check failed.
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-17(SourceFile:419)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.Main.execute(SourceFile:105)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:101)
Caused by: java.lang.IllegalStateException: Check failed.
        at com.milaboratory.util.FSKt$correlate$1$1.invoke(FS.kt:196)
        at com.milaboratory.util.FSKt$correlate$1$1.invoke(FS.kt:196)
        at kotlin.sequences.SequencesKt___SequencesKt$onEach$1.invoke(_Sequences.kt:2149)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.SequencesKt__SequencesKt$flatMapIndexed$1.invokeSuspend(Sequences.kt:330)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at com.milaboratory.util.FSKt.correlate(FS.kt:317)
        at com.milaboratory.util.FSKt.parseAndRunAndCorrelateFSPattern(FS.kt:238)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd$inputFileGroups$2.invoke(SourceFile:802)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd$inputFileGroups$2.invoke(SourceFile:798)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd.getInputFileGroups(SourceFile:798)
        at com.milaboratory.mixcr.cli.CommandAlign$Cmd.validate(SourceFile:1032)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:35)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-32(SourceFile:538)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 2 more
[liu9756@owens-login04 S5]$ 
Because I have two individual files for I1 and I2, I just wonder if it is because it has to be one single file of index.

**Comment by mizraelson** [comment]
Why do you need I1 and I2? The preset only requires R1 and R2 files. Also, is there a reason you run align instead of analyze?

The command bellow should work:

```
mixcr analyze takara-mouse-rna-bcr-umi-smarseq \
      Y10701_WuJ_1-BCR_V1G_1_S5_L{{n}}_R1_001.fastq.gz  \
      Y10701_WuJ_1-BCR_V1G_1_S5_L{{n}}_R2_001.fastq.gz  \
      result/S5
```

**Comment by liu9756** [comment]
Because the clones were not detected after analysis. I suspect that I did not include the index.

**Comment by mizraelson** [comment]
Did you use TakaraBio SMART-Seq Mouse BCR (with UMIs) kit for cDNA library preparation?

**Comment by liu9756** [comment]
Not yet I will try

**Comment by liu9756** [comment]
Actually not, should I do that?

**Comment by mizraelson** [comment]
I mean the data that you are analyzing, what kit did you use to prepare the cDNA library before sequencing?

**Comment by mizraelson** [comment]
Is it just bulk RNA-seq data without any TCR/BCR enrichment?
