### ISSUE TITLE
no report file in mixcr align with error like exception in thread "main" java.lang.IllegalStateException: TotalReads count not set.

### ISSUE THREAD

**Issue by haoye2015** [milaboratory/mixcr#183]
I used the command "mixcr-2.0.2/mixcr align --report sample_align.log --species mmu --threads 18 sample.R1.fastq sample.R2.fastq sample.vdjca ". 

sample.vdjca was successfully generated. However, "sample_align.log" is failed with an error like "exception in thread "main" java.lang.IllegalStateException: TotalReads count not set."

Would you please help to figure out what's wrong with it.

Thanks.

**Comment by dbolotin** [comment]
Please post full stack-trace here.

**Comment by dbolotin** [comment]
And also commands to reproduce the problem.

**Comment by haoye2015** [comment]
@dbolotin I just found that the vdjca file may be not completely generated.  The details of commands and errors were listed as following. 
 
[haoecust@OncServer test_data]$ /program/mixcr-2.0.2/mixcr align --report test_align.log --species mmu --threads 8 test_TRB_CDR3.R1.fastq test_TRB
_CDR3.R2.fastq ./test_TRB/test_TRB_CDR3.vdjca

Reference library: repseqio.v1.1:10090 (9a1b61eb20896bbb44a5d38d9359107b)
WARNING: Functional gene IGKV8-23-1*00 doesn't contain full VRegionWithP (excluded)
WARNING: ... 7 more functional genes excluded due to absent "featureToAlign".
Alignment: 0%
Alignment: 10%  ETA: 00:06:08
Alignment: 20.2%  ETA: 00:05:15
Alignment: 30.2%  ETA: 00:04:36
Alignment: 40.3%  ETA: 00:03:56
Alignment: 50.6%  ETA: 00:03:17
Alignment: 60.7%  ETA: 00:02:43
Alignment: 70.8%  ETA: 00:01:59
Alignment: 81%  ETA: 00:01:18
Alignment: 91.1%  ETA: 00:00:36
Exception in thread "main" com.milaboratory.core.io.sequence.IllegalFileFormatException
        at com.milaboratory.core.io.sequence.fastq.FastqRecordsReader.nextRecord(FastqRecordsReader.java:160)
        at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.take(SingleFastqReader.java:299)
        at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.take(SingleFastqReader.java:35)
        at com.milaboratory.core.io.sequence.AbstractMultiReader.takeReads(AbstractMultiReader.java:52)
        at com.milaboratory.core.io.sequence.PairedReader.take(PairedReader.java:28)
        at com.milaboratory.core.io.sequence.PairedReader.take(PairedReader.java:21)
        at cc.redberry.pipe.util.Chunk.readChunk(Chunk.java:55)
        at cc.redberry.pipe.CUtils$7.take(CUtils.java:323)
        at cc.redberry.pipe.CUtils$7.take(CUtils.java:315)
        at cc.redberry.pipe.blocks.O2ITransmitter.run(O2ITransmitter.java:66)
        at java.lang.Thread.run(Thread.java:745)

**Comment by haoye2015** [comment]
@dbolotin I just found that the vdjca file may be not completely generated. The details of commands and errors were listed as following.

[haoecust@OncServer test_data]$ /program/mixcr-2.0.2/mixcr align --report test_align.log --species mmu --threads 8 test_TRB_CDR3.R1.fastq test_TRB_CDR3.R2.fastq ./test_TRB/test_TRB_CDR3.vdjca

Reference library: repseqio.v1.1:10090 (9a1b61eb20896bbb44a5d38d9359107b)
WARNING: Functional gene IGKV8-23-1*00 doesn't contain full VRegionWithP (excluded)
WARNING: ... 7 more functional genes excluded due to absent "featureToAlign".
Alignment: 0%
Alignment: 10%  ETA: 00:06:08
Alignment: 20.2%  ETA: 00:05:15
Alignment: 30.2%  ETA: 00:04:36
Alignment: 40.3%  ETA: 00:03:56
Alignment: 50.6%  ETA: 00:03:17
Alignment: 60.7%  ETA: 00:02:43
Alignment: 70.8%  ETA: 00:01:59
Alignment: 81%  ETA: 00:01:18
Alignment: 91.1%  ETA: 00:00:36
Exception in thread "main" com.milaboratory.core.io.sequence.IllegalFileFormatException
        at com.milaboratory.core.io.sequence.fastq.FastqRecordsReader.nextRecord(FastqRecordsReader.java:160)
        at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.take(SingleFastqReader.java:299)
        at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.take(SingleFastqReader.java:35)
        at com.milaboratory.core.io.sequence.AbstractMultiReader.takeReads(AbstractMultiReader.java:52)
        at com.milaboratory.core.io.sequence.PairedReader.take(PairedReader.java:28)
        at com.milaboratory.core.io.sequence.PairedReader.take(PairedReader.java:21)
        at cc.redberry.pipe.util.Chunk.readChunk(Chunk.java:55)
        at cc.redberry.pipe.CUtils$7.take(CUtils.java:323)
        at cc.redberry.pipe.CUtils$7.take(CUtils.java:315)
        at cc.redberry.pipe.blocks.O2ITransmitter.run(O2ITransmitter.java:66)
        at java.lang.Thread.run(Thread.java:745)

**Comment by haoye2015** [comment]
@dbolotin  Very strange. I test another testing sample from the same sequencing platform. It seems the results were well generated.

[haoecust@OncServer test_data]$ /program/mixcr-2.0.2/mixcr align --report test2_align.log --species mmu --threads 8 test2.R1.fastq test2.R2.fastq ./test_TRB/test2_CDR3.vdjca

Reference library: repseqio.v1.1:10090 (9a1b61eb20896bbb44a5d38d9359107b)
WARNING: Functional gene IGKV8-23-1*00 doesn't contain full VRegionWithP (excluded)
WARNING: ... 7 more functional genes excluded due to absent "featureToAlign".
Alignment: 0%
Alignment: 10.2%  ETA: 00:05:44
Alignment: 20.2%  ETA: 00:04:54
Alignment: 30.5%  ETA: 00:04:18
Alignment: 40.5%  ETA: 00:03:38
Alignment: 50.8%  ETA: 00:03:02
Alignment: 60.9%  ETA: 00:02:30
Alignment: 71%  ETA: 00:01:49
Alignment: 81.2%  ETA: 00:01:11
Alignment: 91.2%  ETA: 00:00:33
============= Report ==============
Analysis time: 6.30m
Total sequencing reads: 2620365
Successfully aligned reads: 2438296 (93.05%)
Alignment failed, no hits (not TCR/IG?): 18295 (0.7%)
Alignment failed because of absence of J hits: 160176 (6.11%)
Alignment failed because of low total score: 3598 (0.14%)
Overlapped: 2349012 (89.64%)
Overlapped and aligned: 2198372 (83.9%)
Overlapped and not aligned: 150640 (5.75%)
[TRA] chains: 6801 (0.28%)
[TRB] chains: 2431484 (99.72%)
[TRD] chains: 3 (0%)
[IGL] chains: 8 (0%)

**Comment by haoye2015** [comment]
@dbolotin Thank you. I think I have figure it out.  The test data is partially missing during the downloading process. I re-downloaded the test data, currently, all of them are smoothly runing. 

Have a nice holiday!
