### ISSUE TITLE
IndexOutOfBoundsException during java running

### ISSUE THREAD

**Issue by omegahh** [milaboratory/mixcr#1833]
I run `findAlleles` in a '.clna' alignment file. The IndexOutOfBoundsException is caught. Can you help checking the reason?

```
Step 1 of 7: count diversity for dataset: 0%
Step 1 of 7: count diversity for dataset: 26.5%  ETA: 00:00:02
Step 2 of 7: grouping by the same J gene: 0%
Step 2 of 7: grouping by the same J gene: 22.1%  ETA: 00:00:03
Step 2 of 7: Searching for J alleles: 0%
Step 2 of 7: Searching for J alleles: 73.3%  ETA: 00:00:00
Step 2 of 7: Searching for J alleles: 93.3%  ETA: 00:00:00
Step 3 of 7: grouping by the same V gene: 0%
Step 3 of 7: grouping by the same V gene: 69.5%  ETA: 00:00:00
Step 3 of 7: Searching for V alleles: 0%
Step 3 of 7: Searching for V alleles: 42.4%  ETA: 00:00:01
Step 3 of 7: Searching for V alleles: 92.4%  ETA: 00:00:00
Step 4 of 7: grouping by the same J gene: 0%
Step 4 of 7: grouping by the same J gene: 55.1%  ETA: 00:00:00
Step 4 of 7: Searching for J alleles: 20%
Step 4 of 7: Searching for J alleles: 66.7%  ETA: 00:00:00
Step 4 of 7: Searching for J alleles: 93.3%  ETA: 00:00:00
Step 5 of 7: grouping by the same V gene: 0%
Step 5 of 7: grouping by the same V gene: 77.5%  ETA: 00:00:00
Step 5 of 7: Searching for V alleles: 0%
Step 5 of 7: Searching for V alleles: 54.5%  ETA: 00:00:00
Step 5 of 7: Searching for V alleles: 87.9%  ETA: 00:00:00
Step 5 of 7: Searching for V alleles: 98.5%  ETA: 00:00:01
Step 6 of 7: removing unnecessary genes: 0%
Step 6 of 7: removing unnecessary genes: 79.3%  ETA: 00:00:00
Step 7 of 7: realigning /home/hongh/Data/IMMUNITY/PE300/240614_MJBIO_HBCR_SU7/trim_mixcr/S4F04-UQ10-UT09.clna: 0%
Please copy the following information along with the stacktrace:
   Version: 4.7.0; built=Thu Aug 08 03:19:48 CST 2024; rev=976ba14139; lib=repseqio.v5.1
        OS: Linux
      Java: 11.0.22
  Abs path: /home/hongh/Data/IMMUNITY/PE300/240614_MJBIO_HBCR_SU7/logs
  Cmd args: findAlleles -f -t 12 --export-library /home/hongh/Data/IMMUNITY/PE300/240614_MJBIO_HBCR_SU7/trim_mixcr/S4F04-UQ10-UT09.json --export-alleles-mutations /home/hongh/Data/IMMUNITY/PE300/240614_MJBIO_HBCR_SU7/trim_mixcr/S4F04-UQ10-UT09.alleles.tsv --json-report /home/hongh/Data/IMMUNITY/PE300/240614_MJBIO_HBCR_SU7/logs/Library.12_S4F04-UQ10-UT09.mixcr_findAlleles.json --output-template /home/hongh/Data/IMMUNITY/PE300/240614_MJBIO_HBCR_SU7/trim_mixcr/S4F04-UQ10-UT09.clns /home/hongh/Data/IMMUNITY/PE300/240614_MJBIO_HBCR_SU7/trim_mixcr/S4F04-UQ10-UT09.clna
picocli.CommandLine$ExecutionException: Error while running command findAlleles java.lang.IndexOutOfBoundsException: Range = (186->232); size = 99
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-17(SourceFile:420)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.Main.execute(SourceFile:105)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:101)
Caused by: java.lang.IndexOutOfBoundsException: Range = (186->232); size = 99
        at com.milaboratory.core.sequence.NucleotideSequence.getRange(SourceFile:166)
        at com.milaboratory.core.sequence.NucleotideSequence.getRange(SourceFile:31)
        at com.milaboratory.o.N.a(SourceFile:77)
        at com.milaboratory.o.gW.a(SourceFile:121)
        at com.milaboratory.o.gW.a(SourceFile:39)
        at com.milaboratory.o.gW.a(SourceFile:29)
        at com.milaboratory.o.cj.a(SourceFile:4181)
        at com.milaboratory.o.hX.process(SourceFile:51)
        at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:308)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mizraelson** [comment]
Is it possible to share the file?

**Comment by omegahh** [comment]
Sure, here it is: https://www.dropbox.com/scl/fi/66l62djqd2797ek0syqif/S4F04-UQ10-UT09.clns?rlkey=wpn7hib7a1zwojjnt4bt1p9sf&st=c4wvi0hm&dl=0

**Comment by omegahh** [comment]
@mizraelson Can you download the file I uploaded in dropbox

**Comment by mizraelson** [comment]
Yes, I have downloaded the file. Will get back to you as soon as we debug this.

**Comment by omegahh** [comment]
@mizraelson I hope this message finds you well. I apologize for any inconvenience, and I really appreciate the great work you've done with MiXCR. It has been an invaluable tool for my research.

I am eagerly anticipating the resolution of the current issue, as well as the one referenced as #1853. Your guidance on whether these are fixable would be greatly appreciated, as it will inform my decision on whether to await an updated version or to adjust my analysis approach.

Thank you once again for your time and assistance.

**Comment by mizraelson** [comment]
Hi, I am very sorry for the delay. We have been very busy with the release of our new GUI software [Platforma](https://platforma.bio/).
I have looked into the data and unfortunately clns file is not enough to fully debug the issue. Would it be possible to share the raw FASTQ files for this sample as well as the exact commands used for the analysis.

**Comment by omegahh** [comment]
Yeah, I totally understand. Platforma is also a great work! You are doing the amazing things. The raw FASTQ files is too large to upload in here or my dropbox. I send it together with commands by a email via my google email to support@milaboratories.com, and share the raw FASTQ files with that email. The email title is "About Github Issue #1833", and hope you or your college can find it.

**Comment by mizraelson** [comment]
Yes, I received the files. I will get back to you after investigating.

**Comment by PoslavskySV** [comment]
@omegahh Please, use the following build with the fix:

https://cdn.milaboratory.com/software/mixcr/mixcr-4.7.0-143-develop-0200628b02bcd5c86a407f95f4fbaa05c96c208c.zip

**Comment by omegahh** [comment]
Thank you! It solved my problem.
