### ISSUE TITLE
Error while running command align java.lang.RuntimeException: Different number of reads in single-readers.

### ISSUE THREAD

**Issue by pursellta** [milaboratory/mixcr#1834]
I am trying to run the non-enriched 10x analysis pipeline on SRA fastqs. I have suceessfully run this pipeline with this custom reference on other files, but I get the following error I have never seen before.
Information and the stacktrace:
   Version: 4.7.0; built=Wed Aug 07 12:19:48 PDT 2024; rev=976ba14139; lib=repseqio.v5.1
        OS: Linux
      Java: 11.0.13
  Abs path: /home/tpursell   
  Cmd args: align --report /home/tpursell/bats/Arjam_Flu_10x/mixcr.Tony.ML.bcr.20241024/align.report.txt --json-report /home/tpursell/bats/Arjam_Flu_10x/mixcr.Tony.ML.bcr.20241024/align.report.json --threads 20 --preset 10x-sc-5gex --save-output-file-names /home/tpursell/bats/Arjam_Flu_10x/mixcr.Tony.ML.bcr.20241024/align.list.tsv --split-by-sample --species ajam --library Arjam-IG-V1.json.gz --assemble-contigs-by VDJRegion /home/tpursell/bats/Arjam_Flu_10x/TonyFilesSampleSheet.tsv /home/tpursell/bats/Arjam_Flu_10x/mixcr.Tony.ML.bcr.20241024/alignments.vdjca

Error:
picocli.CommandLine$ExecutionException: Error while running command align java.lang.RuntimeException: Different number of reads in single-readers.
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-17(SourceFile:420)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.Main.execute(SourceFile:105)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$PlanBuilder.executeSteps(SourceFile:543)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:444)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-32(SourceFile:539)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.milaboratory.mixcr.cli.Main.execute(SourceFile:105)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:101)
Caused by: java.lang.RuntimeException: Different number of reads in single-readers.
        at com.milaboratory.o.aS.a(SourceFile:62)
        at com.milaboratory.o.ba.take(SourceFile:1028)
        at com.milaboratory.o.c.a(SourceFile:89)
        at com.milaboratory.o.c.take(SourceFile:69)
        at cc.redberry.pipe.util.SimpleProcessorWrapper.take(SimpleProcessorWrapper.java:40)
        at com.milaboratory.o.FG.take(SourceFile)
        at cc.redberry.pipe.util.Chunk.readChunk(Chunk.java:78)
        at cc.redberry.pipe.CUtils$2.take(CUtils.java:169)
        at cc.redberry.pipe.CUtils$2.take(CUtils.java:161)
        at cc.redberry.pipe.blocks.O2ITransmitter.run(O2ITransmitter.java:63)
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: java.lang.RuntimeException: java.lang.IllegalStateException: Footer not set
                at com.milaboratory.o.e$b.close(SourceFile:54)
                at com.milaboratory.o.g.close(SourceFile:75)
                at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:64)
                at com.milaboratory.mixcr.cli.CommandAlign$Cmd.run1(SourceFile:1635)
                at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
                at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
                at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
                at picocli.CommandLine.access$1300(CommandLine.java:145)
                at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
                at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
                at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
                at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-32(SourceFile:539)
                at picocli.CommandLine.execute(CommandLine.java:2078)
                at com.milaboratory.mixcr.cli.Main.execute(SourceFile:105)
                at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$PlanBuilder.executeSteps(SourceFile:543)
                at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:444)
                at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
                at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
                at picocli.CommandLine.access$1300(CommandLine.java:145)
                at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
                at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
                at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
                at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-32(SourceFile:539)
                at picocli.CommandLine.execute(CommandLine.java:2078)
                at com.milaboratory.mixcr.cli.Main.execute(SourceFile:105)
                at com.milaboratory.mixcr.cli.Main.main(SourceFile:101)
        Caused by: java.lang.IllegalStateException: Footer not set
                at com.milaboratory.o.ka.close(SourceFile:167)
                at com.milaboratory.o.e$b.close(SourceFile:46)
                ... 29 more
                Suppressed: java.lang.IllegalStateException: Footer not set
                        ... 31 more
                Suppressed: java.lang.IllegalStateException: Footer not set
                        ... 31 more

**Comment by mizraelson** [comment]
Hi, I see you closed the issue, did you solve it?

**Comment by pursellta** [comment]
Hey Mark!
Yeah, I assume it is a problem with my fastqs (i.e. they got corrupted or didn’t download fully) based on another thread. I am redownloading them and will try again.
-Taylor

From: mizraelson ***@***.***>
Date: Thursday, October 24, 2024 at 4:33 PM
To: milaboratory/mixcr ***@***.***>
Cc: Taylor Pursell ***@***.***>, State change ***@***.***>
Subject: Re: [milaboratory/mixcr] Error while running command align java.lang.RuntimeException: Different number of reads in single-readers. (Issue #1834)

Hi, I see you closed the issue, did you solve it?

**Comment by mizraelson** [comment]
Understood! Please let me know if re-downloading helps!

Sincerely,
Mark
