### ISSUE TITLE
IndexOutOfBoundsException: Index 2 out of bounds for length 2

### ISSUE THREAD

**Issue by pursellta** [milaboratory/mixcr#1836]
I ma trying to run the non-enriched 10x VDJ pipeline with a custom reference. I have successfully used the custom reference before. I downloaded the fastqs from SRA and am running the pipeline with a sample sheet. Here is the command and associated error:
   Version: 4.7.0; built=Wed Aug 07 12:19:48 PDT 2024; rev=976ba14139; lib=repseqio.v5.1
        OS: Linux
      Java: 11.0.13
  Abs path: /home/tpursell/bats/Arjam_Flu_10x/SRA_Files/arjam_WT_intestine_9dpi
  Cmd args: analyze 10x-sc-5gex -t 20 --species ajam --library Arjam-IG-V1.json.gz --assemble-contigs-by VDJRegion --split-by-sample /home/tpursell/bats/Arjam_Flu_10x/SRA_Files/arjam_WT_intestine_9dpi/Arjam_intestine_9dpi.tsv /home/tpursell/bats/Arjam_Flu_10x/SRA_Files/arjam_WT_intestine_9dpi/mixcr.bcr.20241025/

picocli.CommandLine$ExecutionException: Error while running command analyze java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-17(SourceFile:420)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.Main.execute(SourceFile:105)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:101)
Caused by: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at com.milaboratory.mixcr.presets.FullSampleSheetParsed$Companion$parse$parsedRows$1$inputIdx$1.invoke(SourceFile:320)
        at com.milaboratory.mixcr.presets.FullSampleSheetParsed$Companion$parse$parsedRows$1$inputIdx$1.invoke(SourceFile:320)
        at com.milaboratory.mixcr.presets.FullSampleSheetParsed$Companion.put(SourceFile:262)
        at com.milaboratory.mixcr.presets.FullSampleSheetParsed$Companion.parse(SourceFile:320)
        at com.milaboratory.mixcr.presets.FullSampleSheetParsed$Companion.parse(SourceFile:271)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$inputSampleSheet$2.invoke(SourceFile:289)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$inputSampleSheet$2.invoke(SourceFile:287)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.getInputSampleSheet(SourceFile:287)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.access$getInputSampleSheet(SourceFile:96)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$inputFileGroups$2.invoke(SourceFile:297)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$inputFileGroups$2.invoke(SourceFile:295)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.getInputFileGroups(SourceFile:295)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.validate(SourceFile:313)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:35)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-32(SourceFile:539)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 2 more

**Comment by pursellta** [comment]
It was a problem with the sample sheet.
