### ISSUE TITLE
exportReadsForClones to get fastq reads containing CDR3

### ISSUE THREAD

**Issue by Januaryyiyue** [milaboratory/mixcr#1869]
Hi,

I am running mixcr align, assemble and exportReadsForClones for my CapTCR-seq data using the following commands:

```
# Align
mixcr -Xmx90g align --species hs --preset local:cap-tcr -OsaveOriginalReads=true "${INPUT_DIR}/${BASENAME}_merged_R1.fastq.gz" "${INPUT_DIR}/${BASENAME}_merged_R2.fastq.gz" "$OUTPUT_DIR/${BASENAME}_output_file.vdjca"

# Assemble
mixcr -Xmx90g assemble -OassemblingFeatures=CDR3 --write-alignments "$OUTPUT_DIR/${BASENAME}_output_file.vdjca" "$OUTPUT_DIR/${BASENAME}.clna"

# Export reads for clones
mixcr -Xmx90g exportReadsForClones -fs "$OUTPUT_DIR/${BASENAME}.clna" "$OUTPUT_DIR/${BASENAME}_reads.fastq.gz"
```

My scripts produce a `.vdjca` file but does not continue. I get the following error message:
```
WARNING: unnecessary override -OassemblingFeatures=CDR3 with the same value.
No data to automatically infer minRecordsPerConsensus. Using default value: 0
4.4.1; built=Thu Jul 06 13:36:41 EDT 2023; rev=f7cd556c6c; lib=repseqio.v3.0.1
picocli.CommandLine$ExecutionException: Error while running command assemble java.lang.IllegalArgumentException: Input file has insufficient sorting level
	at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-12(SourceFile:323)
	at picocli.CommandLine.execute(CommandLine.java:2088)
	at com.milaboratory.mixcr.cli.Main.main(SourceFile:98)
Caused by: java.lang.IllegalArgumentException: Input file has insufficient sorting level
	at com.milaboratory.o.iq.<init>(SourceFile:53)
	at com.milaboratory.mixcr.cli.CommandAssemble$Cmd.run1(SourceFile:328)
	at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-26(SourceFile:426)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	... 1 more
4.4.1; built=Thu Jul 06 13:36:41 EDT 2023; rev=f7cd556c6c; lib=repseqio.v3.0.1
ERROR: input file "/path/to/output.clna" does not exist.
```

Please let me know what I can do to fix the issue.

Thank you so much!

**Comment by mizraelson** [comment]
It looks like you have UMIs in your preset. If that is the case you should run `mixcr refineTagsAndSort` before `mixcr assemble`
