### ISSUE TITLE
Exception in -nMutations JRegion -aaMutations JRegion

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#187]
`-nMutations JRegion -aaMutations JRegion`

produces the following exception

```
Exception in thread "main" java.lang.NullPointerException
at com.milaboratory.core.Range.contains(Range.java:169)
at com.milaboratory.mixcr.export.FeatureExtractors$MutationsExtractor.extractValue(FeatureExtractors.java:116)
at com.milaboratory.mixcr.export.FeatureExtractors$MutationsExtractor.extractValue(FeatureExtractors.java:86)
at com.milaboratory.mixcr.export.FieldWithParameters$1.extractValue(FieldWithParameters.java:49)
at com.milaboratory.mixcr.export.InfoWriter.put(InfoWriter.java:82)
at com.milaboratory.mixcr.cli.ActionExportClones$ExportClones.run(ActionExportClones.java:151)
at com.milaboratory.mixcr.cli.ActionExportClones.go0(ActionExportClones.java:76)
at com.milaboratory.mixcr.cli.ActionExport.go(ActionExport.java:52)
at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:147)
at com.milaboratory.mixcr.cli.Main.main(Main.java:113)
```

If this is ok, we need better error message.

**Comment by PoslavskySV** [comment]
fixed in 2.04
