### ISSUE TITLE
Bug in exportClones for mmu reference 

### ISSUE THREAD

**Issue by PoslavskySV** [milaboratory/mixcr#217]
Stack trace:

    java.lang.NullPointerException
    at com.milaboratory.mixcr.cli.ActionExportClones$CFilter.accept(ActionExportClones.java:108)
    at com.milaboratory.mixcr.cli.ActionExportClones$CloneExportParameters$1.accept(ActionExportClones.java:192)
    at com.milaboratory.mixcr.cli.ActionExportClones$CloneExportParameters$1.accept(ActionExportClones.java:187)
    at com.milaboratory.mixcr.basictypes.CloneSet.transform(CloneSet.java:137)
    at com.milaboratory.mixcr.cli.ActionExportClones.go0(ActionExportClones.java:62)
    at com.milaboratory.mixcr.cli.ActionExport.go(ActionExport.java:52)
    at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:147)
    at com.milaboratory.mixcr.cli.Main.main(Main.java:120)

note: `Clone.getFeature(CDR3)` gives not null, while `Clone.getPartitionedTarget(0).getFeature(CDR3)` gives null for some reason.

**Comment by dbolotin** [comment]
This seems to be connected with [this code](https://github.com/milaboratory/mixcr/blob/master/src/main/java/com/milaboratory/mixcr/basictypes/VDJCObject.java#L203), which we've just [deleted day ago](https://github.com/milaboratory/mixcr/commit/91f1682d5ac5323da425faad8857ee8d164a709d#diff-2d0ff1d0d538cb0170cc42c35ce723a6L203). Stas, please confirm.

**Comment by PoslavskySV** [comment]
Test case:

    @Test
    public void name() throws Exception {
        VDJCGene gene = VDJCLibraryRegistry.getDefault().getGene(new VDJCGeneId(new VDJCLibraryId("default", 10090), "IGHV1-55*00"));
        GeneFeature intFeature = GeneFeature.parse("{CDR3Begin:VEnd}");
        Assert.assertNotNull(gene.getPartitioning().getRelativeRange(GeneFeature.parse("VRegion"), intFeature));
    }
