### ISSUE TITLE
Bug in GeneFeature#intersection when using -OvParameters.geneFeatureToAlign=VGeneWithP

### ISSUE THREAD

**Issue by PoslavskySV** [milaboratory/mixcr#219]
mixcr align -OvParameters.geneFeatureToAlign=VGeneWithP input.fastq.gz output.vdjca
    mixcr assemble output.vdjca output.clns

causes

    Exception in thread "main" java.lang.IllegalArgumentException

    at io.repseq.core.GeneFeature.intersection0(GeneFeature.java:444)
    at io.repseq.core.GeneFeature.intersection(GeneFeature.java:384)
    at io.repseq.core.GeneFeature.intersection(GeneFeature.java:353)
    at com.milaboratory.mixcr.cli.ActionAssemble.go(ActionAssemble.java:99)
    at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:147)
    at com.milaboratory.mixcr.cli.Main.main(Main.java:120)

**Comment by dbolotin** [comment]
Add tests for exact case.
