### ISSUE TITLE
Exception during alignment

### ISSUE THREAD

**Issue by PoslavskySV** [milaboratory/mixcr#231]
Exception in thread "main" java.lang.NegativeArraySizeException
	at com.milaboratory.core.alignment.kaligner1.KMapper.align(KMapper.java:506)
	at com.milaboratory.core.alignment.kaligner1.KAligner.align(KAligner.java:249)
	at com.milaboratory.core.alignment.kaligner1.KAligner.align(KAligner.java:217)
	at com.milaboratory.core.alignment.kaligner1.KAligner.align(KAligner.java:189)
	at com.milaboratory.core.alignment.kaligner1.KAligner.align(KAligner.java:44)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerS.align(VDJCAlignerS.java:210)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerS.processStrict(VDJCAlignerS.java:145)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerS.process0(VDJCAlignerS.java:78)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerS.process0(VDJCAlignerS.java:47)
	at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:74)
	at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:44)
	at cc.redberry.pipe.CUtils$9.process(CUtils.java:350)
	at cc.redberry.pipe.CUtils$9.process(CUtils.java:345)
	at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:304)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-3" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3284)
	at com.milaboratory.util.IntArrayList.ensureCapacity(IntArrayList.java:59)
	at com.milaboratory.util.IntArrayList.add(IntArrayList.java:64)
	at com.milaboratory.core.alignment.kaligner1.KMapper.align(KMapper.java:447)
	at com.milaboratory.core.alignment.kaligner1.KAligner.align(KAligner.java:249)
	at com.milaboratory.core.alignment.kaligner1.KAligner.align(KAligner.java:217)
	at com.milaboratory.core.alignment.kaligner1.KAligner.align(KAligner.java:189)
	at com.milaboratory.core.alignment.kaligner1.KAligner.align(KAligner.java:44)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerS.align(VDJCAlignerS.java:210)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerS.processStrict(VDJCAlignerS.java:145)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerS.process0(VDJCAlignerS.java:78)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerS.process0(VDJCAlignerS.java:47)
	at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:74)
	at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:44)
	at cc.redberry.pipe.CUtils$9.process(CUtils.java:350)
	at cc.redberry.pipe.CUtils$9.process(CUtils.java:345)
	at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:304)
	at java.lang.Thread.run(Thread.java:745)

**Comment by PoslavskySV** [comment]
The reason is that some reads in the data may be too long (e.g. 2^30). TODO: check read length in aligner and throw correct exception.
