### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by mimisikai** [milaboratory/mixcr#234]
java version "1.8.0_121"
java(TM) SE Runtime Environment (build 1.8.0_121-b13)
java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

F:\MUX4446\2017_01_13_15_38_00_981\RMM592>java -Xmx4g -Xms3g -jar C:\Users\jhou
Downloads\mixcr-2.1.1\mixcr.jar align -s mmu -r alignmentReport_RMM592.txt RMM59
2_MS001-PE-R00400_L001_R1.fastq.gz RMM592_MS001-PE-R00400_L001_R2.fastq.gz align
ments_RMM592.vdjca
Reference library: repseqio.v1.2:10090 (9a1b61eb20896bbb44a5d38d9359107b)
WARNING: Functional gene IGKV8-23-1*00 doesn't contain full VRegionWithP (exclud
ed)
WARNING: ... 7 more functional genes excluded due to absent "featureToAlign".
Alignment: 0.1%
Alignment: 9.4% ETA: 00:19:31
Exception in thread "main" java.lang.NullPointerException
at com.milaboratory.mixcr.vdjaligners.VDJCAlignerPVFirst.process0(VDJCAl
ignerPVFirst.java:97)
at com.milaboratory.mixcr.vdjaligners.VDJCAlignerPVFirst.process0(VDJCAl
ignerPVFirst.java:55)
at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.ja
va:74)
at com.milaboratory.mixcr.vdjaligners.VDJCAlignerWithMerge.process0(VDJC
AlignerWithMerge.java:86)
at com.milaboratory.mixcr.vdjaligners.VDJCAlignerWithMerge.process0(VDJC
AlignerWithMerge.java:42)
at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.ja
va:74)
at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.ja
va:44)
at cc.redberry.pipe.CUtils$9.process(CUtils.java:350)
at cc.redberry.pipe.CUtils$9.process(CUtils.java:345)
at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcesso
r.java:304)
at java.lang.Thread.run(Unknown Source)

**Comment by mimisikai** [comment]
I use another Mac computer to run the same sample and code, with the same error info as below:
mixcr align -s mmu -r alignmentReport_RMM590.txt RMM590_MS001-PE-R00400_L001_R1.fastq.gz RMM590_MS001-PE-R00400_L001_R2.fastq.gz alignments_RMM590.vdjca
Reference library: repseqio.v1.2:10090 (9a1b61eb20896bbb44a5d38d9359107b)
WARNING: Functional gene IGKV8-23-1*00 doesn't contain full VRegionWithP (excluded)
WARNING: ... 7 more functional genes excluded due to absent "featureToAlign".
Alignment: 0.1% Alignment: 4.8%  ETA: 00:40:02
Alignment: 10.4%  ETA: 00:32:00
Alignment: 15.7%  ETA: 00:31:50
Alignment: 21.4%  ETA: 00:27:45
Alignment: 27.2%  ETA: 00:25:05
Alignment: 33.1%  ETA: 00:23:04
Alignment: 38.8%  ETA: 00:21:28
Alignment: 44.7%  ETA: 00:18:47
Alignment: 50.4%  ETA: 00:17:17
Alignment: 56.3%  ETA: 00:15:01
Alignment: 62.1%  ETA: 00:13:06
Alignment: 67.1%  ETA: 00:13:16
Exception in thread "main" java.lang.NullPointerException
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerPVFirst.process0(VDJCAlignerPVFirst.java:97)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerPVFirst.process0(VDJCAlignerPVFirst.java:55)
	at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:74)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerWithMerge.process0(VDJCAlignerWithMerge.java:86)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerWithMerge.process0(VDJCAlignerWithMerge.java:42)
	at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:74)
	at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:44)
	at cc.redberry.pipe.CUtils$9.process(CUtils.java:350)
	at cc.redberry.pipe.CUtils$9.process(CUtils.java:345)
	at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:304)
	at java.lang.Thread.run(Thread.java:745)

MiXCR v2.1.1 (built Thu Mar 02 14:03:41 PST 2017; rev=9cbb23c; branch=release/v2.1.1)
RepSeq.IO v1.2.7 (rev=a06d5b2)
MiLib v1.7.2 (rev=4a8aaf6)
Built-in V/D/J/C library: repseqio.v1.2

Library search path:
- built-in libraries
- /Users/xxxx/Desktop/RMM590/.
- /usr/local/Cellar/mixcr/2.1.1-1/libraries

**Comment by dbolotin** [comment]
Thanks for reporting!
Can you share this dataset? The problem seems to be tricky, and having the data to reproduce it would really speed-up the debugging process. We will of course keep it confidential and remove it after resolution of the bug. If it is possible please write me to `bolotin.dmitriy@gmail.com`.
