### ISSUE TITLE
-r option exception in align and assemble

### ISSUE THREAD

**Issue by DanteBortone** [milaboratory/mixcr#295]
The -r option raises an exception for me in align and assemble:
Exception in thread "main" java.lang.RuntimeException: java.nio.file.NoSuchFileException: alignment_log.txt
	at com.milaboratory.mixcr.cli.Util.appendAtomically(Util.java:74)
	at com.milaboratory.mixcr.cli.Util.appendAtomically(Util.java:65)
	at com.milaboratory.mixcr.cli.Util.writeReport(Util.java:83)
	at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:265)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:155)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:115)
Caused by: java.nio.file.NoSuchFileException: alignment_log.txt
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at com.milaboratory.mixcr.cli.Util.appendAtomically(Util.java:69)
	... 5 more

If I touch the alignment_log.txt file before running align, it works without an raising exception.  After align finishes the touched file contains the report.  Reports also work for assemble if I touch the log file first.

**Comment by dbolotin** [comment]
Thanks for reporting! Confirm it is a bug. I'll release a fix later today.

**Comment by dbolotin** [comment]
Please upgrade MiXCR to 2.1.7, this should fix the problem.
