### ISSUE TITLE
no report file in mixcr align with error like exception in thread "main" java.lang.IllegalStateException: TotalReads count not set.

### ISSUE THREAD

**Issue by anabbi** [milaboratory/mixcr#331]
My issue is similar to:
https://github.com/milaboratory/mixcr/issues/183. I am a heavy user of Mixcr with so many different datasets, but this one time that I am trying to use WGS data it does not create a report files (for the majority of files) and gives me the following error:

MixCR 2.1.2 loaded. You can use 'java -jar $mixcr_dir/mixcr.jar' to run the program.
Exception in thread "main" java.lang.RuntimeException: **Different number of reads in single-readers.**
	at com.milaboratory.core.io.sequence.AbstractMultiReader.takeReads(AbstractMultiReader.java:61)
	at com.milaboratory.core.io.sequence.PairedReader.take(PairedReader.java:28)
	at com.milaboratory.core.io.sequence.PairedReader.take(PairedReader.java:21)
	at cc.redberry.pipe.util.Chunk.readChunk(Chunk.java:63)
	at cc.redberry.pipe.CUtils$7.take(CUtils.java:323)
	at cc.redberry.pipe.CUtils$7.take(CUtils.java:315)
	at cc.redberry.pipe.blocks.O2ITransmitter.run(O2ITransmitter.java:66)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" java.lang.IllegalStateException: **TotalReads count not set.**
	at com.milaboratory.mixcr.cli.CloneAssemblerReport.writeReport(CloneAssemblerReport.java:179)
	at com.milaboratory.mixcr.cli.Util.writeReportToStdout(Util.java:86)
	at com.milaboratory.mixcr.cli.ActionAssemble.go(ActionAssemble.java:129)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:147)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:119)
Exporting clones: 0%
Exporting clones: 6.7%
Exporting clones: 0%
Exporting clones: 0%
Exporting clones: 4.1%
Exporting clones: 9.8%
Exporting clones: 0%

Out of 98 files only 7 files have the log files. Note that I still get the final clones output, but I just do not know whether I can trust it...

Thanks for your help

**Comment by dbolotin** [comment]
Looks like you have different number of records in `R1` and `R2` files.

Try count number of lines in each of the files, like:
```bash
wc -l file.fastq
# or 
zcat file.fastq.gz | wc -l
```

**Comment by dbolotin** [comment]
No reply, closing the issue.
