### ISSUE TITLE
repseqio and MIXCR meta fields

### ISSUE THREAD

**Issue by nathaniel-jd** [milaboratory/mixcr#360]
I have recently been looking to import some local libraries into MIXCR, and have used repseqio to generate the json format for this as per the tutorial here:
https://github.com/repseqio/repseqio

However, when I load these into MIXCR with the following command:
`mixcr align -b my_library -s my_species in.fastq out.vdjca 
`

I get the following error:
```
Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "meta" (class io.repseq.dto.VDJCGeneData), not marked as ignorable (8 known properties: "baseSequence", "anchorPoints", "tags", "name", "isFunctional", "geneType", "chains", "note"])
 at [Source: ~/.mixcr/my_library.json; line: 17, column: 4] (through reference chain: Object[][0]->io.repseq.dto.VDJCLibraryData["genes"]->java.util.ArrayList[0]->io.repseq.dto.VDJCGeneData["meta"])
        at io.repseq.core.VDJCLibraryRegistry$FolderLibraryResolver.resolve(VDJCLibraryRegistry.java:746)
        at io.repseq.core.VDJCLibraryRegistry.tryResolve(VDJCLibraryRegistry.java:410)
        at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:362)
        at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:278)
        at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:120)
        at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:155)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:115)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "meta" (class io.repseq.dto.VDJCGeneData), not marked as ignorable (8 known properties: "baseSequence", "anchorPoints", "tags", "name", "isFunctional", "geneType", "chains", "note"])
 at [Source: ~/.mixcr/my_library.json; line: 17, column: 4] (through reference chain: Object[][0]->io.repseq.dto.VDJCLibraryData["genes"]->java.util.ArrayList[0]->io.repseq.dto.VDJCGeneData["meta"])

```

This error is resolved when manually removing the 'meta' fields from the .json library.

**Comment by nathaniel-jd** [comment]
For reference, I am using repseqio v1.2.11 and MIXCR v2.1.8

**Comment by dbolotin** [comment]
Please try MiXCR 2.1.9

**Comment by nathaniel-jd** [comment]
Yes, the issue is resolved with the newer version. Thanks.
