### ISSUE TITLE
-OmergerParameters.identityType issue

### ISSUE THREAD

**Issue by Alex-Davydov** [milaboratory/mixcr#362]
An error occurs when using mergerParameters.identityType with MinimalQualityWeighted value. Full length IGH data, mixcr 2.1.9

```
mixcr align -p kaligner2 -r alignmnetReports.txt -f -OreadsLayout=Collinear -s hsa -OvParameters.geneFeatureToAlign=VTranscript -OmergerParameters.identityType=MinimalQualityWeighted inputR1.fastq inputR2.fastq output.vdjca
```

```
Reference library: repseqio.v1.5:9606:29a95112c52f62585b28d241db7fd523
Alignment: 1.4%
Alignment: 18.8%  ETA: 00:00:28
Exception in thread "main" java.lang.IllegalArgumentException
  at com.milaboratory.core.merger.MismatchOnlyPairedReadMerger.identity(MismatchOnlyPairedReadMerger.java:210)
  at com.milaboratory.mixcr.partialassembler.TargetMerger.merge(TargetMerger.java:309)
  at com.milaboratory.mixcr.vdjaligners.VDJCAlignerPVFirst.process0(VDJCAlignerPVFirst.java:94)
  at com.milaboratory.mixcr.vdjaligners.VDJCAlignerPVFirst.process0(VDJCAlignerPVFirst.java:55)
  at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:87)
  at com.milaboratory.mixcr.vdjaligners.VDJCAlignerWithMerge.process0(VDJCAlignerWithMerge.java:89)
  at com.milaboratory.mixcr.vdjaligners.VDJCAlignerWithMerge.process0(VDJCAlignerWithMerge.java:42)
  at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:87)
  at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:47)
  at cc.redberry.pipe.CUtils$9.process(CUtils.java:350)
  at cc.redberry.pipe.CUtils$9.process(CUtils.java:345)
  at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:304)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by dbolotin** [comment]
Fixed in https://github.com/milaboratory/milib/commit/9072956f181e5fb9e27097e0757c53cdcee98d7f
