### ISSUE TITLE
Error when using IMGT library for alignment

### ISSUE THREAD

**Issue by brunogrande** [milaboratory/mixcr#381]
I'm attempting to run `mixcr align` with the IMGT library, but I run into the error below. I'm using MiXCR version 2.1.10, and the test files are from `src/test/resources/sequences`. I also included the output of `mixcr -v` and listed the files in `~/.mixcr/libraries`. 

```
$ mixcr align -b imgt test_R1.fastq.gz test_R2.fastq.gz test.vdjca
Exception in thread "main" java.lang.RuntimeException: Can't find library for following library name and species: imgt + hs
	at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:375)
	at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:278)
	at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:120)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:155)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:123)


$ mixcr -v
MiXCR v2.1.10 (built Fri Mar 30 07:59:50 PDT 2018; rev=87f92f5; branch=hotfix/v2.1.10)
RepSeq.IO v1.2.11 (rev=de00211)
MiLib v1.8.3 (rev=1a225d5)
Built-in V/D/J/C library: repseqio.v1.5

Library search path:
- built-in libraries
- /projects/NCI_Burkitts/.
- /home/bgrande/.mixcr/libraries


$ ls /home/bgrande/.mixcr/libraries
imgt.201814-3.sv2.json.gz
```

In case this helps with debugging, if I run the same command using an older version of MiXCR (v2.1.3), I get a different error which suggests that the library JSON file is being loaded, but parsing fails. I presume this is because the latest library file contains fields that didn't exist when MiXCR version 2.1.3 was released. 

Can you think of anything that could explain why the library file can be loaded in version 2.1.3 (even though parsing fails) but not in version 2.1.10?

```
$ mixcr align -b imgt test_R1.fastq.gz test_R2.fastq.gz test.vdjca
Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "meta" (class io.repseq.dto.VDJCGeneData), not marked as ignorable (8 known properties: "baseSequence", "anchorPoints", "tags", "name", "isFunctional", "geneType", "chains", "note"])
 at [Source: java.io.BufferedInputStream@3972a855; line: 22, column: 4] (through reference chain: Object[][0]->io.repseq.dto.VDJCLibraryData["genes"]->java.util.ArrayList[0]->io.repseq.dto.VDJCGeneData["meta"])
	at io.repseq.core.VDJCLibraryRegistry$FolderLibraryResolver.resolve(VDJCLibraryRegistry.java:746)
	at io.repseq.core.VDJCLibraryRegistry.tryResolve(VDJCLibraryRegistry.java:410)
	at io.repseq.core.VDJCLibraryRegistry.tryResolve(VDJCLibraryRegistry.java:421)
	at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:362)
	at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:278)
	at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:110)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:155)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:115)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "meta" (class io.repseq.dto.VDJCGeneData), not marked as ignorable (8 known properties: "baseSequence", "anchorPoints", "tags", "name", "isFunctional", "geneType", "chains", "note"])
 at [Source: java.io.BufferedInputStream@3972a855; line: 22, column: 4] (through reference chain: Object[][0]->io.repseq.dto.VDJCLibraryData["genes"]->java.util.ArrayList[0]->io.repseq.dto.VDJCGeneData["meta"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:851)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1085)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1388)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1342)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:455)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at io.repseq.core.VDJCLibraryRegistry$FolderLibraryResolver.resolve(VDJCLibraryRegistry.java:741)
	... 7 more


$ mixcr -v
MiXCR v2.1.3 (built Wed Jun 07 08:53:54 PDT 2017; rev=bfc0cd3; branch=release/v2.1.3)
RepSeq.IO v1.2.8 (rev=8681210)
MiLib v1.8 (rev=f493f6e)
Built-in V/D/J/C library: repseqio.v1.2

Library search path:
- built-in libraries
- /projects/NCI_Burkitts/.
- /home/bgrande/.mixcr/libraries
```

**Comment by dbolotin** [comment]
Thanks for the very detailed bug report!

The problem is in IMGT library, it lacks `hs` species name (see [here](https://github.com/repseqio/library-imgt/blob/master/rules/rules_human.json#L3)). I will fix it there right away.

P.S. Just in case, the `--species` option will be mandatory in 2.2.* branch, so if you use similar command in scripts I suggest you explicitly specify the species.

**Comment by dbolotin** [comment]
Done. Please try [this one](https://github.com/repseqio/library-imgt/releases/tag/v3).

**Comment by brunogrande** [comment]
Thanks for the quick fix!
