### ISSUE TITLE
Error while using IMGT library

### ISSUE THREAD

**Issue by Bharat-Dekoskylab** [milaboratory/mixcr#424]
HI MixCR developers!

I am trying to use mixcr along with IMGT library and I am getting the following errors:

```
mixcr align BBBNNK1_S13_L001_linked.fq -f --species hs  -b imgt -r alignment_report.txt alignments.vdjca
```

```
Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "meta" (class io.repseq.dto.VDJCGeneData), not marked as ignorable (8 known properties: "baseSequence", "anchorPoints", "tags", "name", "isFunctional", "geneType", "chains", "note"])
 at [Source: java.io.BufferedInputStream@10d307f1; line: 22, column: 4] (through reference chain: Object[][0]->io.repseq.dto.VDJCLibraryData["genes"]->java.util.ArrayList[0]->io.repseq.dto.VDJCGeneData["meta"])
        at io.repseq.core.VDJCLibraryRegistry$FolderLibraryResolver.resolve(VDJCLibraryRegistry.java:746)
        at io.repseq.core.VDJCLibraryRegistry.tryResolve(VDJCLibraryRegistry.java:410)
        at io.repseq.core.VDJCLibraryRegistry.tryResolve(VDJCLibraryRegistry.java:421)
        at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:362)
        at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:278)
        at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:120)
        at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:155)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:115)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "meta" (class io.repseq.dto.VDJCGeneData), not marked as ignorable (8 known properties: "baseSequence", "anchorPoints", "tags", "name", "isFunctional", "geneType", "chains", "note"])
 at [Source: java.io.BufferedInputStream@10d307f1; line: 22, column: 4] (through reference chain: Object[][0]->io.repseq.dto.VDJCLibraryData["genes"]->java.util.ArrayList[0]->io.repseq.dto.VDJCGeneData["meta"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:851)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1085)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1388)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1342)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:455)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
        at io.repseq.core.VDJCLibraryRegistry$FolderLibraryResolver.resolve(VDJCLibraryRegistry.java:741)
        ... 7 more
```

**Here's the result of mixcr -v command:**

```
[b044b665@submit2 mixcr-2.1.12]$ mixcr -v
MiXCR v2.2-SNAPSHOT (built Thu Jan 04 15:24:23 CST 2018; rev=59b4d89; branch=develop)
RepSeq.IO v1.2.11-SNAPSHOT (rev=b0aa6b9)
MiLib v1.8.2-SNAPSHOT (rev=4d7d5da)
Built-in V/D/J/C library: repseqio.v1.4

Library search path:
- built-in libraries
- /panfs/pfs.local/scratch/dekosky/b044b665/VHVL_project/VHVL_Sequence_workflow/Files_Scripts/Andrew_TCR-samples/.
```

I am not sure why I can't see the libraries folder (and .mixcr) when I run mixcr -v command. 

Also, I tried running the align command again after copying the " imgt.201822-5.sv4.json.gz " file inside the libraries folder and outside as well. In both scenarios, I am not able to run the align command using IMGT.

I would highly appreciate if anyone could help me in running the align command with imgt.

P.S. I am running this software on University cluster and I installed mixcr separately on my account.

Thanks
BHARAT

**Comment by dbolotin** [comment]
Please verify that this error reproduce with 2.1.12 release. You seems to be using pre-release mixcr binary from some very old commit.
