### ISSUE TITLE
-p rna-seq option produces errors: Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException:0

### ISSUE THREAD

**Issue by guanxn90** [milaboratory/mixcr#430]
## Checklist before submitting the issue:

 - [ ] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [ ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*
I want to apply miXCR to **bulk RNA-seq**. I first tested it using TCR-seq library which I analyzed before without any errors. The way I test it was: just added the -p rna-seq option and performed two rounds of partial assembly according to the manual. 
## Actual Result
miXCR exports results correctly, but produced errors
*A description of what actually happened*
When not using -p rna-seq option and no performing two rounds of partial assembly, there were no error messages. However, when using -p rna-seq and two rounds of partial assembly, miXCR still exports results, but there was always error message produced. 
## Exact MiXCR commands 

'mixcr align -p rna-seq -f --species $SPECIES -OallowPartialAlignments=true --save-description --save-reads -v --report ${OUT}${NAME}_align_report.txt --threads 8 $FASTQ_R1 ${OUT}${NAME}_alignment.vdjca
mixcr assemblePartial -f --report ${OUT}${NAME}_assemble_report_p1.txt ${OUT}${NAME}_alignment.vdjca ${OUT}${NAME}_alignmentRescued_p1.vdjca
mixcr assemblePartial -f --report ${OUT}${NAME}_assemble_report_p2.txt ${OUT}${NAME}_alignmentRescued_p1.vdjca ${OUT}${NAME}_alignmentRescued_p2.vdjca
mixcr extendAlignments -f ${OUT}${NAME}_alignmentRescued_p2.vdjca ${OUT}${NAME}_alignmentsRescued_p2_extended.vdjca

mixcr assemble -f --report ${OUT}${NAME}_assemble_report.txt ${OUT}${NAME}_alignmentsRescued_p2_extended.vdjca ${OUT}${NAME}_assemble.clns
mixcr exportAlignments -f -cloneId -sequence -vHits -dHits -jHits -vAlignments -dAlignments -jAlignments -nFeature CDR3 -minFeatureQuality CDR3 -aaFeature CDR3 -vHit -dHit -jHit -vAlignment -dAlignment -jAlignment ${OUT}${NAME}_alignmentsRescued_p2_extended.vdjca ${OUT}${NAME}_alignment_export.txt
mixcr exportClones -f -c TRA --preset-file assemble_preset.txt ${OUT}${NAME}_assemble.clns ${OUT}${NAME}_clone_TRA_export.txt
mixcr exportClones -f -c TRB --preset-file assemble_preset.txt ${OUT}${NAME}_assemble.clns ${OUT}${NAME}_clone_TRB_export.txt'

## MiXCR report files 

''' Reference library: repseqio.v1.5:9606:29a95112c52f62585b28d241db7fd523
Alignment: 2.9%
Alignment: 26.2%  ETA: 00:00:09
Alignment: 46.6%  ETA: 00:00:02
Alignment: 58.3%  ETA: 00:00:03
Alignment: 72.9%  ETA: 00:00:01
Alignment: 93.2%  ETA: 00:00:00
============= Report ==============
Analysis time: 8.04s
Total sequencing reads: 50000
Successfully aligned reads: 49556 (99.11%)
Alignment failed, no hits (not TCR/IG?): 169 (0.34%)
Alignment failed because of absence of CDR3 parts: 1 (0%)
Alignment failed because of low total score: 274 (0.55%)
Overlapped: 0 (0%)
Overlapped and aligned: 0 (0%)
Alignment-aided overlaps: 0 (�%)
Overlapped and not aligned: 0 (0%)
TRA chains: 24622 (49.69%)
TRB chains: 24931 (50.31%)
TRD chains: 1 (0%)
TRA,TRD chains: 2 (0%)
Building index: 0%
Searching for overlaps: 0%
Searching for overlaps: 60.1%  ETA: 00:00:00
============= Report ==============
Analysis time: 2.58s
Total alignments analysed: 50000
Number of output alignments: 50000 (100%)
Alignments already with CDR3 (no overlapping is performed): 42551 (85.1%)
Successfully overlapped alignments: 0 (0%)
Left parts with too small N-region (failed to extract k-mer): 0 (0%)
Extracted k-mer diversity: 3435
Dropped due to wildcard in k-mer: 0 (0%)
Dropped due to too short NRegion parts in overlap: 0 (0%)
Dropped overlaps with empty N region due to no complete NDN coverage: 0 (0%)
Number of left-side alignments: 65 (0.13%)
Number of right-side alignments: 6940 (13.88%)
Complex overlaps: 0 (0%)
Over-overlaps: 0 (0%)
Partial alignments written to output: 7449 (14.9%)
Building index: 0%
Building index: 95.7%  ETA: 00:00:00
Searching for overlaps: 0%
Searching for overlaps: 50.7%  ETA: 00:00:00
============= Report ==============
Analysis time: 3.06s
Total alignments analysed: 50000
Number of output alignments: 50000 (100%)
Alignments already with CDR3 (no overlapping is performed): 42551 (85.1%)
Successfully overlapped alignments: 0 (0%)
Left parts with too small N-region (failed to extract k-mer): 0 (0%)
Extracted k-mer diversity: 3435
Dropped due to wildcard in k-mer: 0 (0%)
Dropped due to too short NRegion parts in overlap: 0 (0%)
Dropped overlaps with empty N region due to no complete NDN coverage: 0 (0%)
Number of left-side alignments: 65 (0.13%)
Number of right-side alignments: 6940 (13.88%)
Complex overlaps: 0 (0%)
Over-overlaps: 0 (0%)
Partial alignments written to output: 7449 (14.9%)
Processing: 0%
Processing: 31.9%  ETA: 00:00:02
============= Report ==============
Analysis time: 1.94s
Extended alignments count: 0 (0%)
V extensions total: 0 (0%)
V extensions with merged targets: 0 (0%)
J extensions total: 0 (0%)
J extensions with merged targets: 0 (0%)
V+J extensions: 0 (0%)
Mean V extension length: NaN
Mean J extension length: NaN
Initialization: progress unknown
Mapping low quality reads: 1.9%
Writing clones: 0%
============= Report ==============
Analysis time: 2.35s
Final clonotype count: 93
Average number of reads per clonotype: 365.48
Reads used in clonotypes, percent of total: 33990 (67.98%)
Reads used in clonotypes before clustering, percent of total: 38792 (77.58%)
Number of reads used as a core, percent of used: 34406 (88.69%)
Mapped low quality reads, percent of used: 4386 (11.31%)
Reads clustered in PCR error correction, percent of used: 4802 (12.38%)
Reads pre-clustered due to the similar VJC-lists, percent of used: 0 (0%)
Reads dropped due to the lack of a clone sequence: 7449 (14.9%)
Reads dropped due to low quality: 5 (0.01%)
Reads dropped due to failed mapping: 3754 (7.51%)
Reads dropped with low quality clones: 0 (0%)
Clonotypes eliminated by PCR error correction: 636
Clonotypes dropped as low quality: 0
Clonotypes pre-clustered due to the similar VJC-lists: 0
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at com.milaboratory.mixcr.export.FieldExtractors$32.create(FieldExtractors.java:817)
	at com.milaboratory.mixcr.export.FieldExtractors.parse(FieldExtractors.java:584)
	at com.milaboratory.mixcr.cli.ActionExportParameters.parseFields(ActionExportParameters.java:224)
	at com.milaboratory.mixcr.cli.ActionExportParameters.parse(ActionExportParameters.java:200)
	at com.milaboratory.mixcr.cli.ActionExport.parseParameters(ActionExport.java:58)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:101)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:124)
Exporting clones: 0%
Exporting clones: 0%
'''

**Comment by guanxn90** [comment]
The error is at the end of report file. Not sure "Mean V extension length: NaN
Mean J extension length: NaN" is the problem or not. Thanks a lot.
