### ISSUE TITLE
exportAlignmentsPretty: expect backward compatibility?

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#455]
I was running exportAlignmentsPretty against a gzipped vdjca file generated using MiXCR 2.2x.  When using MiXCR 3, I get an error like this.  Is this expected?  I assume the ?? is because my input is gzipped, which was supported for MiXCR 2.

Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandExportAlignmentsPretty@470f1802): java.lang.RuntimeException: Unsupported file format; .vdjca file of version �� while you are running MiXCR MiXCR.VDJC.V13
        at picocli.CommandLine.execute(CommandLine.java:1004)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:48)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:31)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
        at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:53)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:25)
Caused by: java.lang.RuntimeException: Unsupported file format; .vdjca file of version �� while you are running MiXCR MiXCR.VDJC.V13
        at com.milaboratory.mixcr.basictypes.VDJCAlignmentsReader.init(VDJCAlignmentsReader.java:142)
        at com.milaboratory.mixcr.basictypes.VDJCAlignmentsReader.init(VDJCAlignmentsReader.java:122)
        at com.milaboratory.mixcr.basictypes.VDJCAlignmentsReader.take(VDJCAlignmentsReader.java:258)
        at com.milaboratory.mixcr.basictypes.VDJCAlignmentsReader.take(VDJCAlignmentsReader.java:50)
        at cc.redberry.pipe.CUtils$OPIterator.hasNext(CUtils.java:420)
        at com.milaboratory.mixcr.cli.CommandExportAlignmentsPretty.run0(CommandExportAlignmentsPretty.java:166)
        at com.milaboratory.mixcr.cli.ACommand.run(ACommand.java:73)
        at picocli.CommandLine.execute(CommandLine.java:996)

**Comment by bbimber** [comment]
ok.  can one specify .gz when running the 'analyze' commands?  with those you provide the basename only, from what i can see.

**Comment by PoslavskySV** [comment]
> ok. can one specify .gz when running the 'analyze' commands? with those you provide the basename only, from what i can see.

no, there is no option. I'll add it to release, this should be quite simple:)

**Comment by dbolotin** [comment]
MiXCR 3.0 now always outputs compressed file, the compression is performed on chunks consisting of ~1000 alignments with LZ4 algorithm, with some extra meta information. Both `vdjca` and `clna` (clones with alignments) files uses such format for alignment storage.

So, basically compression is built into format and files can't be additionally compressed with `.gz`. Additional compression is not possible (1) due to the technical reasons - reading is now performed with lower level API - through memory mapped file, and (2) it is not rational now, as it should not significantly reduce the file size "information is already as dense as possible".

As a result MiXCR 3.0 `vdjca` files are 3 to 4 fold smaller than the same files from previous MiXCR versions.
