### ISSUE TITLE
assembleContigs failed

### ISSUE THREAD

**Issue by weizhiting** [milaboratory/mixcr#481]
HI:
In order to assemble full TCR/IG  receptor, I run "mixcr assembleContigs   clones.clna  full_clones.clns", 

but error 
"""Java HotSpot(TM) 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAssembleContigs@6ca0256d): java.lang.IllegalArgumentException: Wrong file type. Magic = targetSequence, expected = MiXCR.CLNA.V03
	at picocli.CommandLine.execute(CommandLine.java:1004)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:48)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:31)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:53)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:25)
Caused by: java.lang.IllegalArgumentException: Wrong file type. Magic = targetSequence, expected = MiXCR.CLNA.V03
	at com.milaboratory.mixcr.basictypes.ClnAReader.<init>(ClnAReader.java:126)
	at com.milaboratory.mixcr.basictypes.ClnAReader.<init>(ClnAReader.java:173)
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.run1(CommandAssembleContigs.java:87)
	at com.milaboratory.mixcr.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:99)
	at com.milaboratory.mixcr.cli.ACommand.run(ACommand.java:73)
	at picocli.CommandLine.execute(CommandLine.java:996)
	... 7 more"""  happens.  

the align and assemble procedure finished ok , what is more,  
"mixcr  exportClones  -c TCR -f  clones.clna  TCRclones.txt"  is  ok,
i run the pipeline in three samples, the other two finished ok.
I just can't figure it out, hope receive your reply!  thanks~

**Comment by PoslavskySV** [comment]
Hi, 

did you use `-a` (`--write-alignments`) flag for `assemble` command?

**Comment by weizhiting** [comment]
Hi,
Thanks for your reply. Yes. here is the command
"mixcr align  -OvParameters.geneFeatureToAlign=VGeneWithP    --species hsa  --report report.tsv -t 48     -p kAligner2  -OallowPartialAlignments=true  clean_1.fq  clean_2.fq  alignments.vdjca"

"mixcr assemble --write-alignments   --report  report.txt  alignments.vdjca  clones.clna "

**Comment by PoslavskySV** [comment]
It looks like a bug. Could you please paste all exact commands you used, version of MiXCR (`mixcr -v`), and report files produced during `align` and `assemble`? We can fix the bug much faster if you also can provide the initial data files which caused the error (you can share it e.g. via my private email poslavskysv (at) milaboratory dot com ; we promise to keep your data in secret and remove after debugging).

**Comment by weizhiting** [comment]
sorry for  the delay reply! I use the newest version of MixCR (v3.0.3 ) and Java ("11.0.1" 2018-10-16 LTS). 
I hava send the alignment file  and report file to your email as the raw file is too large. please check  your email!

**Comment by PoslavskySV** [comment]
Hi!

Thanks for sharing the data, it was very helpful. We've fixed the bug in the develop version. It will be released very soon.

**Comment by weizhiting** [comment]
yes, the bug had been fixed. Thanks for all your help!
