### ISSUE TITLE
exportAlignments fails on .clna file

### ISSUE THREAD

**Issue by JohnMCMa** [milaboratory/mixcr#482]
## Checklist before submitting the issue:

 - [X] The issue is strongly related to the MiXCR software
 - [X] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [X] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [X] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

A text file containing all reads' readId, cloneId and their imputed `VDJRegion`.

## Actual Result

````
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandExport$CommandExportAlignments@bb9e6dc): java.util.NoSuchElementException
        at picocli.CommandLine.execute(CommandLine.java:1004)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:48)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:31)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
        at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:53)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:25)
Caused by: java.util.NoSuchElementException
        at java.util.ArrayList$Itr.next(ArrayList.java:854)
        at com.milaboratory.mixcr.basictypes.BasicVDJCAlignmentReader.take(BasicVDJCAlignmentReader.java:129)
        at com.milaboratory.mixcr.basictypes.BasicVDJCAlignmentReader.take(BasicVDJCAlignmentReader.java:49)
        at cc.redberry.pipe.util.CountLimitingOutputPort.take(CountLimitingOutputPort.java:67)
        at cc.redberry.pipe.blocks.FilteringPort.take(FilteringPort.java:69)
        at com.milaboratory.mixcr.cli.CommandExport$CommandExportAlignments.run1(CommandExport.java:183)
        at com.milaboratory.mixcr.cli.CommandExport.run0(CommandExport.java:139)
        at com.milaboratory.mixcr.cli.ACommand.run(ACommand.java:73)
        at picocli.CommandLine.execute(CommandLine.java:996)
        ... 7 more
````
An output file is still written with the expected format, but they're certainly incomplete--the largest cloneId in the file is smaller than the number of cloneIds from the `exportClones` output.

## Exact MiXCR commands 

`java -jar ~/mixcr-3.0.3/mixcr.jar exportAlignments -f -readIds -cloneId -c TRB -nFeatureImputed VDJRegion "/rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d/10X-033_14d.clna" "/rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d/10X-033_14d.reads.TRB.VDJRegionImputed.txt"`

Removing the chain parameter does not solve the problem. Using the VDJCA input solves the problem, but I need the `cloneId`. The associated .clns exports normally. with `exportClones -p full`

## MiXCR report files 

```
Analysis date: Wed Dec 26 15:47:36 CST 2018
Input file(s): /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/fastq/20181026/22_S63_L001_R1_001.fastq.gz,/rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/fastq/20181026/22_S63_L001_R2_001.fastq.gz
Output file(s): /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.vdjca
Version: 3.0.3; built=Sun Nov 18 09:48:30 CST 2018; rev=5281a0f; lib=repseqio.v1.5
Command line arguments: --species hsa --report /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.report -p rna-seq -OvParameters.geneFeatureToAlign=VTranscriptWithP -OvParameters.parameters.floatingLeftBound=true -OjParameters.parameters.floatingRightBound=false -OcParameters.parameters.floatingRightBound=true -t 4 /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/fastq/20181026/22_S63_L001_R1_001.fastq.gz /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/fastq/20181026/22_S63_L001_R2_001.fastq.gz /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.vdjca
Analysis time: 5.91m
Total sequencing reads: 774215
Successfully aligned reads: 580103 (74.93%)
Chimeras: 4 (0%)
Paired-end alignment conflicts eliminated: 113685 (14.68%)
Alignment failed, no hits (not TCR/IG?): 165507 (21.38%)
Alignment failed because of absence of V hits: 15831 (2.04%)
Alignment failed because of absence of J hits: 11895 (1.54%)
No target with both V and J alignments: 878 (0.11%)
Alignment failed because of low total score: 1 (0%)
Overlapped: 558504 (72.14%)
Overlapped and aligned: 393311 (50.8%)
Alignment-aided overlaps: 27618 (7.02%)
Overlapped and not aligned: 165193 (21.34%)
V gene chimeras: 898 (0.12%)
J gene chimeras: 12 (0%)
TRA chains: 182602 (31.48%)
TRB chains: 397495 (68.52%)
TRG chains: 2 (0%)
======================================
Analysis date: Wed Dec 26 15:53:30 CST 2018
Input file(s): /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.vdjca
Output file(s): /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.clna
Version: 3.0.3; built=Sun Nov 18 09:48:30 CST 2018; rev=5281a0f; lib=repseqio.v1.5
Command line arguments: --report /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.report --write-alignments -OassemblingFeatures="[CDR3]" -OseparateByV=false -OseparateByJ=true -OseparateByC=false -t 4 /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.vdjca /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.clna
Analysis time: 56.30s
Final clonotype count: 8555
Average number of reads per clonotype: 51.92
Reads used in clonotypes, percent of total: 444173 (57.37%)
Reads used in clonotypes before clustering, percent of total: 462636 (59.76%)
Number of reads used as a core, percent of used: 454234 (98.18%)
Mapped low quality reads, percent of used: 8402 (1.82%)
Reads clustered in PCR error correction, percent of used: 18463 (3.99%)
Reads pre-clustered due to the similar VJC-lists, percent of used: 1 (0%)
Reads dropped due to the lack of a clone sequence: 108689 (14.04%)
Reads dropped due to low quality: 165 (0.02%)
Reads dropped due to failed mapping: 8613 (1.11%)
Reads dropped with low quality clones: 0 (0%)
Clonotypes eliminated by PCR error correction: 6635
Clonotypes dropped as low quality: 0
Clonotypes pre-clustered due to the similar VJC-lists: 1
======================================
Analysis date: Wed Dec 26 15:55:32 CST 2018
Input file(s): /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.clna
Output file(s): /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.contigs.clns
Version: 3.0.3; built=Sun Nov 18 09:48:30 CST 2018; rev=5281a0f; lib=repseqio.v1.5
Command line arguments: --report /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.report -t 4 /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.clna /rsrch3/scratch/lym_myl_rsch/mma/Green/TCR/output/10X-033_14d//10X-033_14d.contigs.clns
Analysis time: 1.08m
Initial clonotype count: 8555
Final clonotype count: 8555 (100%)
Longest contig length: 733
Clustered variants: 0 (0%)
Reads in clustered variants: 0.0 (0%)
Reads in divided (newly created) clones: 0.0 (0%)
======================================
```

**Comment by JohnMCMa** [comment]
I got a different error at the same step instead:
```
Exception in thread "main" java.lang.AssertionError
        at com.milaboratory.mixcr.basictypes.BasicVDJCAlignmentReader.take(BasicVDJCAlignmentReader.java:127)
        at com.milaboratory.mixcr.basictypes.BasicVDJCAlignmentReader.take(BasicVDJCAlignmentReader.java:49)
        at cc.redberry.pipe.util.CountLimitingOutputPort.take(CountLimitingOutputPort.java:67)
        at cc.redberry.pipe.blocks.FilteringPort.take(FilteringPort.java:69)
        at com.milaboratory.mixcr.cli.CommandExport$CommandExportAlignments.run1(CommandExport.java:184)
        at com.milaboratory.mixcr.cli.CommandExport.run0(CommandExport.java:140)
        at com.milaboratory.cli.ACommand.run(ACommand.java:90)
        at picocli.CommandLine.execute(CommandLine.java:996)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:49)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:32)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
        at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:54)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:26)
```

**Comment by dbolotin** [comment]
Seems like a different bug.
Can you share the data to reproduce the problem on our side?

**Comment by JohnMCMa** [comment]
What is the appropriate email to contact? And what should I send--fastq? vdjca? clna? clns?

**Comment by dbolotin** [comment]
Because bug may be on another step we need to reproduce the whole pipeline. For this we need original fastq files.

My email to send the data: bolotin.dmitriy (at) gmail.com

Please also post all MiXCR commands starting from fastq files.

(I will remove the data after debugging the problem, and it will not be shared with anybody outside the MiXCR developer team)

**Comment by dbolotin** [comment]
Let me know, if there are any problems sending the data (except the holidays 😀of course). No hurry, just want to make sure you haven't send it already and I missed it somehow.
Happy New Year!

**Comment by JohnMCMa** [comment]
I sent you the files.

**Comment by dbolotin** [comment]
@JohnMCMa please verify that the issue is resolved.

**Comment by JohnMCMa** [comment]
Hi @dbolotin : I thought you closed this because you confirmed it's been fixed... I will test that tomorrow.

**Comment by JohnMCMa** [comment]
Confirmed to work in that particular case.
