### ISSUE TITLE
Error with exportClones and -nMutations CDR3

### ISSUE THREAD

**Issue by LCapitani** [milaboratory/mixcr#500]
Hey there!

## Expected Result and Exact MiXCR commands 

*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*

I ran the mixcr analyze amplicon command and I am now attempting to personalize the exported information. This is how I ran the analysis:

`mixcr analyze amplicon -s hsa --starting-material dna --5-end v-primers --3-end c-primers --adapters no-adapters --receptor-type igh --only-productive --contig-assembly file1.fastq file2.fastq`

I am then attempting to export the following fields, which are saved in a .txt file:

-cloneId
-count
-fraction
-vHit
-jHit
-vAlignment
-jAlignment
-lengthOf CDR3
-aaFeature CDR3
-nFeature CDR3
-nMutations CDR3

I run the export step as follows:

`mixcr exportClones -f --preset-file /path_to/myFields.txt file_name.contigs.clns export_file_name.txt`

## Actual Result

I get this error: 

```

Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandExport$CommandExportClones@670002): java.lang.IllegalArgumentException: -nMutations: Gene feature CDR3 covers several gene types (not possible to select corresponding alignment)
        at picocli.CommandLine.execute(CommandLine.java:1004)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:48)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:31)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
        at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:53)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:25)
Caused by: java.lang.IllegalArgumentException: -nMutations: Gene feature CDR3 covers several gene types (not possible to select corresponding alignment)
        at com.milaboratory.mixcr.export.FeatureExtractors$MutationsExtractor.validate(FeatureExtractors.java:123)
        at com.milaboratory.mixcr.export.FeatureExtractors$WithHeader.getParameters(FeatureExtractors.java:79)
        at com.milaboratory.mixcr.export.FeatureExtractors$WithHeader.getParameters(FeatureExtractors.java:48)
        at com.milaboratory.mixcr.export.FieldWithParameters.create(FieldWithParameters.java:53)
        at com.milaboratory.mixcr.cli.CommandExport.extractor(CommandExport.java:362)
        at com.milaboratory.mixcr.cli.CommandExport.lambda$run0$1(CommandExport.java:136)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.milaboratory.mixcr.cli.CommandExport.run0(CommandExport.java:137)
        at com.milaboratory.mixcr.cli.ACommand.run(ACommand.java:73)
        at picocli.CommandLine.execute(CommandLine.java:996)
        ... 7 more

```

Any idea on what I am doing wrong/misunderstanding about the procedure?
Thanks!

**Comment by PoslavskySV** [comment]
Hi! 

The problem is that `-nMutations CDR3` is not a valid option. Mutations are always considered relatively to some reference sequence, while CDR3 has no any reference. You can use e.g.
```
-nMutations VCDR3Part
-nMutations JCDR3Part
-nMutations DCDR3Part
```

**Comment by sdwien** [comment]
For me, `-nMutations VCDR3Part` actually did not work either:
My command was:
`mixcr-3.0.13/mixcr exportClones -f --minimal-clone-count 2 -cloneId -count -fraction -vHit -dHit -jHit -vGene -dGene -jGene -vFamily -dFamily -jFamily -aaFeature CDR1 -aaFeature CDR2 -aaFeature CDR3 -aaFeature FR1 -aaFeature FR2 -aaFeature FR3 -aaFeature FR4 -nMutations CDR1 -aaMutations CDR1 -nMutations CDR2 -aaMutations CDR2 -nMutations VCDR3Part -nMutations JCDR3Part -nMutations DCDR3Part -nMutations FR1 -aaMutations FR1 -nMutations FR2 -aaMutations FR2 -nMutations FR3 -aaMutations FR3 -nMutations FR4 -aaMutations FR4 "$sample"_pair_mixcr_VDJRegion.clns "$sample"_pair_mixcr_VDJRegion_clones_minCloneCount2_aaFeaturesMutations.txt`
and the error I got was:
```
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandExport$CommandExportClones@7098b907): java.lang.IllegalArgumentException: -nMutations: Please use -nMutationsRelative option instead and specify base gene feature to extract mutations from alignment-attached gene feature VCDR3Part
        at picocli.CommandLine.execute(CommandLine.java:1004)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:76)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:65)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
        at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:89)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:59)
Caused by: java.lang.IllegalArgumentException: -nMutations: Please use -nMutationsRelative option instead and specify base gene feature to extract mutations from alignment-attached gene feature VCDR3Part
        at com.milaboratory.mixcr.export.FeatureExtractors$MutationsExtractor.validate(FeatureExtractors.java:132)
        at com.milaboratory.mixcr.export.FeatureExtractors$WithHeader.getParameters(FeatureExtractors.java:77)
        at com.milaboratory.mixcr.export.FeatureExtractors$WithHeader.getParameters(FeatureExtractors.java:48)
        at com.milaboratory.mixcr.export.FieldWithParameters.create(FieldWithParameters.java:53)
        at com.milaboratory.mixcr.cli.CommandExport.extractor(CommandExport.java:392)
        at com.milaboratory.mixcr.cli.CommandExport.lambda$run0$1(CommandExport.java:166)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.milaboratory.mixcr.cli.CommandExport.run0(CommandExport.java:167)
        at com.milaboratory.cli.ACommand.run(ACommand.java:90)
        at picocli.CommandLine.execute(CommandLine.java:996)
        ... 7 more
```
What would be the base gene feature for VCDR3Part?
I am working on RNA-Seq data, does this make any difference here?
Thanks a lot for any suggestions you might have!
Best, Sophia

**Comment by PoslavskySV** [comment]
@sdwien sorry for the late reply,

my answer contained a mistake, I just updated it, one need to use
```
-nMutations GermlineVCDR3Part
-nMutations GermlineJCDR3Part
```

Also for the account of P-segment it is possible to use
```
-nMutationsRelative VCDR3Part GermlineVCDR3Part
```
but this is quite advance feature and we [do not have related documentation yet](https://github.com/milaboratory/mixcr/issues/392)...
