### ISSUE TITLE
Align Error while running command (com.milaboratory.mixcr.cli.CommandAlign@7486b455)

### ISSUE THREAD

**Issue by ashleypng** [milaboratory/mixcr#502]

**Comment by ashleypng** [comment]
**Expected result**: Align single end RNAseq data resulting in vdjca output file 
**Actual result**: (Java) Error
**Exact MiXCR commands**
'mixcr align -p rna-seq -s mmu -OallowPartialAlignments=true --verbose 1786_CB2WEANXX_GTCCGC_L001_R1.fastq.gz 1786_CB2WEANXX_GTCCGC_L001_R1.fastq.gz_alignments.vdjca'

**MiXCR report (files)**
'''WARNING: Functional gene IGHV8-13*00 excluded due to absent VTranscriptWithP
WARNING: Functional gene IGKV8-23-1*00 excluded due to absent VTranscriptWithP
WARNING: Functional gene IGKV20-101-2*00 excluded due to absent VTranscriptWithP
WARNING: Functional gene TRGV2*00 excluded due to absent VTranscriptWithP
WARNING: Functional gene IGHV13-1*00 excluded due to absent VTranscriptWithP
WARNING: Functional gene IGKV14-130*00 excluded due to absent VTranscriptWithP
WARNING: Functional gene IGKV8-28*00 excluded due to absent VTranscriptWithP
WARNING: 7 functional genes were excluded, re-run with --verbose option to see the list of excluded genes and exclusion reason.
WARNING: 84 non-functional genes excluded.
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAlign@7486b455): java.lang.RuntimeException: java.io.EOFException
	at picocli.CommandLine.execute(CommandLine.java:1004)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:78)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:61)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:83)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:55)
Caused by: java.lang.RuntimeException: java.io.EOFException
	at com.milaboratory.cli.ACommand.run(ACommand.java:94)
	at picocli.CommandLine.execute(CommandLine.java:996)
	... 7 more
Caused by: java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at com.milaboratory.core.io.CompressionType.createInputStream(CompressionType.java:63)
	at com.milaboratory.core.io.CompressionType.createInputStream(CompressionType.java:47)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.<init>(SingleFastqReader.java:251)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.<init>(SingleFastqReader.java:65)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.<init>(SingleFastqReader.java:79)
	at com.milaboratory.mixcr.cli.CommandAlign.createReader(CommandAlign.java:249)
	at com.milaboratory.mixcr.cli.CommandAlign.run1(CommandAlign.java:450)
	at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
	at com.milaboratory.cli.ACommand.run(ACommand.java:90)
	... 8 more'''

$ java -version
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)

Thanks.
