### ISSUE TITLE
Bug in assembleContigs

### ISSUE THREAD

**Issue by PoslavskySV** [milaboratory/mixcr#528]
```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAssembleContigs@5ecba515): java.lang.RuntimeException: While processing clone #2
	at picocli.CommandLine.execute(CommandLine.java:1004)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:72)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:61)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:85)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:55)
Caused by: java.lang.RuntimeException: While processing clone #2
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$10(CommandAssembleContigs.java:212)
	at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:313)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.mergeTwoAlignments(FullSeqAssembler.java:1052)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.buildClone(FullSeqAssembler.java:843)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.lambda$callVariants$0(FullSeqAssembler.java:270)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.callVariants(FullSeqAssembler.java:271)
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$10(CommandAssembleContigs.java:210)
```

**Comment by Gaut1993** [comment]
I'm having the same issue, was it fixed ? (First time running mixcr app)

**Comment by PoslavskySV** [comment]
@Gaut1993  Hi, which MiXCR version you use ?

**Comment by Gaut1993** [comment]
@PoslavskySV Hi, I'm sorry for the delayed response. I thought that I had answered. The problem is solved, I think my problem was coming from my JDK version which was not up to date.

**Comment by zxl215** [comment]
@Gaut1993 @PoslavskySV Hi, I'm having this same problem. I want to know you how to solve the problem. Could  you help me?

**Comment by Gaut1993** [comment]
@zxl215  Hi, the problem has been solved after I updated MIXCR to the last version.
