### ISSUE TITLE
Error with mixcr analyze --region-of-interest Vregion (--region-of-interest only CDR3 works)

### ISSUE THREAD

**Issue by joonaas** [milaboratory/mixcr#531]
## Actual Result
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandAmplicon@7ec58feb): java.lang.ArrayIndexOutOfBoundsException: -1
	at picocli.CommandLine.execute(CommandLine.java:1004)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:72)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:61)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:85)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:55)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at com.milaboratory.mixcr.assembler.CloneFactory.create(CloneFactory.java:214)
	at com.milaboratory.mixcr.assembler.CloneFactory.create(CloneFactory.java:254)
	at com.milaboratory.mixcr.assembler.CloneAssembler$ClonesBuilder.buildClones(CloneAssembler.java:588)
	at com.milaboratory.mixcr.assembler.CloneAssembler.buildClones(CloneAssembler.java:335)
	at com.milaboratory.mixcr.assembler.CloneAssemblerRunner.run(CloneAssemblerRunner.java:131)
	at com.milaboratory.mixcr.cli.CommandAssemble.run1(CommandAssemble.java:200)
	at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
	at com.milaboratory.cli.ACommand.run(ACommand.java:90)
	at com.milaboratory.mixcr.cli.CommandAnalyze.run0(CommandAnalyze.java:652)
	at com.milaboratory.cli.ACommand.run(ACommand.java:90)
	at picocli.CommandLine.execute(CommandLine.java:996)

## Exact MiXCR commands 
mixcr analyze amplicon -s hsa --starting-material dna --5-end no-v-primers --3-end j-primers --adapters no-adapters --receptor-type igl --contig-assembly --region-of-interest Vregion 1.fastq J2.fastq analysisVL

**Comment by dbolotin** [comment]
Thanks for reporting!

**Comment by PoslavskySV** [comment]
Hi! Region of interest must cover `CDR3` (or at least something like `CDR3(-3,3)`), so your option 
```
--region-of-interest Vregion
```
is incorrect.  I'll add appropriate error message. May be you mean `VDJRegion`?
