### ISSUE TITLE
java -jar mixcr.jar does not search for library in libraries/

### ISSUE THREAD

**Issue by jggatter** [milaboratory/mixcr#546]
I was running mixcr in a docker container and noticed that when you run `java -jar mixcr.jar`, mixcr does not search the libraries/ directory as `mixcr` does.

```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAlign@72cc7e6f): java.lang.RuntimeException: Can't find library for following library name and species: imgt.201918-4.sv5 + hs
at picocli.CommandLine.execute(CommandLine.java:1004)
at picocli.CommandLine.access$900(CommandLine.java:142)
at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:72)
at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:61)
at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:85)
at com.milaboratory.mixcr.cli.Main.main(Main.java:55)
Caused by: java.lang.RuntimeException: Can't find library for following library name and species: imgt.201918-4.sv5 + hs
at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:395)
at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:293)
at com.milaboratory.mixcr.cli.CommandAlign.getLibrary(CommandAlign.java:274)
at com.milaboratory.mixcr.cli.CommandAlign.getAlignerParameters(CommandAlign.java:230)
at com.milaboratory.mixcr.cli.CommandAlign.run1(CommandAlign.java:399)
at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
at com.milaboratory.cli.ACommand.run(ACommand.java:90)
at picocli.CommandLine.execute(CommandLine.java:996)
... 7 more
```
<img width="1674" alt="mixcr_libararies" src="https://user-images.githubusercontent.com/39911742/66599100-8151d880-eb70-11e9-8c19-5b214851d715.png">

Not sure if you approve of my usage but thought it might be nice to inform somebody!

Best,
James

**Comment by dbolotin** [comment]
Thanks for reporting!

Please try official mixcr image ([repo](https://github.com/milaboratory/mixcr-docker), [image](https://hub.docker.com/r/milaboratory/mixcr)).

Try mounting library file to `/mixcr/libraries/` folder, mixcr should check that folder.

We'll document this aspects, and overall do another iteration for the image (e.g. will make both alpine and debian versions and move to java 11, because it has much better support for container environment. I think we'll also make image including imgt library.

**Comment by dbolotin** [comment]
Just released docker with built-in IMGT reference.

Try something like this:
docker run -v /path/to/data:/work -it --rm milaboratory/mixcr:3.0.11-imgt mixcr align -f --library imgt -s hs test_R1.fastq.gz s1.vdjca

All images with tags ending with `-imgt` contain IMGT reference.

**Comment by decenwang** [comment]
> Just released docker with built-in IMGT reference.
> 
> Try something like this:
> docker run -v /path/to/data:/work -it --rm milaboratory/mixcr:3.0.11-imgt mixcr align -f --library imgt -s hs test_R1.fastq.gz s1.vdjca
> 
> All images with tags ending with `-imgt` contain IMGT reference.

Hi Dr. Bolotin,

I got the same problem, and I also found the same issues in the "Issue" column. but I really do not know how to figure it out. Could please you help?

**Linux: Unbutu 18.0.4 LTS
Mixcr version: 3.0.11 installed by conda
java version : 
openjdk version "11.0.1-internal" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.1-internal+0-adhoc..src, mixed mode)
Command I used: 
mixcr analyze amplicon --species hs \
--starting-material rna \
--region-of-interest CDR3 \
--receptor-type TRB \
--5-end v-primers \
--3-end j-primers \
--adapters no-adapters \
--report ./ \
seq_R1.fastq seq_R2.fastq analysis**

**BUT if I use these commands:
mixcr analyze amplicon --species hs \
--starting-material rna \
--5-end v-primers \
--3-end j-primers \
--adapters no-adapters \
--receptor-type TRB \
seq_R1.fastq seq_R2.fastq analysis
Mixcr can run well!!!!!!!!**
Errors as following:
Alignment: 16.6%
Alignment: 33.2%  ETA: 00:00:04
Alignment: 49.8%  ETA: 00:00:09
Alignment: 66.4%  ETA: 00:00:04
Alignment: 83%  ETA: 00:00:02
Alignment: 99.5%  ETA: 00:00:00
============= Report ==============
Analysis time: 12.87s
Total sequencing reads: 5000
Successfully aligned reads: 4972 (99.44%)
Paired-end alignment conflicts eliminated: 5 (0.1%)
Alignment failed, no hits (not TCR/IG?): 6 (0.12%)
Alignment failed because of absence of J hits: 22 (0.44%)
Overlapped: 4989 (99.78%)
Overlapped and aligned: 4963 (99.26%)
Alignment-aided overlaps: 5 (0.1%)
Overlapped and not aligned: 26 (0.52%)
TRB chains: 4809 (96.72%)
TRG chains: 163 (3.28%)
Realigned with forced non-floating bound: 32 (0.64%)
Realigned with forced non-floating right bound in left read: 7 (0.14%)
Realigned with forced non-floating left bound in right read: 7 (0.14%)
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandAmplicon@70242f38): java.lang.RuntimeException: java.nio.file.FileSystemException: .: Is a directory
	at picocli.CommandLine.execute(CommandLine.java:1004)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:72)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:61)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:85)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:55)
Caused by: java.lang.RuntimeException: java.nio.file.FileSystemException: .: Is a directory
	at com.milaboratory.mixcr.cli.Util.appendAtomically(Util.java:80)
	at com.milaboratory.mixcr.cli.Util.appendAtomically(Util.java:71)
	at com.milaboratory.mixcr.cli.Util.writeReport(Util.java:97)
	at com.milaboratory.mixcr.cli.CommandAlign.run1(CommandAlign.java:579)
	at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
	at com.milaboratory.cli.ACommand.run(ACommand.java:90)
	at com.milaboratory.mixcr.cli.CommandAnalyze.run0(CommandAnalyze.java:637)
	at com.milaboratory.cli.ACommand.run(ACommand.java:90)
	at picocli.CommandLine.execute(CommandLine.java:996)
	... 7 more
Caused by: java.nio.file.FileSystemException: .: Is a directory
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:178)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
	at com.milaboratory.mixcr.cli.Util.appendAtomically(Util.java:75)
	... 15 more

Between the two command lines the difference is tiny, and they are normal options in mixcr. 

Thanks a million!

Best,

Decen

**Comment by dbolotin** [comment]
The error seems legit `java.nio.file.FileSystemException: .: Is a directory`, as the `.` is actually a directory.

You should specify file path for the `--report` option (e.g. `--report ./my_report.file.txt` .

**Comment by dbolotin** [comment]
BTW, please use latest MiXCR 3.0.12 docker image (released couple of days ago), it contains both updated IMGT and built-in libraries.

**Comment by decenwang** [comment]
Thanks a lot! I tried, it works well.
