### ISSUE TITLE
IndexOutOfBoundsException from exportClones

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#549]
Hello,

I have a custom reference database containing spliced sequence (i.e. not introns). When running exportClones I hit this error.  I assume the issue is that my reference library lacks an expected segment. I'm reporting the issue in case there is the possibility of more graceful error handling.  Thanks.

```
/home/groups/prime-seq/exacloud/java/current/bin/java \
    -Dmixcr.path=/home/groups/prime-seq/pipeline_tools/bin \
    -Dmixcr.command=mixcr \
    -jar /home/groups/prime-seq/pipeline_tools/bin/mixcr.jar \
    exportClones -c TRA --minimal-clone-count 1 --minimal-clone-fraction 0.1 \
    -cloneId -vHit -dHit -jHit -cHit -aaFeature CDR3 -lengthOf CDR3 \
    -count -fraction -targets -vHits -dHits -jHits -cHits \
    -vGene -vGenes -dGene -dGenes -jGene -jGenes -cGene -cGenes \
    -vBestIdentityPercent -dBestIdentityPercent -jBestIdentityPercent \
    -nFeature CDR3 -qFeature CDR3 -nFeatureImputed VDJRegion \
    -f \
    /home/exacloud/lustre1/prime-seq/workDir/82c4c29f-c826-1037-9ab4-f8f3fc869afb/SequenceA.work/221-3_E3_21826_IE2-AN10_TAPI-0_TNF-Pos_Clone_51/221-3_E3_21826_IE2-AN10_TAPI-0_TNF-Pos_Clone_51.18.rhesus.contigs.clns \
    /home/exacloud/lustre1/prime-seq/workDir/82c4c29f-c826-1037-9ab4-f8f3fc869afb/SequenceA.work/221-3_E3_21826_IE2-AN10_TAPI-0_TNF-Pos_Clone_51/221-3_E3_21826_IE2-AN10_TAPI-0_TNF-Pos_Clone_51.18.rhesus.TRA.mixcr.txt
```

```
03 Oct 2019 11:35:40,613 DEBUG: using path: /home/groups/prime-seq/exacloud/java/current/bin:/home/groups/prime-seq/pipeline_tools/bin/:/home/groups/prime-seq/exacloud/java/current/bin/:/home/groups/prime-seq/pipeline_tools/bin:/usr/local/bin:/usr/bin
03 Oct 2019 11:35:41,948 DEBUG:     Exporting clones: 0%
03 Oct 2019 11:35:41,974 DEBUG:     Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandExport$CommandExportClones@2b491fee): java.lang.IndexOutOfBoundsException
03 Oct 2019 11:35:42,003 DEBUG:         at picocli.CommandLine.execute(CommandLine.java:1004)
03 Oct 2019 11:35:42,018 DEBUG:         at picocli.CommandLine.access$900(CommandLine.java:142)
03 Oct 2019 11:35:42,040 DEBUG:         at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
03 Oct 2019 11:35:42,053 DEBUG:         at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:72)
03 Oct 2019 11:35:42,075 DEBUG:         at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:61)
03 Oct 2019 11:35:42,148 DEBUG:         at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
03 Oct 2019 11:35:42,157 DEBUG:         at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:85)
03 Oct 2019 11:35:42,163 DEBUG:         at com.milaboratory.mixcr.cli.Main.main(Main.java:55)
03 Oct 2019 11:35:42,382 DEBUG:     Caused by: java.lang.IndexOutOfBoundsException
03 Oct 2019 11:35:42,390 DEBUG:         at com.milaboratory.core.sequence.AbstractArraySequence.getRange(AbstractArraySequence.java:63)
03 Oct 2019 11:35:42,432 DEBUG:         at com.milaboratory.mixcr.basictypes.VDJCObject.getIncompleteFeature(VDJCObject.java:580)
03 Oct 2019 11:35:42,441 DEBUG:         at com.milaboratory.mixcr.export.FieldExtractors$15.extractValue(FieldExtractors.java:303)
03 Oct 2019 11:35:42,449 DEBUG:         at com.milaboratory.mixcr.export.FieldExtractors$15.extractValue(FieldExtractors.java:299)
03 Oct 2019 11:35:42,461 DEBUG:         at com.milaboratory.mixcr.export.FieldWithParameters$1.extractValue(FieldWithParameters.java:58)
03 Oct 2019 11:35:42,472 DEBUG:         at com.milaboratory.mixcr.export.InfoWriter.put(InfoWriter.java:83)
03 Oct 2019 11:35:42,487 DEBUG:         at com.milaboratory.mixcr.cli.CommandExport$CommandExportClones$ExportClones.run(CommandExport.java:372)
03 Oct 2019 11:35:42,513 DEBUG:         at com.milaboratory.mixcr.cli.CommandExport$CommandExportClones.run1(CommandExport.java:272)
03 Oct 2019 11:35:42,551 DEBUG:         at com.milaboratory.mixcr.cli.CommandExport.run0(CommandExport.java:169)
03 Oct 2019 11:35:42,582 DEBUG:         at com.milaboratory.cli.ACommand.run(ACommand.java:90)
03 Oct 2019 11:35:42,613 DEBUG:         at picocli.CommandLine.execute(CommandLine.java:996)
```

**Comment by dbolotin** [comment]
Can you please reproduce the problem with [the latest MiXCR version](https://github.com/milaboratory/mixcr/releases/tag/v3.0.10)?

**Comment by bbimber** [comment]
@dbolotin apparently 3.0.10 fixed it.  as you probably saw i was running 3.0.3.  thanks.
