### ISSUE TITLE
java.lang.RuntimeException: and Exception in thread "BasicVDJCAlignmentReaderThread-0" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by decenwang** [milaboratory/mixcr#583]
To whom it may concern,

I got the same three problems again and this time I can help myself. Please see below. Thanks a lot!
[https://github.com/milaboratory/mixcr/issues/546](url),  in issue #546, I also put forward this question. but now I am in this trap again. Now, I only can get the vdjca files. the assembling cannot be performed individually.
**Linux: Unbutu 18.0.4 LTS, in virtualbox ,4G RAM, 4 cores.**
Mixcr version: 3.0.12
java version :
openjdk version "11.0.1-internal" 2018-10-16
But anyway, If I extract 5000 seqs from the orignally large file R1 and R2,respectively,  it can run well.
I am a little bit confused by this magical trouble. because the two files are large, I cannot upload these two files.

1st question:
**java -jar /home/decen/tcr/mixcr-3.0.12/mixcr.jar analyze amplicon --species hsa --starting-material rna --region-of-interest CDR3 --receptor-type TRB --5-end v-primers --3-end j-primers --adapters no-adapters --report ana.report filter_R1_01-1.fq.gz Filter_R2-01-1.fq.gz analysis**
**Alignment: 5.5%
Alignment: 16.6%  ETA: 00:01:15
Alignment: 27.7%  ETA: 00:00:52
Alignment: 38.7%  ETA: 00:00:38
Alignment: 49.8%  ETA: 00:00:31
Alignment: 60.8%  ETA: 00:00:21
Alignment: 71.9%  ETA: 00:00:15
Alignment: 83%  ETA: 00:00:09
Alignment: 94%  ETA: 00:00:03
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandAmplicon@6a2eea2a): java.lang.RuntimeException: While reading fastq record with id=96582 (line number = 386328)
	at picocli.CommandLine.execute(CommandLine.java:1004)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:72)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:61)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:85)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:55)
Caused by: java.lang.RuntimeException: While reading fastq record with id=96582 (line number = 386328)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.take(SingleFastqReader.java:302)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.take(SingleFastqReader.java:35)
	at com.milaboratory.core.io.sequence.AbstractMultiReader.takeReads(AbstractMultiReader.java:52)
	at com.milaboratory.core.io.sequence.PairedReader.take(PairedReader.java:28)
	at com.milaboratory.core.io.sequence.PairedReader.take(PairedReader.java:21)
	at cc.redberry.pipe.util.Chunk.readChunk(Chunk.java:63)
	at cc.redberry.pipe.CUtils$7.take(CUtils.java:323)
	at cc.redberry.pipe.CUtils$7.take(CUtils.java:315)
	at cc.redberry.pipe.blocks.O2ITransmitter.run(O2ITransmitter.java:66)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)
	at com.milaboratory.core.io.sequence.fastq.FastqRecordsReader$1.read(FastqRecordsReader.java:266)
	at com.milaboratory.core.io.sequence.fastq.FastqRecordsReader$InputDataWrapper.readFully(FastqRecordsReader.java:250)
	at com.milaboratory.core.io.sequence.fastq.FastqRecordsReader.fillBuffer(FastqRecordsReader.java:124)
	at com.milaboratory.core.io.sequence.fastq.FastqRecordsReader.nextRecord(FastqRecordsReader.java:170)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.take(SingleFastqReader.java:299)
	... 9 more**

2nd question:
**Analysis time: 30.96s
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandAmplicon@4435047f): java.lang.IllegalStateException: TotalReads count not set.
	at picocli.CommandLine.execute(CommandLine.java:1004)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:72)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:61)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:85)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:55)
Caused by: java.lang.IllegalStateException: TotalReads count not set.
	at com.milaboratory.mixcr.cli.CloneAssemblerReport.writeReport(CloneAssemblerReport.java:230)
	at com.milaboratory.mixcr.cli.Util.writeReportToStdout(Util.java:67)
	at com.milaboratory.mixcr.cli.CommandAssemble.run1(CommandAssemble.java:240)
	at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
	at com.milaboratory.cli.ACommand.run(ACommand.java:90)
	at com.milaboratory.mixcr.cli.CommandAnalyze.run0(CommandAnalyze.java:656)
	at com.milaboratory.cli.ACommand.run(ACommand.java:90)
	at picocli.CommandLine.execute(CommandLine.java:996)
	... 7 more**
3rd question:
**Assembling initial clonotypes: 44.5%  ETA: 00:41:31
Exception in thread "BasicVDJCAlignmentReaderThread-0" java.lang.OutOfMemoryError: Java heap space
	at com.milaboratory.mixcr.basictypes.IO$VDJCHitSerializer.read(IO.java:68)
	at com.milaboratory.mixcr.basictypes.IO$VDJCHitSerializer.read(IO.java:48)
	at com.milaboratory.primitivio.PrimitivI.readObject(PrimitivI.java:105)
	at com.milaboratory.primitivio.DefaultSerializersProviderImpl$ArraySerializer.read(DefaultSerializersProviderImpl.java:330)
	at com.milaboratory.primitivio.PrimitivI.readObject(PrimitivI.java:105)
	at com.milaboratory.mixcr.basictypes.IO$VDJCAlignmentsSerializer.read(IO.java:109)
	at com.milaboratory.mixcr.basictypes.IO$VDJCAlignmentsSerializer.read(IO.java:82)
	at com.milaboratory.primitivio.PrimitivI.readObject(PrimitivI.java:105)
	at com.milaboratory.mixcr.basictypes.AlignmentsIO.readBlock(AlignmentsIO.java:299)
	at com.milaboratory.mixcr.basictypes.BasicVDJCAlignmentReader$DecoderThread.run(BasicVDJCAlignmentReader.java:165)
Assembling initial clonotypes: 44.7%  ETA: 07:31:00
Assembling initial clonotypes: 44.7%
Assembling initial clonotypes: 44.7%
Assembling initial clonotypes: 44.7%
Assembling initial clonotypes: 44.7%**

**Comment by PoslavskySV** [comment]
Hi, 

use `java -jar -Xmx32g ...` to increase memory amount available to MiXCR (replace 32g - 32 gigabytes - with any reasonable value).
