### ISSUE TITLE
IllegalFileFormatException: Too small buffer

### ISSUE THREAD

**Issue by benponv** [milaboratory/mixcr#634]
## Checklist before submitting the issue:

 - [X] The issue is strongly related to the MiXCR software
 - [X] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [X] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [X] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

I tried to run mixcr analyze shotgun on a paired-end WES from NCBI database (Accession no: SRR3928207) using prefetch, validated, then fasterq-dump to 2 files (named SRR3928207.sra_1.fastq and SRR3928207.sra_2.fastq). But there was an error "IllegalFileFormatException: Too small buffer" which I tried to rerun, restart the wsl, but still received the same error.

I use Windows 10 Enterprise Build 19042 and WSL2 with Ubuntu 18.04 and openjdk version "11.0.9.1" while running mixcr version 3.0.13.

## Expected Result

I expected to finish running mixcr as usual (I ran SRR3928207 - SRR3928211 using similar code without any problem).

## Actual Result

> NOTE: report file is not specified, using SRR3928207.vdjca.report to write report.
Alignment: 0%
Alignment: 1.4%  ETA: 02:21:33
Alignment: 2.7%  ETA: 02:30:38
Alignment: 4%  ETA: 02:30:04
Alignment: 5.2%  ETA: 02:32:32
Alignment: 6.4%  ETA: 02:37:52
Alignment: 7.6%  ETA: 02:36:02
Alignment: 8.8%  ETA: 02:29:20
Alignment: 10%  ETA: 02:28:50
Alignment: 11.3%  ETA: 02:19:38
Alignment: 12.5%  ETA: 02:29:20
Alignment: 13.7%  ETA: 02:21:46
Alignment: 14.9%  ETA: 02:22:40
Alignment: 16.2%  ETA: 02:09:46
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandShotgun@4d6f197e): com.milaboratory.core.io.sequence.IllegalFileFormatException: Too small buffer.
        at picocli.CommandLine.execute(CommandLine.java:1004)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:76)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:65)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
        at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:89)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:59)
Caused by: com.milaboratory.core.io.sequence.IllegalFileFormatException: Too small buffer.
        at com.milaboratory.core.io.sequence.fastq.FastqRecordsReader.nextRecord(FastqRecordsReader.java:141)
        at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.take(SingleFastqReader.java:299)
        at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.take(SingleFastqReader.java:35)
        at com.milaboratory.core.io.sequence.AbstractMultiReader.takeReads(AbstractMultiReader.java:52)
        at com.milaboratory.core.io.sequence.PairedReader.take(PairedReader.java:28)
        at com.milaboratory.core.io.sequence.PairedReader.take(PairedReader.java:21)
        at cc.redberry.pipe.util.Chunk.readChunk(Chunk.java:63)
        at cc.redberry.pipe.CUtils$7.take(CUtils.java:323)
        at cc.redberry.pipe.CUtils$7.take(CUtils.java:315)
        at cc.redberry.pipe.blocks.O2ITransmitter.run(O2ITransmitter.java:66)
        at java.base/java.lang.Thread.run(Thread.java:834)

## Exact MiXCR commands 

''mixcr analyze shotgun -s hsa --starting-material dna --receptor-type tcr SRR3928207.sra_1.fastq SRR3928207.sra_2.fastq SRR3928207.vdjca"

## MiXCR report files 

I did not receive any MiXCR report file, only .vdjca file was available.

**Comment by PoslavskySV** [comment]
Hi, 

there are two reasons for this: the file is broken or the read length is far too big. Could you check that fastq files are consistent after `fasterq-dump`? If yes, what is the maximal read length in R1 and R2 ?

**Comment by benponv** [comment]
> Hi,
> 
> there are two reasons for this: the file is broken or the read length is far too big. Could you check that fastq files are consistent after `fasterq-dump`? If yes, what is the maximal read length in R1 and R2 ?

Thank you for your suggestion. I checked the fastq file using fastqc and the file was actually corrupted. I reran fasterq-dump again to get a new fastq and now it worked perfectly. :D
