### ISSUE TITLE
assembleContigs failed to assemble contigs of TRA 

### ISSUE THREAD

**Issue by pinjouwu9325** [milaboratory/mixcr#648]
## Checklist before submitting the issue:

 - [✓] The issue is strongly related to the MiXCR software
 - [✓] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [✓] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [✓] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

I expected to have the assembled contigs of the TRA.

## Actual Result

assembleContigs failed to assemble contigs of the TRA only. It worked well for assembling the TRB. The TCR library was constructed using 5’RACE (A SMARTer approach to T-cell receptor profiling).

## Exact MiXCR commands 

```
SAMPLE_A="LN-TCR-a_S60 SP-TCR-a_S58"
for i in ${SAMPLE_A};
do
    echo ${i}
    ~/tools/mixcr-3.0.13/mixcr analyze amplicon --species mmu \
        --starting-material rna \
        --5-end no-v-primers \
        --3-end c-primers \
        --adapters adapters-present \
        --receptor-type tra \
        --contig-assembly \
        -t 16 \
        --verbose \
        /LVM_data/pinjouwu9325/data/mctq1/TGIA_20210409/9-13-${i}_L001_R1_001.fastq.gz \
        /LVM_data/pinjouwu9325/data/mctq1/TGIA_20210409/9-13-${i}_L001_R2_001.fastq.gz \
        ${i}
done
```
I also tried to do it separately using `~/tools/mixcr-3.0.13/mixcr assembleContigs -t 16 --report report.txt ../LN-TCR-a_S60.clna full_clones.clns 2>&1 | tee assembleContigs.log` but it failed to assembling as well. 

## MiXCR report files 

```
LN-TCR-a_S60
NOTE: report file is not specified, using LN-TCR-a_S60.report to write report.
WARNING: 7 functional genes were excluded, re-run with --verbose option to see the list of excluded genes and exclusion reason.
Alignment: 0.1%
Alignment: 10.3%  ETA: 00:05:00
Alignment: 20.3%  ETA: 00:03:50
Alignment: 30.6%  ETA: 00:03:21
Alignment: 40.7%  ETA: 00:02:50
Alignment: 50.8%  ETA: 00:02:21
Alignment: 61%  ETA: 00:01:51
Alignment: 71.2%  ETA: 00:01:21
Alignment: 81.4%  ETA: 00:00:53
Alignment: 91.6%  ETA: 00:00:24
============= Report ==============
Analysis time: 4.89m
Total sequencing reads: 1099688
Successfully aligned reads: 953271 (86.69%)
Chimeras: 40 (0%)
Paired-end alignment conflicts eliminated: 118763 (10.8%)
Alignment failed, no hits (not TCR/IG?): 121029 (11.01%)
Alignment failed because of absence of V hits: 961 (0.09%)
Alignment failed because of absence of J hits: 23918 (2.17%)
No target with both V and J alignments: 508 (0.05%)
Alignment failed because of low total score: 1 (0%)
Overlapped: 850566 (77.35%)
Overlapped and aligned: 709245 (64.5%)
Alignment-aided overlaps: 59847 (8.44%)
Overlapped and not aligned: 141321 (12.85%)
V gene chimeras: 11467 (1.04%)
J gene chimeras: 5 (0%)
TRA chains: 953218 (99.99%)
TRB chains: 12 (0%)
IGH chains: 1 (0%)
Realigned with forced non-floating bound: 617938 (56.19%)
Realigned with forced non-floating right bound in left read: 144583 (13.15%)
Realigned with forced non-floating left bound in right read: 144583 (13.15%)
Initialization: progress unknown
Assembling initial clonotypes: 8.8%
Assembling initial clonotypes: 20.2%  ETA: 00:00:06
Assembling initial clonotypes: 37.6%  ETA: 00:00:07
Assembling initial clonotypes: 60.6%  ETA: 00:00:03
Assembling initial clonotypes: 74.9%  ETA: 00:00:01
Assembling initial clonotypes: 85.7%  ETA: 00:00:01
Assembling initial clonotypes: 96.8%  ETA: 00:00:00
Mapping low quality reads: 7.1%
Mapping low quality reads: 19.5%  ETA: 00:00:06
Mapping low quality reads: 38.6%  ETA: 00:00:06
Mapping low quality reads: 49.6%  ETA: 00:00:04
Mapping low quality reads: 63.5%  ETA: 00:00:02
Mapping low quality reads: 78.9%  ETA: 00:00:01
Mapping low quality reads: 91.5%  ETA: 00:00:00
Clustering: 0%
Clustering: 10.1%  ETA: 00:03:51
Clustering: 20.4%  ETA: 00:01:17
Clustering: 31.2%  ETA: 00:01:03
Clustering: 42.3%  ETA: 00:00:51
Clustering: 52.5%  ETA: 00:00:42
Clustering: 62.8%  ETA: 00:00:28
Clustering: 73.1%  ETA: 00:00:20
Clustering: 83.9%  ETA: 00:00:10
Clustering: 95%  ETA: 00:00:03
Building clones: 10.1%
Building clones: 23.3%  ETA: 00:00:05
Building clones: 35.9%  ETA: 00:00:05
Building clones: 48.3%  ETA: 00:00:04
Building clones: 69%  ETA: 00:00:02
Building clones: 81.3%  ETA: 00:00:01
Building clones: 97.8%  ETA: 00:00:00
Preparing for sorting: progress unknown
Writing alignments: 0%
============= Report ==============
Writing alignments: 100%  ETA: 00:00:00
Analysis time: 5.75m
Final clonotype count: 169081
Average number of reads per clonotype: 5.23
Reads used in clonotypes, percent of total: 884085 (80.39%)
Reads used in clonotypes before clustering, percent of total: 903986 (82.2%)
Number of reads used as a core, percent of used: 889656 (98.41%)
Mapped low quality reads, percent of used: 14330 (1.59%)
Reads clustered in PCR error correction, percent of used: 19901 (2.2%)
Reads pre-clustered due to the similar VJC-lists, percent of used: 5 (0%)
Reads dropped due to the lack of a clone sequence, percent of total: 38863 (3.53%)
Reads dropped due to low quality, percent of total: 0 (0%)
Reads dropped due to failed mapping, percent of total: 10422 (0.95%)
Reads dropped with low quality clones, percent of total: 0 (0%)
Clonotypes eliminated by PCR error correction: 12102
Clonotypes dropped as low quality: 0
Clonotypes pre-clustered due to the similar VJC-lists: 5
TRA chains: 169062 (99.99%)
TRB chains: 6 (0%)
IGH chains: 1 (0%)
Assembling: 0%
Assembling: 10.4%  ETA: 00:03:53
Assembling: 20.6%  ETA: 00:03:38
Assembling: 30.8%  ETA: 00:03:29
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandAmplicon@1bcbeb59): java.lang.RuntimeException: While processing clone #8825
	at picocli.CommandLine.execute(CommandLine.java:1004)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:76)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:65)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:89)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:59)
Caused by: java.lang.RuntimeException: While processing clone #8825
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:230)
	at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:313)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.<init>(FullSeqAssembler.java:147)
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:199)
	... 2 more
```
I checked the raw alignments and it looked fine to me. 

```
>>> Read ids: 1146


                                                    <5'UTR                                         
                                                                                                   
     Quality    66666777777777777777777777777777777777777777777777777777777777777777777777777777   
     Target0  0 ATATACTAAGCAGTGGTATCAACGCAGAGTACGGGGAGTGTTCTGTGGGAGACAAAAGGTCACCTGAGTTCCCTTCAAGC 79  Score
TRAV14D-1*00 41                                     agtgttctgtgggagacaaaaggtcacctgagttcccttcaagc 84  2115
TRAV14N-1*00 41                                     agtgttctgtgggagacaaaaggtcacctgagttcccttcaagc 84  2115
TRAV14D-2*00 42                                     agtgttctgtgggagacaaaaggCcacctgagttccc-Ccaagc 84  1881
TRAV14N-2*00 42                                     agtgttctgtgggagacaaaaggCcacctgagttccc-Ccaagc 84  1881

                         5'UTR><L1                                              L1><L2              
                                M  D  K  I  L  T  A  T  F  L  L  L  G  L  H  L  A  G  V  N  G  Q    
     Quality    77777777777777777777777777777777777777777777777777777777777777776777777777777777    
     Target0 80 TTCAGTCTAGGAGGAATGGACAAGATCCTGACAGCAACGTTTTTACTCCTAGGCCTTCACCTAGCTGGGGTGAATGGCCA 159  Score
TRAV14D-1*00 85 ttcagtctaggaggaatggacaagatcctgacagcaacgtttttactcctaggccttcacctagctggggtgaatggcca 164  2115
TRAV14N-1*00 85 ttcagtctaggaggaatggacaagatcctgacagcaacgtttttactcctaggccttcacctagctggggtgaatggcca 164  2115
TRAV14D-2*00 85 ttcagtctaggaggaatggacaagatcctgacagcaTcgtttttactcctaggccttcacctagctggggtgaGtggcca 164  1881
TRAV14N-2*00 85 ttcagtctaggaggaatggacaagatcctgacagcaTcgtttttactcctaggccttcacctagctggggtgaGtggcca 164  1881

                                 L2><FR1                                                             
                   Q  Q  E  K  R  D  Q  Q  Q  V  R  Q  S  P  Q  S  L  T  V  W  E  G  E  T  A  I      
     Quality     77777777777777777777777776777744667777777777777777777777777777777777777777631164    
     Target0 160 GCAGCAGGAGAAACGTGACCAGCAGCAGGTGAGACAAAGTCCCCAATCTCTGACAGTCTGGGAAGGAGAGACCGCAATTC 239  Score
TRAV14D-1*00 165 gcagcaggagaaacgtgaccagcagcaggtgagacaaagtccccaatctctgacagtctgggaaggagagaccgcaattc 244  2115
TRAV14N-1*00 165 gcagcaggagaaacgtgaccagcagcaggtgagacaaagtccccaatctctgacagtctgggaaggagagaccgcaattc 244  2115
TRAV14D-2*00 165 gcagcaggagaaacgtgaccagcagcaggtgagacaaagtccccaatctctgacagtctgggaaggagagacAgcaattc 244  1881
TRAV14N-2*00 165 gcagcaggagaaacgtgaccagcagcaggtgagacaaagtccccaatctctgacagtctgggaaggagagacAgcaattc 244  1881

                              FR1><CDR1        CDR1><FR2                                             
                 L  N  C  S  Y  E  D  S  T  F  N  Y  F  P  W  Y  Q  Q  F  P  G  E  G  P  A  L  L     
     Quality     14424454465654463460776777777777677777776677757566436567766777777777777667777777    
     Target0 240 TGAACTGCAGTTATGAGGACAGCACTTTTAACTACTTCCCATGGTACCAGCAGTTCCCTGGGGAAGGCCCTGCACTCCTG 319  Score
TRAV14D-1*00 245 tgaactgcagttatgaggacagcacttttaactacttcccatggtaccagcagttccctggggaaggccctgcactcctg 324  2115
TRAV14N-1*00 245 tgaactgcagttatgaggacagcacttttaactacttcccatggtaccagcagttccctggggaaggccctgcactcctg 324  2115
TRAV14D-2*00 245 tgaactgcagttatgaggacagcacttttGactacttcccatggtacTGgcagttccctAgggaaAgccctgcactcctg 324  1881
TRAV14N-2*00 245 tgaactgcagttatgaggacagcacttttGactacttcccatggtacTGgcagttccctAgggaaAgccctgcactcctg 324  1881

                   FR2><CDR2           CDR2><FR3                                                     
                  I  S  I  R  S  V  S  D  K  K  E  D  G  R  F  T  I  F  F  N  K  R  E  K  K  L  S    
     Quality     77777765767777777777764427777777777777777777777777777777777777777777777777777777    
     Target0 320 ATATCCATACGTTCAGTGTCCGATAAAAAGGAAGATGGACGATTCACAATCTTCTTCAATAAAAGGGAGAAAAAGCTCTC 399  Score
TRAV14D-1*00 325 atatccatacgttcagtgtccgataaaaaggaagatggacgattcacaatcttcttcaataaaagggagaaaaagctctc 404  2115
TRAV14N-1*00 325 atatccatacgttcagtgtccgataaaaaggaagatggacgattcacaatcttcttcaataaaagggagaaaaagctctc 404  2115
TRAV14D-2*00 325 ataGccatacgtCcagtgtccAataaaaaggaagatggacgattcacaatcttcttcaataaaagggagaaaaagctctc 404  1881
TRAV14N-2*00 325 ataGccatacgtCcagtgtccAataaaaaggaagatggacgattcacaatcttcttcaataaaagggagaaaaagctctc 404  1881

                                                           FR3><CDR3      V>   <J                    
                   L  H  I  T  D  S  Q  P  G  D  S  A  T  Y  F  C  A  A  S  G  D  Y  N  Q  G  K      
     Quality     77777777777777777777777777777777777777777777777777777777777777777777777777777777    
     Target0 400 CTTGCACATCACAGACTCTCAGCCTGGAGACTCAGCTACCTACTTCTGTGCAGCAAGTGGCGATTATAACCAGGGGAAGC 479  Score
TRAV14D-1*00 405 cttgcacatcacagactctcagcctggagactcagctacctacttctgtgcagcaagtg                      463  2115
TRAV14N-1*00 405 cttgcacatcacagactctcagcctggagactcagctacctacttctgtgcagcaagtg                      463  2115
TRAV14D-2*00 405 cttgcacatcacagactctcagcctggagactcagctacctacttctgtgcagcaagtg                      463  1881
TRAV14N-2*00 405 cttgcacatcacagactctcagcctggagactcagctacctacttctgtgcagcaagtg                      463  1881
   TRAJ23*00  23                                                               attataaccaggggaagc 40   285

                 CDR3><FR4                       FR4><C                                           
              L  I  F  G  Q  G  T  K  L  S  I  K  P  N  I  Q  N  P  E  P  A  V  Y  Q  L  A  M     
  Quality     77777777777777777777777777677777777777777777777777777777777777777777777777766666    
  Target0 480 TTATCTTTGGACAGGGAACCAAGTTATCTATCAAGCCCAACATCCAGAACCCAGAACCTGCTGTGTACCAGTTAGCCATG 559  Score
TRAJ23*00  41 ttatctttggacagggaaccaagttatctatcaagccca                                          79   285
  TRAC*00   0                                        acatccagaacccagaacctgctgtgtaccagtta       34   175
```

The memory setting for Java is `-Xmx12000m -Xms8000m`.
Thank you.

Regards,
Pin-Jou

**Comment by pinjouwu9325** [comment]
Here is a little update.
I had a look at clone #8825 where the error occurred and I found that its nSeqCDR3 field was missing. 
Also, some clones in the exportClone file did not have the nSeqCDR3 sequence. 
Maybe it is the reason why assembleContig crushed since there is no sequence for MiXCR to assemble contigs. 

## Exact MiXCR commands
`~/tools/mixcr-3.0.13/mixcr exportClones -f ../LN-TCR-a_S60.clna clones.txt`

## MiXCR report files
```
Exporting clones: 0%
Exporting clones: 18.4%  ETA: 00:00:04
Exporting clones: 46.6%  ETA: 00:00:01
Exporting clones: 69.6%  ETA: 00:00:01
Exporting clones: 91.1%  ETA: 00:00:00
```
The output: [clones_top10k.txt](https://github.com/milaboratory/mixcr/files/6322133/clones_top10k.txt)

Thank you.

Best, 
Pin-Jou

**Comment by PoslavskySV** [comment]
Hi,

thanks for reporting. I confirm that this is a bug rarely arising with mmu reference. Already in work, will be fixed in the upcoming release.

**Comment by pinjouwu9325** [comment]
Hi, 

Thanks for the help.
I had also tried to analyse the data by the commands step by step and it worked.
Here is the command: 
```
SAMPLE="LN-TCR-b_S61 SP-TCR-b_S59"

for i in ${SAMPLE};
do
    echo ${i}
# Alignement
    ~/tools/mixcr-3.0.13/mixcr align \
        -t 16 \
        --species mmu \
        --report ${i}.align.txt \
        /LVM_data/pinjouwu9325/data/mctq1/TGIA_20210409/9-13-${i}_L001_R1_001.fastq.gz \
        /LVM_data/pinjouwu9325/data/mctq1/TGIA_20210409/9-13-${i}_L001_R2_001.fastq.gz \
        ${i}.vdjca 2>&1 | tee ${i}.align.log   
# Assemble
    ~/tools/mixcr-3.0.13/mixcr assemble \
        -t 16 \
        --write-alignments \
        --report ${i}.assemble.txt \
        ./${i}.vdjca \
        ${i}.assemble.clna 2>&1 | tee ${i}.assemble.log    
# Assemble full TCR receptor sequences
    ~/tools/mixcr-3.0.13/mixcr assembleContigs \
        -t 16 \
        --report ${i}.assembleContigs.txt \
        ./${i}.assemble.clna \
        ${i}.assembleContigs.clns 2>&1 | tee ${i}.assembleContigs.log
# Export Clones
    ~/tools/mixcr-3.0.13/mixcr exportClones \
        ./${i}.assembleContigs.clns \
        ${i}.exportClones.txt 2>&1 | tee ${i}.exportClones.log
done
```

So I suggested that it may only happen on  `analyze amplicon`.
Thank again for your help and the awesome software.

Best,
Pin-Jou

**Comment by PoslavskySV** [comment]
@pinjouwu9325 Hi Pin-Jou,

we are now working on the fix and it turned out that the bug is more complex and dependent on the data, so it is not trivial to fix. Could you, please, share your raw fastq so we could reproduce the bug? You can send it to us using support@milaboratory.com (of course we will keep it securely).

Thanks!
Stanislav

**Comment by Leena-Abdullah** [comment]
Hi 
I am getting a similar error when I to align CDR1,2 AND 3. I was wondering if there is a way I can fix this.
<img width="821" alt="MIXCR error" src="https://user-images.githubusercontent.com/95719967/145607514-3b2ea1c5-547f-4b7b-bb26-3dafc76e5476.png">

**Comment by Nitin123-4** [comment]
I am also facing the same issue as clone 9001 doesn't have any sequence. I am facing this issue with the Monkey genome.

Any solution for this?

Command error:
  picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAssembleContigs@22cb296a): java.lang.RuntimeException: While processing clone #9001
        at picocli.CommandLine.execute(CommandLine.java:1004)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:87)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:76)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
        at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:100)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:70)
  Caused by: java.lang.RuntimeException: While processing clone #9001
        at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:230)
        at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:313)
        at java.lang.Thread.run(Thread.java:745)
  Caused by: java.lang.NullPointerException
        at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.<init>(FullSeqAssembler.java:147)
        at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:199)
        ... 2 more

**Comment by Nitin123-4** [comment]
Please help with this erro

**Comment by PoslavskySV** [comment]
Hi, we will provide you an updated version in a couple of hours.

**Comment by Nitin123-4** [comment]
Hi vd-dragan21,

Yes, The issue is fixed and working fine for me.

Thanks, PoslavskySV for fixing it.

Please, download it from this link, it should work with Java 8:  

https://s3.amazonaws.com/files.milaboratory.com/mixcr-AJhWd7aqJuivQ2ESgAgH2dn1nWy2iQdL1PQboAFV/mixcr.zip
