### ISSUE TITLE
Failure to assemble

### ISSUE THREAD

**Issue by SoniaWolf149** [milaboratory/mixcr#653]
Had a script in MiXCR that was working well; no issues. Suddenly the assembly stage of the pipeline is not working and outputs error message. All other stages of the pipeline are working to this point. 

Script was:

`mixcr assemble WTCHG_862660_71935265_alignments_rescued_2_extended.vdjca WTCHG_862660_71935265_clones.clns`

Error message

```
OpenJDK 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAssemble@36dce7ed): java.lang.RuntimeException: java.nio.file.AccessDeniedException: /tmp/mixcr_293c0a45eb0f7059e5cc519ea63ed138b65a6f283450071418298199207.tmp
	at picocli.CommandLine.execute(CommandLine.java:1004)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:48)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:31)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:53)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:25)
Caused by: java.lang.RuntimeException: java.nio.file.AccessDeniedException: /tmp/mixcr_293c0a45eb0f7059e5cc519ea63ed138b65a6f283450071418298199207.tmp
	at com.milaboratory.util.TempFileManager.getTempFile(TempFileManager.java:62)
	at com.milaboratory.util.TempFileManager.getTempFile(TempFileManager.java:40)
	at com.milaboratory.mixcr.assembler.AssemblerEventLogger.<init>(AssemblerEventLogger.java:56)
	at com.milaboratory.mixcr.assembler.CloneAssembler.<init>(CloneAssembler.java:104)
	at com.milaboratory.mixcr.cli.CommandAssemble.run1(CommandAssemble.java:147)
	at com.milaboratory.mixcr.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:99)
	at com.milaboratory.mixcr.cli.ACommand.run(ACommand.java:73)
	at picocli.CommandLine.execute(CommandLine.java:996)
	... 7 more
Caused by: java.nio.file.AccessDeniedException: /tmp/mixcr_293c0a45eb0f7059e5cc519ea63ed138b65a6f283450071418298199207.tmp
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.createFile(Files.java:647)
	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:137)
	at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
	at java.base/java.nio.file.Files.createTempFile(Files.java:912)
	at com.milaboratory.util.TempFileManager.getTempFile(TempFileManager.java:54)
	... 14 more
```

I'm running this on a university HPC; I have tried with both the conda mixcr and the mixcr.jar file and get the same error message. 

Wondering if this is something to do with java as I installed some other software last week- my java version is 

openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)

**Comment by PoslavskySV** [comment]
Hi,

according to the error message, this is due to your cluster setup: MiXCR uses system-provided `tmp` dir for intermediate storage, and it is not available or too oftenly cleaned up in your HPC. I think your cluster administrators will know how to fix or overcome this.
