### ISSUE TITLE
Alignment fail at 82% multiple times (String index out of range: -16)

### ISSUE THREAD

**Issue by mehdiborji** [milaboratory/mixcr#668]
I have a relatively large fastq file (~30m single end long read, 48GB uncompressed). I have used MixCR successfully on subsets of the same input file. However when I try to use it on the whole library I keep getting this error exactly at around %82:
``` 
Alignment: 81.8%  ETA: 00:24:35
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAlign@1c80e49b): java.lang.StringIndexOutOfBoundsException: String index out of range: -16
        at picocli.CommandLine.execute(CommandLine.java:1004)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:76)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:65)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
        at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:89)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:59)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -16
        at java.lang.String.checkBounds(String.java:381)
        at java.lang.String.<init>(String.java:545)
        at com.milaboratory.core.io.sequence.SingleReadLazy.createNSequenceWithQuality(SingleReadLazy.java:109)
        at com.milaboratory.core.io.sequence.SingleReadLazy.getData(SingleReadLazy.java:96)
        at com.milaboratory.mixcr.vdjaligners.VDJCAligner.hash(VDJCAligner.java:75)
        at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:87)
        at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:49)
        at cc.redberry.pipe.CUtils$9.process(CUtils.java:350)
        at cc.redberry.pipe.CUtils$9.process(CUtils.java:345)
        at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:313)
        at java.lang.Thread.run(Thread.java:748)
```
The command that I used is as follows:
`mixcr align -r sample.txt -s hsa -t 8 -OsaveOriginalReads=true  sample.fastq sample.vdjca -f`

I don't have any memory or space issues and it fails exactly at the same spot!

Any help is appreciated!

**Comment by PoslavskySV** [comment]
Hi, it looks like you have a very long sequence inside your fastq file - MiXCR doesn't support reads longer than 32,767 bp. A possible workaround right now is to truncate reads in your file like:

```
cat sample.fastq | cut -c -32000 > sample_truncated.fastq
```

**Comment by mehdiborji** [comment]
Thank you so much! This solution worked for me! For truncating I used `awk` like here: `https://www.biostars.org/p/66996/`
