### ISSUE TITLE
Unable to run IMGT library with mouse

### ISSUE THREAD

**Issue by NiketPatel9** [milaboratory/mixcr#687]
Hello, I was unsure if this is being worked on by the folks at IMGT, but I am trying to align a FASTQ file by using the IMGT library as a reference for my mouse species. I am able to run the following command without fail, but when I add the --library imgt tag, I am getting the following error:

```
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAlign@44828f6b): java.lang.RuntimeException: Can't find library for following library name and species: imgt + mmu
        at picocli.CommandLine.execute(CommandLine.java:1004)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:76)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:65)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
        at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:89)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:59)
        at com.milaboratory.mixcr.cli.Main1.main(Main1.java:61)
Caused by: java.lang.RuntimeException: Can't find library for following library name and species: imgt + mmu
        at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:395)
        at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:293)
        at com.milaboratory.mixcr.cli.CommandAlign.getLibrary(CommandAlign.java:274)
        at com.milaboratory.mixcr.cli.CommandAlign.getAlignerParameters(CommandAlign.java:230)
        at com.milaboratory.mixcr.cli.CommandAlign.run1(CommandAlign.java:412)
        at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
        at com.milaboratory.cli.ACommand.run(ACommand.java:90)
        at picocli.CommandLine.execute(CommandLine.java:996)
```

Here is the command that I ran:
``
java -jar /n/groups/lab/user/mixcr-3.0.13/mixcr.jar  align --library imgt --species mmu umicollapse/HT1_cell_1_umicollapse.fastq vdjca/HT1_cell_1_imgt.vdjca
``

I am loading in the following version of java
```module load java/jdk-11.0.11``` (I am on Slurm)

Also, my libraries structure within the mixcr-3.0.13 folder has the latest IMGT JSON file inside (mixcr-3.0.13/libraries/imgt.202141-1.sv7.json)

Thank you for any help you can provide.

**Comment by NiketPatel9** [comment]
Edit: I figured it out, running it with the jar file does not seem to work, but running it with the other exectuable file (mixcr) allows it to search in the libraries file within the MiXCR folder where my JSON file it.
