### ISSUE TITLE
assembleContigs error 

### ISSUE THREAD

**Issue by juliatjwang** [milaboratory/mixcr#695]
## Checklist before submitting the issue:

 - [X] The issue is strongly related to the MiXCR software
 - [X] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [X] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [X] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

Assembly of contigs - I am running Mixcr on 3' scRNAseq (10X) following the workflow described here: https://github.com/milaboratory/mixcr/wiki/Analysis-of-10X-Single-Cell-data 

Prior to the assembleContigs step, all steps ran fine (report for the immediately prior 'assemble' step below) 

## Actual Result

```
Assembling contigs: 0%
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAssembleContigs@62a8fd44): java.lang.RuntimeException: While processing clone #49
	at picocli.CommandLine.executeUserObject(CommandLine.java:1778)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:140)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:129)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:151)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:123)
Caused by: java.lang.RuntimeException: While processing clone #49
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:231)
	at cc.redberry.pipe.CUtils$Indexed.process(CUtils.java:67)
	at cc.redberry.pipe.CUtils.lambda$orderedParallelProcessor$1(CUtils.java:96)
	at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:305)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.IllegalStateException: random access primitivI blocks or primitivI reader not closed
		at com.milaboratory.primitivio.blocks.PrimitivIHybrid.checkNullState(PrimitivIHybrid.java:174)
		at com.milaboratory.primitivio.blocks.PrimitivIHybrid.close(PrimitivIHybrid.java:285)
		at com.milaboratory.mixcr.basictypes.ClnAReader.close(ClnAReader.java:364)
		at com.milaboratory.mixcr.cli.CommandAssembleContigs.run1(CommandAssembleContigs.java:242)
		at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
		at com.milaboratory.cli.ACommand.run(ACommand.java:100)
		at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
		at picocli.CommandLine.access$900(CommandLine.java:145)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
		at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:140)
		at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:129)
		at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
		at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:151)
		at com.milaboratory.mixcr.cli.Main.main(Main.java:123)
Caused by: java.lang.IndexOutOfBoundsException
	at com.milaboratory.core.alignment.BandedMatrix.defined(BandedMatrix.java:134)
	at com.milaboratory.core.alignment.BandedMatrix.get(BandedMatrix.java:121)
	at com.milaboratory.core.alignment.BandedAffineAligner.semiGlobalRight0(BandedAffineAligner.java:377)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.alignAffineSeq1FromLeft(FullSeqAssembler.java:1067)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.alignSeq1FromLeft(FullSeqAssembler.java:1002)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.buildClone(FullSeqAssembler.java:866)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.lambda$callVariants$1(FullSeqAssembler.java:290)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.callVariants(FullSeqAssembler.java:291)
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:229)
	... 4 more
```

## Exact MiXCR commands 

`mixcr -Xmx300g assembleContigs --force-overwrite -OalignedRegionsOnly=true clones.clna clones.clns`
Also tried: `mixcr -Xmx300g assembleContigs --force-overwrite clones.clna clones.clns`

## MiXCR report files 

``` 
============= Report ==============
Analysis time: 10.71m
Number of input groups: 9263786
Number of input alignments: 25422082
Number of output pre-clonotypes: 11071
Number of clonotypes per group
  1: + 10933 (99.41%) = 10933 (99.41%)
  2: + 58 (0.53%) = 10991 (99.94%)
  3: + 6 (0.05%) = 10997 (99.99%)
  4: + 1 (0.01%) = 10998 (100%)
Number of core alignments: 17478 (0.07%)
Discarded core alignments: 14 (0.08%)
Empirically assigned alignments: 9809 (0.04%)
Empirical assignment conflicts: 0 (0%)
UMI+VJ-gene empirically assigned alignments: 8851 (0.03%)
VJ-gene empirically assigned alignments: 0 (0%)
UMI empirically assigned alignments: 958 (0%)
Number of ambiguous UMIs: 65
Number of ambiguous V-genes: 71
Number of ambiguous J-genes: 56
Number of ambiguous UMI+V/J-gene combinations: 127
Unassigned alignments: 1118 (0%)
Final clonotype count: 1181
Average number of reads per clonotype: 22.26
Reads used in clonotypes, percent of total: 26286 (0.01%)
Reads used in clonotypes before clustering, percent of total: 26468 (0.01%)
Number of reads used as a core, percent of used: 25783 (97.41%)
Mapped low quality reads, percent of used: 685 (2.59%)
Reads clustered in PCR error correction, percent of used: 182 (0.69%)
Reads pre-clustered due to the similar VJC-lists, percent of used: 0 (0%)
Reads dropped due to the lack of a clone sequence, percent of total: 5 (0%)
Reads dropped due to low quality, percent of total: 0 (0%)
Reads dropped due to failed mapping, percent of total: 1091 (0%)
Reads dropped with low quality clones, percent of total: 0 (0%)
Clonotypes eliminated by PCR error correction: 49
Clonotypes dropped as low quality: 0
Clonotypes pre-clustered due to the similar VJC-lists: 0
Clonotypes dropped in fine filtering: 0
Partially aligned reads attached to clones by tags: 0 (0%)
Partially aligned reads with ambiguous clone attachments by tags: 0 (0%)
Partially aligned reads failed to attach to clones by tags: 0 (0%)
TRA chains: 28 (2.37%)
TRB chains: 18 (1.52%)
TRD chains: 3 (0.25%)
TRG chains: 55 (4.66%)
IGH chains: 404 (34.21%)
IGK chains: 355 (30.06%)
IGL chains: 318 (26.93%)
```

Alignment files (.vdjca) appear correctly formatted. I realize that very few alignments may be expected from 3'-scRNAseq, but I'd like to confirm whether this is causing the error I'm seeing, as it is hard to tell based on the error message and report alone.

I've also attached the output of `mixcr exportClones -f clones.clna > clones_clna.txt`
[clones_clna.txt](https://github.com/milaboratory/mixcr/files/8895892/clones_clna.txt)

**Comment by dbolotin** [comment]
Please try using `-p rna-seq` instead of `-p kaligner2` on the align step. It should both give you better results for not-enriched  scRNASeq data, and fix the bug you encountered here.

**Comment by juliatjwang** [comment]
Thank you so much, this solution worked :)!
