### ISSUE TITLE
assembleContigs error in scRNA data 

### ISSUE THREAD

**Issue by FsheriF** [milaboratory/mixcr#718]
##Description:

Hi MiXCR team, thanks for releasing the amazing MiXCR v4.0.0. I have encountered an error when running a scRNA example to compare with the TRUST4 result.

MiXCR version: newly released v4.0.0, https://github.com/milaboratory/mixcr/releases/tag/v4.0.0
scRNA data SRA: SRR14481962, downloaded using SRA tool kit `fastq-dump --split-files SRR14481962 --gzip`

## Expected Result

I strictly followed the code posted in https://github.com/milaboratory/mixcr/wiki/Analysis-of-10X-Single-Cell-data

## Actual Result

The process of align, correctAndSortTags, assemblePartial and assemble were all fine and formed the clones.clna file. When go through the process `/mixcr-4.0.0/mixcr assembleContigs ./clones.clna ./clones.clns`, an error message showed like:
"Assembling contigs: 0%
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAssembleContigs@2f879bab): java.lang.RuntimeException: While processing clone #57
	at picocli.CommandLine.executeUserObject(CommandLine.java:1778)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:140)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:129)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:151)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:123)
Caused by: java.lang.RuntimeException: While processing clone #57
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:231)
	at cc.redberry.pipe.CUtils$Indexed.process(CUtils.java:67)
	at cc.redberry.pipe.CUtils.lambda$orderedParallelProcessor$1(CUtils.java:96)
	at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:305)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: java.lang.IllegalStateException: random access primitivI blocks or primitivI reader not closed
		at com.milaboratory.primitivio.blocks.PrimitivIHybrid.checkNullState(PrimitivIHybrid.java:174)
		at com.milaboratory.primitivio.blocks.PrimitivIHybrid.close(PrimitivIHybrid.java:285)
		at com.milaboratory.mixcr.basictypes.ClnAReader.close(ClnAReader.java:364)
		at com.milaboratory.mixcr.cli.CommandAssembleContigs.run1(CommandAssembleContigs.java:242)
		at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
		at com.milaboratory.cli.ACommand.run(ACommand.java:100)
		at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
		at picocli.CommandLine.access$900(CommandLine.java:145)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
		at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:140)
		at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:129)
		at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
		at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:151)
		at com.milaboratory.mixcr.cli.Main.main(Main.java:123)
Caused by: java.lang.IndexOutOfBoundsException
	at com.milaboratory.core.alignment.BandedMatrix.defined(BandedMatrix.java:134)
	at com.milaboratory.core.alignment.BandedMatrix.get(BandedMatrix.java:121)
	at com.milaboratory.core.alignment.BandedAffineAligner.semiGlobalRight0(BandedAffineAligner.java:377)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.alignAffineSeq1FromLeft(FullSeqAssembler.java:1067)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.alignSeq1FromLeft(FullSeqAssembler.java:1002)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.buildClone(FullSeqAssembler.java:866)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.lambda$callVariants$1(FullSeqAssembler.java:290)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.callVariants(FullSeqAssembler.java:291)
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:229)
	... 4 more
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandExport$CommandExportClones@623a8092): java.lang.RuntimeException: Unsupported file type
	at picocli.CommandLine.executeUserObject(CommandLine.java:1778)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:140)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:129)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:151)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:123)
Caused by: java.lang.RuntimeException: Unsupported file type
	at com.milaboratory.mixcr.basictypes.CloneSetIO.read(CloneSetIO.java:41)
	at com.milaboratory.mixcr.basictypes.CloneSetIO.read(CloneSetIO.java:35)
	at com.milaboratory.mixcr.cli.CommandExport$CommandExportClones.run1(CommandExport.java:225)
	at com.milaboratory.mixcr.cli.CommandExport.run0(CommandExport.java:148)
	at com.milaboratory.cli.ACommand.run(ACommand.java:100)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	... 7 more
"

## Exact MiXCR commands 

`/mixcr-4.0.0/mixcr align --tag-pattern '^(CELL:N{16})(UMI:N{10})\^(R2:*)' -p kaligner2 -s hs -OvParameters.geneFeatureToAlign=VTranscript -OvParameters.parameters.floatingLeftBound=false -OjParameters.parameters.floatingRightBound=false -OcParameters.parameters.floatingRightBound=false -OallowPartialAlignments=true -OallowNoCDR3PartAlignments=true --report align.report ./SRR14481962_1.fastq.gz ./SRR14481962_2.fastq.gz ./alignments.vdjca`

`/mixcr-4.0.0/mixcr correctAndSortTags ./alignments.vdjca ./alignments.corrected.vdjca`

`/mixcr-4.0.0/mixcr assemblePartial ./alignments.corrected.vdjca ./alignments.partial.assemble.vdjca`

`/mixcr-4.0.0/mixcr assemble  -a ./alignments.partial.assemble.vdjca ./clones.clna`

`/mixcr-4.0.0/mixcr assembleContigs ./clones.clna ./clones.clns`

**Comment by Meletian** [comment]
I met the same problem when analyzing bulk bcr-seq of assembling contigs.

**Comment by PoslavskySV** [comment]
Hi guys, 

we know about the problem and will fix it soon. Meanwhile, you can use `-p rna-seq` instead of `-p kAligner2` and that should work, though this may lead in a loose of some long indels in case of BCR analyis.

**Comment by PoslavskySV** [comment]
Resolved in [MiXCR v4.1](https://github.com/milaboratory/mixcr/releases/tag/v4.1.0)
