### ISSUE TITLE
assembleContigs: Error while running command 

### ISSUE THREAD

**Issue by sheljoy** [milaboratory/mixcr#727]
```bash
mixcr  analyze amplicon \
--threads 32 \
--species mmu  --starting-material dna \
--5-end no-v-primers --3-end j-primers \
--adapters no-adapters \
--receptor-type bcr  --contig-assembly  --region-of-interest VDJRegion  --only-productive \
--assemble "-OassemblingFeatures=[FR1,CDR1,FR2,CDR2,FR3,CDR3,FR4]" \
--export "-p full" --export "-cloneId"  --export "-c IG" \
--report xxxx.report \
xxxx_1.fq.gz.paried_clean_1.fq.gz \
xxxx_2.fq.gz.paried_clean_2.fq.gz \
xxxx
```

analysis the BCR-seq  clean data with `contig-assembly`,  how to solve the isssue:

picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandAmplicon@516c20de): java.lang.RuntimeException: While processing clone #29
        at picocli.CommandLine.executeUserObject(CommandLine.java:1778)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:140)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:129)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
        at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:151)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:123)
Caused by: java.lang.RuntimeException: While processing clone #29
        at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:231)
        at cc.redberry.pipe.CUtils$Indexed.process(CUtils.java:67)
        at cc.redberry.pipe.CUtils.lambda$orderedParallelProcessor$1(CUtils.java:96)
        at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:305)
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: java.lang.IllegalStateException: random access primitivI blocks or primitivI reader not closed
                at com.milaboratory.primitivio.blocks.PrimitivIHybrid.checkNullState(PrimitivIHybrid.java:174)
                at com.milaboratory.primitivio.blocks.PrimitivIHybrid.close(PrimitivIHybrid.java:285)
                at com.milaboratory.mixcr.basictypes.ClnAReader.close(ClnAReader.java:364)
                at com.milaboratory.mixcr.cli.CommandAssembleContigs.run1(CommandAssembleContigs.java:242)
                at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
                at com.milaboratory.cli.ACommand.run(ACommand.java:100)
                at com.milaboratory.mixcr.cli.CommandAnalyze.run0(CommandAnalyze.java:690)
                at com.milaboratory.cli.ACommand.run(ACommand.java:100)
                at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
                at picocli.CommandLine.access$900(CommandLine.java:145)
                at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
                at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:140)
                at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:129)
                at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
                at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:151)
                at com.milaboratory.mixcr.cli.Main.main(Main.java:123)
Caused by: java.lang.NullPointerException
        at io.repseq.core.SequencePartitioning.isAvailable(SequencePartitioning.java:62)
        at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.checkGeneCompatibility(FullSeqAssembler.java:1947)
        at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$null$1(CommandAssembleContigs.java:153)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$null$3(CommandAssembleContigs.java:154)
        at java.base/java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1666)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:147)
        ... 4 more

**Comment by PoslavskySV** [comment]
Hi,

this:
```
-OassemblingFeatures=[FR1,CDR1,FR2,CDR2,FR3,CDR3,FR4]
```

is a syntax for disjoint features. So instead of this, please use:

```
-OassemblingFeatures={FR1Begin:FR4End}
```

Other examples: https://docs.milaboratories.com/mixcr/reference/ref-gene-features/
