### ISSUE TITLE
Can't run mixcr 4 with the external reference

### ISSUE THREAD

**Issue by f6v** [milaboratory/mixcr#728]
Hi,

I was running mixcr 3 with the IMGT reference like so:
```
mixcr analyze amplicon     --species mmu     --starting-material rna     --5-end no-v-primers     --3-end c-primers     --adapters no-adapters     --library imgt     --threads 8     --only-productive     30581-004.1_R1.fastq.gz 30581-004.1_R2.fastq.gz 30581-004.1
```

After switching to mixcr 4, I get an error:

```
 picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandAmplicon@64c2b546): java.lang.RuntimeException: Can't find library for following library name and species: imgt + mmu
  	at picocli.CommandLine.executeUserObject(CommandLine.java:1778)
  	at picocli.CommandLine.access$900(CommandLine.java:145)
  	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
  	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:84)
  	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:73)
  Causedat picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
  	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:95)
  	at com.milaboratory.mixcr.cli.Main.main(Main.java:67)
  Caused by: java.lang.RuntimeException: Can't find library for following library name and species: imgt + mmu
  	at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:395)
  	at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:293)
  	at com.milaboratory.mixcr.cli.CommandAlign.getLibrary(CommandAlign.java:318)
  	at com.milaboratory.mixcr.cli.CommandAlign.getAlignerParameters(CommandAlign.java:274)
  	at com.milaboratory.mixcr.cli.CommandAlign.run1(CommandAlign.java:554)
  	at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
  	at com.milaboratory.cli.ACommand.run(ACommand.java:100)
  	at com.milaboratory.mixcr.cli.CommandAnalyze.run0(CommandAnalyze.java:667)
  	at com.milaboratory.cli.ACommand.run(ACommand.java:100)
  rk dirat picocli.CommandLine.executeUserObject(CommandLine.java:1769)
```

The library file is in the library search path. I get the error by only switching between the mixcr versions. Do I have to adjust for the mixcr 4?

**Comment by PoslavskySV** [comment]
Hi,

can you try most recent IMGT library available here: https://github.com/repseqio/library-imgt/releases

Let me know if it works.

**Comment by f6v** [comment]
Thanks for getting back to me!

I've tried the latest library, but it still doesn't work.

**Comment by Alex-Davydov** [comment]
Hi,
Can you run `mixcr -v` for both version and attach the output here

**Comment by zmyyy3** [comment]
Hi, 
Thank you for developing such powerful software. I met the same problem. I'm using the latest version MiXCR 4.0.0. 
Here is the output after running `mixcr -v`

> MiXCR v4.0.0b (built Wed Jul 06 18:14:53 EDT 2022; rev=8050699050; branch=400b; host=Dmitrys-MacBook-Pro-2.local)
>
>RepSeq.IO v1.4.0 (rev=8ad610d516)
>MiLib v2.0.0 (rev=ee6396596d)
>Built-in V/D/J/C library: repseqio.v2.0
>
>Library search path:
>- built-in libraries
>- /scratch/mzhang11/MiXCR/result/.
>
Thank you in advance for your help.

**Comment by Alex-Davydov** [comment]
Hi,
Try to put the imgt library in result folder (/scratch/mzhang11/MiXCR/result/.)

**Comment by zmyyy3** [comment]
Hi,
Thank you so much for the quick respone! It works now.

**Comment by f6v** [comment]
@Alex-Davydov that kind of works. I'm running `mixcr` inside a `Nextflow` pipeline, so I have to copy the IMGT `json` file inside a process working directory.
