### ISSUE TITLE
Error while running postanalysis ?

### ISSUE THREAD

**Issue by Gaut1993** [milaboratory/mixcr#730]
Hello, 

I'm trying to run postanalysis for the first time and I'm having errors that I can't even understand. 
Unfortunately,  I have not been able to find any solutions. 

**Here is my command line :**

mixcr postanalysis individual     --metadata metadata.tsv     --only-productive     --default-downsampling count-reads-auto     test.clns     pa/i.pa.json.gz

**Here is the output error :**

picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.postanalysis.CommandPaIndividual@4482469c): java.lang.RuntimeException: java.nio.charset.MalformedInputException: Input length = 1
	at picocli.CommandLine.executeUserObject(CommandLine.java:1778)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:84)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:73)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:95)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:67)
Caused by: java.lang.RuntimeException: java.nio.charset.MalformedInputException: Input length = 1
	at com.milaboratory.mixcr.cli.postanalysis.CommandPa.metadata(CommandPa.java:216)
	at com.milaboratory.mixcr.cli.postanalysis.CommandPa.validate(CommandPa.java:160)
	at com.milaboratory.cli.ACommand.run(ACommand.java:93)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	... 7 more
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:352)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3399)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3436)
	at com.milaboratory.mixcr.cli.postanalysis.CommandPa.metadata(CommandPa.java:214)
	... 10 more

I would greately appreciate some help. Thank you.

**Comment by PoslavskySV** [comment]
Hi,

can you send us a message to support@milaboratories.com ? We will provide you instructions how to fix this.
