### ISSUE TITLE
Feature to align does not work with IMGT reference

### ISSUE THREAD

**Issue by peterch405** [milaboratory/mixcr#76]
Using this `-OvParameters.geneFeatureToAlign=VGene` with `--library local` produces the following error

`Exception in thread "main" java.lang.NullPointerException
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerPVFirst.createInitialHelper(VDJCAlignerPVFirst.java:127)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerPVFirst.createInitialHelpers(VDJCAlignerPVFirst.java:122)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerPVFirst.process(VDJCAlignerPVFirst.java:58)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerWithMerge.process(VDJCAlignerWithMerge.java:86)
	at com.milaboratory.mixcr.vdjaligners.VDJCAlignerWithMerge.process(VDJCAlignerWithMerge.java:42)
	at cc.redberry.pipe.CUtils$9.process(CUtils.java:350)
	at cc.redberry.pipe.CUtils$9.process(CUtils.java:345)
	at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:304)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by dbolotin** [comment]
Please post full command line. It seems that you are using wrong species name.

**Comment by dbolotin** [comment]
Sorry, previous comment was wrong. The problem is that IMGT reference does't have VGene feature. It neither have 5'UTR nor Intron sequence.

Please see http://mixcr.readthedocs.org/en/latest/geneFeatures.html for more information on gene feature names used in MiXCR.

Absence of this vital information was the main reason to compose our own reference based on genome sequence with. Another reason was the fact that there are several sequence errors in IMGT genes. This paper covers some of problems: http://www.ncbi.nlm.nih.gov/pubmed/18040280

Thanks for reporting this problem, I will add human readable error message for such cases.
