### ISSUE TITLE
Failure to assembleContigs

### ISSUE THREAD

**Issue by robbinxiaochen** [milaboratory/mixcr#762]
Hi, I have used Mixcr multiple times, but never met the problem before.  Now, I am sticking to this.
I am running it in a private HPC with 256G memory, it would be very appreciated if I could get some help here.
Thanks!

Script was:

`mixcr assembleContigs \
--report .//03.AssembleContigs/RNA_REP_22062102_S6_assembleContig_report.txt      \
       .//02.Assemble/RNA_REP_22062102_S6_clones.clna .//03.AssembleContigs/RNA_REP_22062102_S6_full_clones.clns -f      \
             >> .//RNA_REP_22062102_S6.log`

Error message is:

`picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAssembleContigs@1950e8a6): java.lang.RuntimeException: While processing clone #108
	at picocli.CommandLine.executeUserObject(CommandLine.java:1778)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:84)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:73)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:95)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:67)
Caused by: java.lang.RuntimeException: While processing clone #108
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:231)
	at cc.redberry.pipe.CUtils$Indexed.process(CUtils.java:67)
	at cc.redberry.pipe.CUtils.lambda$orderedParallelProcessor$1(CUtils.java:96)
	at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:305)
	at java.lang.Thread.run(Thread.java:750)
	Suppressed: java.lang.IllegalStateException: random access primitivI blocks or primitivI reader not closed
		at com.milaboratory.primitivio.blocks.PrimitivIHybrid.checkNullState(PrimitivIHybrid.java:174)
		at com.milaboratory.primitivio.blocks.PrimitivIHybrid.close(PrimitivIHybrid.java:285)
		at com.milaboratory.mixcr.basictypes.ClnAReader.close(ClnAReader.java:364)
		at com.milaboratory.mixcr.cli.CommandAssembleContigs.run1(CommandAssembleContigs.java:242)
		at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
		at com.milaboratory.cli.ACommand.run(ACommand.java:100)
		at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
		at picocli.CommandLine.access$900(CommandLine.java:145)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
		at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:84)
		at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:73)
		at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
		at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:95)
		at com.milaboratory.mixcr.cli.Main.main(Main.java:67)
Caused by: java.lang.IndexOutOfBoundsException
	at com.milaboratory.core.alignment.BandedMatrix.defined(BandedMatrix.java:134)
	at com.milaboratory.core.alignment.BandedMatrix.get(BandedMatrix.java:121)
	at com.milaboratory.core.alignment.BandedAffineAligner.semiGlobalRight0(BandedAffineAligner.java:377)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.alignAffineSeq1FromLeft(FullSeqAssembler.java:1067)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.alignSeq1FromLeft(FullSeqAssembler.java:1002)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.buildClone(FullSeqAssembler.java:866)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.lambda$callVariants$1(FullSeqAssembler.java:290)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.callVariants(FullSeqAssembler.java:291)
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:229)
	... 4 more`

**Comment by PoslavskySV** [comment]
Hi! Which version of MiXCR you have?

**Comment by PoslavskySV** [comment]
And can you share clna file with us to reproduce the error?

**Comment by robbinxiaochen** [comment]
> Hi! Which version of MiXCR you have?

Hi, I was using Mixcr-4.0.0 then met this error. And today I changed back to Mixcr-3.0.13, it works well. The .clna file is around 5.0G, If you want it, I can find a way to transfer it. 

Thank you so much for the reply!

**Comment by PoslavskySV** [comment]
Resolved in [MiXCR v4.1](https://github.com/milaboratory/mixcr/releases/tag/v4.1.0)
