### ISSUE TITLE
cell umi pattern

### ISSUE THREAD

**Issue by 0x1orz** [milaboratory/mixcr#781]
for the umi pattern  `"^(CELL:N{12})(UMI:N{6})(R1:*)"` , it raise the following  error in 4.0.0-68-developer  with analyze pipeline  while it works in 4.0.0 `align` subcommand :
```plainttext
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandAmplicon@658c5a19): java.lang.IllegalArgumentException: UMI pattern can't contain cell barcodes.
	at picocli.CommandLine.executeUserObject(CommandLine.java:1778)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:83)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:72)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:94)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:66)
Caused by: java.lang.IllegalArgumentException: UMI pattern can't contain cell barcodes.
	at com.milaboratory.mixcr.cli.CommandAnalyze$CommandAmplicon.pipelineSpecificAlignParameters(CommandAnalyze.java:866)
	at com.milaboratory.mixcr.cli.CommandAnalyze.mkAlign(CommandAnalyze.java:410)
	at com.milaboratory.mixcr.cli.CommandAnalyze.getAlign(CommandAnalyze.java:327)
	at com.milaboratory.mixcr.cli.CommandAnalyze.run0(CommandAnalyze.java:696)
	at com.milaboratory.cli.ACommand.run(ACommand.java:112)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	... 7 more
```

**Comment by mizraelson** [comment]
Hi, `mixcr analyze amplicon` command doesn't support `CELL` barcodes. In the approaching `v4.1` there will be a specialized pipeline way to work with single-cell data. Before that, please use distinct `mixcr` commands. Let me know if you need help with that.

**Comment by PoslavskySV** [comment]
These all been fixed in and significantly improved in [MiXCR v4.1](https://github.com/milaboratory/mixcr/releases/tag/v4.1.0). Please, use e.g.
```
mixcr analyze 10x-vdj-tcr --species hsa r1.fq.gz r2.fq.gz result
```
