### ISSUE TITLE
java.lang.NullPointerException using assemble with -index option

### ISSUE THREAD

**Issue by weshorton** [milaboratory/mixcr#85]
#### System
java version 1.7.0_101
mixcr version 1.7.1

#### Commands
`usr/bin/java -Xmx15g -jar /path/to/mixcr-1.7.1/mixcr.jar align -f --loci TRB --species mmu --save-description --save-reads --report /path/to/report.txt /path/to/fastq /path/to/align.vdjca`

`usr/bin/java -Xmx15g -jar /path/to/mixcr-1.7.1/mixcr.jar assemble -f --index /path/to/index.txt --report /path/to/report.txt --threads 4 /path/to/align.vdjca /path/to/assemble.clns`

#### Description
I'm running the mixcr align-assemble-export pipeline on 170 samples of mouse T-Cell Receptor beta data. Samples were created using a multiplex PCR reaction to amplify all 20 V and 13 J genes within this locus. Using the pipeline without the index step works just fine for all samples, it's when we attempt to add the `-index [index file]` option that we get the issue.

The error occurs for 8 of the 170 files, but which 8 vary between runs.

##### Trial 1
1. Run **mixcr align** (no errors) and **mixcr assemble**

     A) Receive two errors from assemble (Samples 146 and 167)
2. Using same vdjca files, re-run **mixcr assemble** for samples 146 and 167

     A) Did this 10 times for each sample

          i) receive same error message 10 of 10 times for sample 146
          ii) receive same error message 10 of 10 times for sample 167

##### Trial 2
1. Run **mixcr align** (no errors) and **mixcr assemble**

     A) Receive four errors from assemble (Samples 1, 29, 86, 95, 145, 167) 
2. Using the same vdjca files, re-run **mixcr assemble** for samples 1, 29, 86, 95, 145, 167

     A) Did this 10 times for each sample - receive same error message 10 of 10 times for all 6

##### Trial 3
1. Run **mixcr align** (no errors) and **mixcr assemble**
     A) Receive three errors from assemble (Samples 95, 146, 167)
2. Re-run **mixcr align** for error samples 10 times
3. Re-run **mixcr assemble** for the outputs of part 2.

     A) For the 10 replicates of sample 95 - 5 produced error
     B) For the 10 replicates of sample 146 - 3 produced error
     C) For the 10 replicates of sample 167 - 7 produced error

#### Stack Trace of Error
`Exception in thread "main" java.lang.NullPointerException
	at com.milaboratory.mixcr.assembler.IO.write0(IO.java:122)
	at com.milaboratory.mixcr.assembler.IO.access$000(IO.java:45)
	at com.milaboratory.mixcr.assembler.IO$ReadToCloneMappingBtreeSerializer.serialize(IO.java:81)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:385)
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:288)
	at org.mapdb.Store.serialize(Store.java:154)
	at org.mapdb.StoreDirect.put(StoreDirect.java:365)
	at org.mapdb.Caches$HashTable.put(Caches.java:216)
	at org.mapdb.Pump.buildTreeMap(Pump.java:470)
	at org.mapdb.DB.createTreeSet(DB.java:1072)
	at org.mapdb.DB$BTreeSetMaker.make(DB.java:749)
	at com.milaboratory.mixcr.cli.ActionAssemble.go(ActionAssemble.java:125)
	at com.milaboratory.mitools.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:145)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:64)`

#### Interpretation
To me it looks like there is an issue with saving reads in the **align** step, but one that does not trigger any error. It only shows when the **assemble** step is run and tries map the read IDs into the index file.

**Comment by PoslavskySV** [comment]
The issue seems to be with this line of code: https://github.com/milaboratory/mixcr/blob/develop/src/main/java/com/milaboratory/mixcr/util/TempFileManager.java#L59 . At some conditions (when running e.g. two same files simultaneously) `RandomUtil.getThreadLocalRandomData ` may produce similar names for tmp files (used to store `ReadToCloneMapping`) so different MiXCR processes will write to the same single file. The fix will be included in version 1.7.4.

**Comment by mimisikai** [comment]
Similar problem as:

F:\MUX4446\2017_01_13_15_38_00_981\RMM592>java -Xmx4g -Xms3g -jar C:\Users\jhou\
Downloads\mixcr-2.1.1\mixcr.jar align -s mmu -r alignmentReport_RMM592.txt RMM59
2_MS001-PE-R00400_L001_R1.fastq.gz RMM592_MS001-PE-R00400_L001_R2.fastq.gz align
ments_RMM592.vdjca
Reference library: repseqio.v1.2:10090 (9a1b61eb20896bbb44a5d38d9359107b)
WARNING: Functional gene IGKV8-23-1*00 doesn't contain full VRegionWithP (exclud
ed)
WARNING: ... 7 more functional genes excluded due to absent "featureToAlign".
Alignment: 0.1%
Alignment: 9.4%  ETA: 00:19:31
Exception in thread "main" java.lang.NullPointerException
        at com.milaboratory.mixcr.vdjaligners.VDJCAlignerPVFirst.process0(VDJCAl
ignerPVFirst.java:97)
        at com.milaboratory.mixcr.vdjaligners.VDJCAlignerPVFirst.process0(VDJCAl
ignerPVFirst.java:55)
        at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.ja
va:74)
        at com.milaboratory.mixcr.vdjaligners.VDJCAlignerWithMerge.process0(VDJC
AlignerWithMerge.java:86)
        at com.milaboratory.mixcr.vdjaligners.VDJCAlignerWithMerge.process0(VDJC
AlignerWithMerge.java:42)
        at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.ja
va:74)
        at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.ja
va:44)
        at cc.redberry.pipe.CUtils$9.process(CUtils.java:350)
        at cc.redberry.pipe.CUtils$9.process(CUtils.java:345)
        at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcesso
r.java:304)
        at java.lang.Thread.run(Unknown Source)
