### ISSUE TITLE
The newest version of mixcr

### ISSUE THREAD

**Issue by MaryGoAround** [milaboratory/mixcr#851]
Hi

I was following your page to install 4.1 version but I get error

```
fi1d18@-Server2:/data/mixcr$ wget https://github.com/milaboratory/mixcr/releases/download/v4.1.0/mixcr-4.1.0.zip
--2022-10-30 21:29:55--  https://github.com/milaboratory/mixcr/releases/download/v4.1.0/mixcr-4.1.0.zip
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-30 21:29:56 ERROR 404: Not Found.
```

https://docs.milaboratories.com/mixcr/getting-started/installation/#manual-installation

Thanks for any idea to see where I make a mistake

**Comment by PoslavskySV** [comment]
Apologies, this is issue with GitHub, it deleted the release, we will fix this within couple of hours. Meanwhile, please use this link:

https://cdn.milaboratory.com/software/mixcr/mixcr-4.1.0-852d9d8feb46d9ce03460e6fbf0439887ed86233.zip

**Comment by MaryGoAround** [comment]
Thanks a lot

I have 10x 5' GEX, TCR and BCR for PBMC

I started mixcr with my BCR fastq files and I got this

```
fi1d18@Server2:/data/mixcr1$ unzip mixcr-4.1.0-852d9d8feb46d9ce03460e6fbf0439887ed86233.zip
Archive:  mixcr-4.1.0-852d9d8feb46d9ce03460e6fbf0439887ed86233.zip
  inflating: mixcr                   
  inflating: LICENSE                 
  inflating: mixcr.jar               
fi1d18@Server2:/data/mixcr1$ mixcr -v
MiXCR v3.0.13 (built Wed Apr 15 16:28:14 BST 2020; rev=f614226; branch=release/v3.0.13; host=Dmitrys-MacBook-Pro.local)
RepSeq.IO v1.3.4 (rev=073c079)
MiLib v1.13 (rev=f8fd717)
Built-in V/D/J/C library: repseqio.v1.6

Library search path:
- built-in libraries
- /data/Continuum/Angel/mixcr1/.
- /usr/local/mixcr-3.0.13/libraries
fi1d18@Server2:/data/mixcr1$ mixcr analyze 10x-vdj-bcr --species hsa --rna /data/Continuum/PN0340_0001_BCR_S2_L001_R1_001.fastq.gz /data/Continuum/PN0340_0001_BCR_S2_L001_R2_001.fastq.gz sample_result
Unmatched arguments: 10x-vdj-bcr, --species, hsa, --rna, /data/PN0340_0001_BCR_S2_L001_R1_001.fastq.gz, /data/PN0340_0001_BCR_S2_L001_R2_001.fastq.gz, sample_result
Usage: mixcr analyze [COMMAND]
Run full MiXCR pipeline for specific input.
Commands:
  help      Displays help information about the specified command
  amplicon  Analyze targeted TCR/IG library amplification (5'RACE, Amplicon, Multiplex, etc).
  shotgun   Analyze random-fragmented data (like RNA-Seq, Exome-Seq, etc). This pipeline assumes
              the data contain no adapter / primer sequences. Adapter trimming must be performed
              for the data containing any artificial sequence parts (e.g. single-cell /
              molecular-barcoded data).
```
Please, do you know what is going wrong here?

Thanks once more

**Comment by mizraelson** [comment]
Hi, it seems that you have an older MiXCR version installed and in your $PATH.

When you run:

`fi1d18@Server2:/data/mixcr1$ mixcr -v`

You don't run the MiXCR from the file, but the one you have in the $PATH.

To use the file you have downloaded run it like that:

`fi1d18@Server2:/data/mixcr1$ ./mixcr -v`

The output should be v4.1 instead of v3.0.13

Also, there is no need to pass '--rna' because 10x preset already includes that parameter.

**Comment by MaryGoAround** [comment]
Thanks a lot

That gives
```

fi1d18@Server2:/data/mixcr$ ./mixcr -v
=== No License ===

To use MiXCR, please, provide a valid license.

If you already have a license, activate it by calling:
  mixcr activate-license

You can also activate the license via a special file, environment
variable or other means, please check the docs at
  https://github.com/milaboratory/mixcr/wiki/Using-license

Academic users can quickly get a license at
  https://licensing.milaboratories.com.

Commercial trial license may be requested at
  https://licensing.milaboratories.com
or by email to
  licensing@milaboratories.com.
```

**Comment by mizraelson** [comment]
That's correct, since MiXCR v4.0 we started using licensing. Thé licence is free for academic use. If that is your case please fill the form on:

https://licensing.milaboratories.com

You can also read about obtaining and using the licence on our new documentation portal:

https://docs.milaboratories.com/mixcr/getting-started/milm/

**Comment by MaryGoAround** [comment]
Thanks a lot

I got this red errors

```
Writing result: 0%
Writing result: 10.6%  ETA: 00:02:49
Writing result: 20.9%  ETA: 00:04:06
picocli.CommandLine$ExecutionException: Error while running command refineTagsAndSort java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
	at com.milaboratory.mixcr.cli.Main.mkCmd$lambda-21(Main.kt:318)
	at picocli.CommandLine.execute(CommandLine.java:2088)
	at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(CommandAnalyze.kt:223)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(MiXCRCommand.kt:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.milaboratory.mixcr.cli.Main.main(Main.kt:77)
Caused by: java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
	at com.milaboratory.primitivio.blocks.PrimitivIOBlocksAbstract.checkException(PrimitivIOBlocksAbstract.java:88)
	at com.milaboratory.primitivio.blocks.PrimitivIBlocks$Reader.close(PrimitivIBlocks.java:628)
	at com.milaboratory.util.sorting.HashSorter$Collator$2.close(HashSorter.java:554)
	at com.milaboratory.util.sorting.HashSorter$Collator$2.take(HashSorter.java:539)
	at cc.redberry.pipe.CUtils$OPIterator.hasNext(CUtils.java:489)
	at com.milaboratory.util.sorting.HashSorter$Collator.getPortForBucket(HashSorter.java:606)
	at com.milaboratory.util.sorting.HashSorter$Collator$4.take(HashSorter.java:663)
	at cc.redberry.pipe.util.CountingOutputPort.take(CountingOutputPort.java:42)
	at cc.redberry.pipe.CUtils$OPIterator.hasNext(CUtils.java:489)
	at com.milaboratory.primitivio.PritmitivIExtesionsKt.forEach(PritmitivIExtesions.kt:228)
	at com.milaboratory.mixcr.cli.CommandRefineTagsAndSort$Cmd.run0(CommandRefineTagsAndSort.kt:397)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(MiXCRCommand.kt:42)
	at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run(MiXCRCommandWithOutputs.kt:67)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	... 11 more
	Suppressed: java.lang.IllegalStateException: Footer not set
		at com.milaboratory.mixcr.basictypes.VDJCAlignmentsWriter.close(VDJCAlignmentsWriter.java:196)
		at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:64)
		at com.milaboratory.mixcr.cli.CommandRefineTagsAndSort$Cmd.run0(CommandRefineTagsAndSort.kt:339)
		... 21 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.milaboratory.primitivio.blocks.PrimitivIBlocks.deserializeBlock(PrimitivIBlocks.java:174)
	at com.milaboratory.primitivio.blocks.PrimitivIBlocks.access$600(PrimitivIBlocks.java:54)
	at com.milaboratory.primitivio.blocks.PrimitivIBlocks$Reader$2.completed(PrimitivIBlocks.java:492)
	at com.milaboratory.primitivio.blocks.PrimitivIBlocks$Reader$2.completed(PrimitivIBlocks.java:459)
	at com.milaboratory.util.io.AsynchronousFileChannelAdapter$CompletionHandlerAdapter.completed(AsynchronousFileChannelAdapter.java:163)
	at com.milaboratory.util.io.AsynchronousFileChannelAdapter$CompletionHandlerAdapter.completed(AsynchronousFileChannelAdapter.java:152)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.SimpleAsynchronousFileChannelImpl$2.run(SimpleAsynchronousFileChannelImpl.java:335)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
====================
Running:
mixcr assemblePartial --report ./sample_result.assemblePartial.report.txt --json-report ./sample_result.assemblePartial.report.json ./sample_result.refined.vdjca ./sample_result.passembled.1.vdjca
picocli.CommandLine$ExecutionException: Error while running command assemblePartial java.io.IOException: Malformed file, END_MAGIC mismatch.
	at com.milaboratory.mixcr.cli.Main.mkCmd$lambda-21(Main.kt:318)
	at picocli.CommandLine.execute(CommandLine.java:2088)
	at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(CommandAnalyze.kt:223)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(MiXCRCommand.kt:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.milaboratory.mixcr.cli.Main.main(Main.kt:77)
Caused by: java.io.IOException: Malformed file, END_MAGIC mismatch.
	at com.milaboratory.mixcr.basictypes.VDJCAlignmentsReader.<init>(VDJCAlignmentsReader.java:121)
	at com.milaboratory.mixcr.basictypes.VDJCAlignmentsReader.<init>(VDJCAlignmentsReader.java:108)
	at com.milaboratory.mixcr.basictypes.VDJCAlignmentsReader.<init>(VDJCAlignmentsReader.java:104)
	at com.milaboratory.mixcr.basictypes.VDJCAlignmentsReader.<init>(VDJCAlignmentsReader.java:100)
	at com.milaboratory.mixcr.basictypes.VDJCAlignmentsReader.<init>(VDJCAlignmentsReader.java:96)
	at com.milaboratory.mixcr.cli.CommandAssemblePartial$Cmd.run0(CommandAssemblePartial.kt:130)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(MiXCRCommand.kt:42)
	at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run(MiXCRCommandWithOutputs.kt:67)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	... 11 more
====================
Running:
mixcr assemble --report ./sample_result.assemble.report.txt --json-report ./sample_result.assemble.report.json ./sample_result.passembled.1.vdjca ./sample_result.clna
ERROR: input file "./sample_result.passembled.1.vdjca" does not exist.
====================
Running:
mixcr assembleContigs --report ./sample_result.assembleContigs.report.txt --json-report ./sample_result.assembleContigs.report.json ./sample_result.clna ./sample_result.contigs.clns
ERROR: input file "./sample_result.clna" does not exist.
====================
Running:
mixcr exportClones ./sample_result.contigs.clns ./sample_result.clones.tsv
ERROR: input file "./sample_result.contigs.clns" does not exist.
fi1d18@Server2:/data/mixcr$ 
```
Any idea please?

**Comment by mizraelson** [comment]
This indicates the lack of memory for the task. You can provide memory by using '-Xmx'.

E.g:
`mixcr -Xmx50G analyze...`


The amount of memory you allocate for the task should be compatible with you system.

**Comment by MaryGoAround** [comment]
Thanks a lot, BCR kit run finished successfully


```
- field: "-aaFeature"
    args:
      - "CDR2"
  - field: "-aaFeature"
    args:
      - "FR3"
  - field: "-aaFeature"
    args:
      - "CDR3"
  - field: "-aaFeature"
    args:
      - "FR4"
  - field: "-defaultAnchorPoints"
====================
Exporting 
Exporting clones: 0%

```

Am I doing correctly for my `10x genomic TCR kit` please? Any argument should be added to the preset for TCR?

`fi1d18@RBGO-Server2:/data/mixcr$ ./mixcr -Xmx50G analyze 10x-vdj-tcr --species hsa /data/PN0340_0001_TCR_S1_L001_R1_001.fastq.gz /data/PN0340_0001_TCR_S1_L001_R2_001.fastq.gz tcr_result
`
