### ISSUE TITLE
FindAlleles with NullPointerException error

### ISSUE THREAD

**Issue by HantaoLou** [milaboratory/mixcr#862]
## Expected Result
I typed in:  mixcr findAlleles --output-template home/user/result_test.clns                                                            
 home/user/result_test.contigs.clns  which I expected to return the new clns file with alleles info but it returned with error.

## Actual Result

Stopped at searching for V alleles: 19% with error

## Exact MiXCR commands 

mixcr findAlleles --output-template home/user/result_test.clns                                                            
 home/user/result_test.contigs.clns

## MiXCR report files 

Grouping by the same J gene: 0%
Searching for J alleles: 32.5%  ETA: 00:00:02
Searching for V alleles: 19%
picocli.CommandLine$ExecutionException: Error while running command findAlleles java.lang.NullPointerException
        at com.milaboratory.mixcr.cli.Main.mkCmd$lambda-21(Main.kt:318)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.Main.main(Main.kt:77)
Caused by: java.lang.NullPointerException
        at com.milaboratory.mixcr.alleles.CloneRebuild$Companion.alignmentsChange(CloneRebuild.kt:181)
        at com.milaboratory.mixcr.alleles.CloneRebuild$Companion.alignmentsChange$default(CloneRebuild.kt:172)
        at com.milaboratory.mixcr.alleles.AllelesBuilder$findAlleles$cloneDescriptors$1.invoke(AllelesBuilder.kt:144)
        at com.milaboratory.mixcr.alleles.AllelesBuilder$findAlleles$cloneDescriptors$1.invoke(AllelesBuilder.kt:136)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
        at com.milaboratory.mixcr.alleles.AllelesBuilder.findAlleles(AllelesBuilder.kt:154)
        at com.milaboratory.mixcr.alleles.AllelesBuilder.access$findAlleles(AllelesBuilder.kt:69)
        at com.milaboratory.mixcr.alleles.AllelesBuilder$searchForAlleles$1$3$1.invoke(AllelesBuilder.kt:113)
        at com.milaboratory.mixcr.alleles.AllelesBuilder$searchForAlleles$1$3$1.invoke(AllelesBuilder.kt:111)
        at com.milaboratory.primitivio.PritmitivIExtesionsKt.mapInParallel$lambda-4(PritmitivIExtesions.kt:115)
        at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:305)
        at java.lang.Thread.run(Thread.java:750)

**Comment by gnefedev** [comment]
Thanks for reporting. I will look at this issue on Monday and let you know about the results.

**Comment by gnefedev** [comment]
I fixed this issue, it will be included in version 4.1.1

Meanwhile. you can download dev version with the fix by this link:
https://link.milaboratory.com/software/mixcr/mixcr-develop.zip
