### ISSUE TITLE
issue with alignment 10x bcr 

### ISSUE THREAD

**Issue by mariafrancesca21** [milaboratory/mixcr#888]
Hi!
I downloaded yesterday the new version (4.1.1), I was using v1.3 until yesterday but I decided to update it because I have some single cell data with a tag for each cell that I need to preserve after the alignment.
I'm running this to align 

mixcr align --species hsa -p 10x-vdj-bcr *.fasta alignments.vdjca

and then I planned to do the export clones with -tag so that I can read the tag, but I have some issues and I cannot align. I have just one fasta file that is made like this: 
>tag
seq in nucl 
>tag
seq in nucl .... 

this is the output:

The following tags and their roles were recognised:
Payload tags: R2
Cell tags: CELL
Molecule tags: UMI
Alignment: 0%
picocli.CommandLine$ExecutionException: Error while running command align java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at com.milaboratory.mixcr.cli.Main.mkCmd$lambda-21(Main.kt:322)
at picocli.CommandLine.execute(CommandLine.java:2088)
at com.milaboratory.mixcr.cli.Main.main(Main.kt:76)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.base/java.util.Collections$SingletonList.get(Collections.java:4849)
at com.milaboratory.mitool.pattern.search.ReadSearchHit.getReadProjection(ReadSearch.kt:75)
at com.milaboratory.mitool.pattern.search.MicRecord$getTagValue$2.getBaseSequenceProjection(ReadSearch.kt:108)
at com.milaboratory.mitool.pattern.search.MicRecord$getTagValue$2.getValue(ReadSearch.kt:114)
at com.milaboratory.mixcr.cli.CommandAlign$Cmd$TagsExtractor.parse(CommandAlign.kt:1207)
at com.milaboratory.mixcr.cli.CommandAlign$Cmd$run0$1$step0$1.invoke(CommandAlign.kt:887)
at com.milaboratory.mixcr.cli.CommandAlign$Cmd$run0$1$step0$1.invoke(CommandAlign.kt:886)
at com.milaboratory.mitool.helpers.PipeKt.mapUnchunked$lambda-5(Pipe.kt:44)
at cc.redberry.pipe.CUtils$9.process(CUtils.java:403)
at cc.redberry.pipe.CUtils$9.process(CUtils.java:398)
at cc.redberry.pipe.util.SimpleProcessorWrapper.take(SimpleProcessorWrapper.java:44)
at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:303)
at java.base/java.lang.Thread.run(Thread.java:829)
Suppressed: java.lang.IllegalStateException: Footer not set
at com.milaboratory.mixcr.basictypes.VDJCAlignmentsWriter.close(VDJCAlignmentsWriter.java:196)
at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:64)
at com.milaboratory.mixcr.cli.CommandAlign$Cmd.run0(CommandAlign.kt:1300)
at com.milaboratory.mixcr.cli.MiXCRCommand.run(MiXCRCommand.kt:42)
at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run(MiXCRCommandWithOutputs.kt:67)
at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
at picocli.CommandLine.access$1300(CommandLine.java:145)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
at picocli.CommandLine.execute(CommandLine.java:2078)
at com.milaboratory.mixcr.cli.Main.main(Main.kt:76)

P.S. if you also have some suggestions to preserve the tag in a different way I'll be glad. Thank you in advance.

**Comment by PoslavskySV** [comment]
Hi Maria,

do you have the raw fastq files? For the command you used, you should supply raw fastq (R1+R2) files to MiXCR. See how 10x Genomics preset works here:

https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/#10xgenomics

**Comment by mariafrancesca21** [comment]
No, unfortunately I don't have it. I just have the already aligned fasta
file but I need mixcr to separate V J gene and CDR3.

Best,
Maria Francesca

Il giorno mar 15 nov 2022 alle ore 12:14 Stanislav Poslavsky <
***@***.***> ha scritto:

**Comment by PoslavskySV** [comment]
I'm not sure I understand what you need. What is the structure of sequences in your .fasta file? primers/adapters/barcodes etc... It seems that you pre-processed somehow the raw data.

**Comment by Alex-Davydov** [comment]
Hi Maria,
It seems your `fasta` file looks like `filtered_contigs.fasta` from Cell Ranger output. Am I right? If so you can run MiXCR in the following way:
`mixcr align -p legacy-4.0-kAligner2 -s hs -OsaveOriginalReads=true -f your_fasta.fasta alignments.vdjca`
`mixcr assemble -a -f --assemble-clonotypes-by VDJRegion alignments.vdjca clones.clna`
`mixcr exportAlignments -descrsR1 -cloneId -f clones.clna alignments.tsv`
In the final `tsv` file you will get alignments result for all aligned sequences from your fasta file with corresponding sequence id (fasta header) and clone id.

**Comment by mariafrancesca21** [comment]
Thank you very much, it worked.

Best,
Maria Francesca

Il giorno gio 17 nov 2022 alle ore 03:03 Alex-Davydov <
***@***.***> ha scritto:

**Comment by PoslavskySV** [comment]
@Alex-Davydov  thank you for helping! @mariafrancesca21 please, keep in mind that with MiXCR 4.x you can run the whole 10x pipeline (as well as [many other](https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/) pipelines for commercial kits) with one analyze command. We will be happy to organize a dedicated training session for MiXCR series 4.x for you and your team. Reach us at support@milaboratories.com if interested.
