### ISSUE TITLE
Align with VGene, then assemble VTranscript -> Exception

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#90]
```
Exception in thread "main" java.lang.IllegalArgumentException
at com.milaboratory.mixcr.reference.GeneFeature.intersection0(GeneFeature.java:422)
at com.milaboratory.mixcr.reference.GeneFeature.intersection(GeneFeature.java:363)
at com.milaboratory.mixcr.cli.ActionAssemble.go(ActionAssemble.java:100)
at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:145)
at com.milaboratory.mixcr.cli.Main.main(Main.java:65)
```

**Comment by PoslavskySV** [comment]
Exception in thread "main" java.lang.IllegalArgumentException
	at com.milaboratory.mixcr.reference.GeneFeature.intersection0(GeneFeature.java:422)
	at com.milaboratory.mixcr.reference.GeneFeature.intersection(GeneFeature.java:363)
	at com.milaboratory.mixcr.cli.ActionAssemble.go(ActionAssemble.java:100)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:145)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:65)
