### ISSUE TITLE
Error in assemblePartial  java.lang.NullPointerException

### ISSUE THREAD

**Issue by juliaed** [milaboratory/mixcr#911]
## Expected Result

Hi, 
Could you help me with an issue with mixcr v 4.1.2 ? I have launched a mixcr analyze pipeline on exome sequencing data with the following command

## Exact MiXCR commands 
```
 mixcr analyze exom-full-length \
      --species hsa \
        $R1_file \
        $R2_file \
        $sample
```

## Actual Result

The align command ran well with a .vdjca output that is correct. However the assemblePartial command does not run and I get the following error.

## Error : 
```
picocli.CommandLine$ExecutionException: Error while running command assemblePartial java.lang.NullPointerException
        at com.milaboratory.mixcr.cli.Main.mkCmd$lambda-21(Main.kt:323)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.Main.main(Main.kt:76)
Caused by: java.lang.NullPointerException
        at com.milaboratory.mixcr.partialassembler.PartialAlignmentsAssemblerAligner.process0(PartialAlignmentsAssemblerAligner.java:293)
        at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:69)
        at com.milaboratory.mixcr.partialassembler.PartialAlignmentsAssembler.searchOverlaps(PartialAlignmentsAssembler.java:165)
        at com.milaboratory.mixcr.cli.CommandAssemblePartial$Cmd.run0(CommandAssemblePartial.kt:186)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(MiXCRCommand.kt:42)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run(MiXCRCommandWithOutputs.kt:67)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 1 more
        Suppressed: java.lang.IllegalStateException: Footer not set
                at com.milaboratory.mixcr.basictypes.VDJCAlignmentsWriter.close(VDJCAlignmentsWriter.java:198)
                at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:64)
                at com.milaboratory.mixcr.cli.CommandAssemblePartial$Cmd.run0(CommandAssemblePartial.kt:141)
                ... 11 more
```

## Full output of the analyze pipeline :
```
====================
Running:
mixcr align --report ./10SL.align.report.txt --json-report ./10SL.align.report.json --preset exom-full-length --species hsa /sps/sallegen/edith/raw_data/10SL_1.fastq.gz /sps/sallegen/edith/raw_data/10SL_2.fastq.gz ./10SL.vdjca
Alignment: 0%
Alignment: 0.4%  ETA: 07:47:17
Alignment: 0.8%  ETA: 08:30:28
Alignment: 1.2%  ETA: 08:53:43
.....
Alignment: 98.3%  ETA: 00:09:25
Alignment: 98.7%  ETA: 00:07:57
Alignment: 99.1%  ETA: 00:04:49
Alignment: 99.4%  ETA: 00:03:03
Alignment: 99.8%  ETA: 00:01:03
============== Align Report ==============
Analysis time: 547.3m
Total sequencing reads: 74663642
Successfully aligned reads: 55433 (0.07%)
Paired-end alignment conflicts eliminated: 260 (0%)
Alignment failed, no hits (not TCR/IG?): 72589161 (97.22%)
Alignment failed because of absence of CDR3 parts: 870549 (1.17%)
Alignment failed because of low total score: 1148499 (1.54%)
Overlapped: 58188929 (77.93%)
Overlapped and aligned: 41131 (0.06%)
Alignment-aided overlaps: 1778 (4.32%)
Overlapped and not aligned: 58147798 (77.88%)
No CDR3 parts alignments, percent of successfully aligned: 1310 (2.36%)
Partial aligned reads, percent of successfully aligned: 53895 (97.23%)
V gene chimeras: 556 (0%)
J gene chimeras: 259 (0%)
TRA chains: 5199 (9.38%)
TRA non-functional: 7 (0.13%)
TRB chains: 7955 (14.35%)
TRB non-functional: 5 (0.06%)
TRD chains: 79 (0.14%)
TRD non-functional: 0 (0%)
TRG chains: 1145 (2.07%)
TRG non-functional: 70 (6.11%)
IGH chains: 17094 (30.84%)
IGH non-functional: 0 (0%)
TRAD chains: 2820 (5.09%)
TRAD non-functional: 0 (0%)
IGK chains: 12230 (22.06%)
IGK non-functional: 0 (0%)
IGL chains: 8911 (16.08%)
IGL non-functional: 0 (0%)
Realigned with forced non-floating bound: 32952982 (44.14%)
Realigned with forced non-floating right bound in left read: 28959 (0.04%)
Realigned with forced non-floating left bound in right read: 28959 (0.04%)
====================
Running:
mixcr assemblePartial --report ./10SL.assemblePartial.report.txt --json-report ./10SL.assemblePartial.report.json ./10SL.vdjca ./10SL.passembled.1.vdjca
Building index: 0%
Searching for overlaps: 0%

picocli.CommandLine$ExecutionException: Error while running command assemblePartial java.lang.NullPointerException
        at com.milaboratory.mixcr.cli.Main.mkCmd$lambda-21(Main.kt:323)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.Main.main(Main.kt:76)
Caused by: java.lang.NullPointerException
        at com.milaboratory.mixcr.partialassembler.PartialAlignmentsAssemblerAligner.process0(PartialAlignmentsAssemblerAligner.java:293)
        at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:69)
        at com.milaboratory.mixcr.partialassembler.PartialAlignmentsAssembler.searchOverlaps(PartialAlignmentsAssembler.java:165)
        at com.milaboratory.mixcr.cli.CommandAssemblePartial$Cmd.run0(CommandAssemblePartial.kt:186)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(MiXCRCommand.kt:42)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run(MiXCRCommandWithOutputs.kt:67)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 1 more
        Suppressed: java.lang.IllegalStateException: Footer not set
                at com.milaboratory.mixcr.basictypes.VDJCAlignmentsWriter.close(VDJCAlignmentsWriter.java:198)
                at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:64)
                at com.milaboratory.mixcr.cli.CommandAssemblePartial$Cmd.run0(CommandAssemblePartial.kt:141)
                ... 11 more
```

**Comment by dbolotin** [comment]
Hi! Thanks for reporting! This is a bug, I will fix it soon, and share the pre-release version with a fix.

**Comment by dbolotin** [comment]
Hi, I fixed the error, please try development build of mixcr. You can install it using one of the following ways:
 - zip https://cdn.milaboratory.com/software/mixcr/mixcr-4.1.2-23-develop-c8f1fd34f90dbb4e3ce8ae3d0b86f8296930d046.zip
 - docker `com.milaboratory:mixcr:4.1.2-23-develop`
 - or development conda repository `conda install -c milaboratories mixcr-dev`

**Comment by juliaed** [comment]
Hi, the new development version  works well. Thank you !
