### ISSUE TITLE
A problem with AssemblePartial  while running the Nextera FLex-tagmented DNA data

### ISSUE THREAD

**Issue by MarzenaWojtaszewska** [milaboratory/mixcr#937]
## Checklist before submitting the issue:

 - [v ] The issue is strongly related to the MiXCR software
 - [ v] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [ v] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ v] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

While working with Nextera FLex DNA fastq data for IGHV  I run the preset exom-full-length as most well suited (IMO) to align and assemble  randomly fragmented tagmented sequences (as far as I know there are no other presets adequate for the task).
I am using: 
mixcr analyze exom-full-length --species hsa input/{{a}}_{{R}}_L{{n}}.fastq.gz output/001
I want to proces the data through tasks: align, AssemblePartial, assembleContigs and ExportClones to get the full consesus sequences and % of the clones for clonality and SHM analyses.

## Actual Result
The presets runs succesfully throug align and then it stops on the AssemblePartial.

*A description of what actually happened*

When I manually run my samples through align and the AssemblePartial I get the same error, however I can successfully assemble the data with plain assemble command. 
It happens only with IGHV fastq files with high read amounts (eg. 50k-70k), the whole preset runs well on poorly sequenced samples with eg. 5k reads.

## Exact MiXCR commands 

'mixcr analyze exom-full-length --species hsa input/{{a}}_{{R}}_L{{n}}.fastq.gz output/001'

## MiXCR report files 

```====================
Running:
mixcr align --report output\001.align.report.txt --json-report output\001.align.report.json --preset exom-full-length --species hsa input\{{a}}_{{R}}_L{{n}}.fastq.gz output\001.vdjca
Alignment: 0%
Alignment: 15,1%  ETA: 00:00:05
Alignment: 30,2%  ETA: 00:00:09
Alignment: 45,3%  ETA: 00:00:25
============== Align Report ==============
Analysis time: 53,7s
Total sequencing reads: 99996
Successfully aligned reads: 23664 (23,66%)
Paired-end alignment conflicts eliminated: 46 (0,05%)
Alignment failed, no hits (not TCR/IG?): 40329 (40,33%)
Alignment failed because of absence of CDR3 parts: 29851 (29,85%)
Alignment failed because of low total score: 6152 (6,15%)
Overlapped: 97957 (97,96%)
Overlapped and aligned: 23554 (23,55%)
Alignment-aided overlaps: 162 (0,69%)
Overlapped and not aligned: 74403 (74,41%)
No CDR3 parts alignments, percent of successfully aligned: 760 (3,21%)
Partial aligned reads, percent of successfully aligned: 13602 (57,48%)
V gene chimeras: 1 (0%)
IGH chains: 23664 (100%)
IGH non-functional: 60 (0,25%)
Realigned with forced non-floating bound: 4402 (4,4%)
Realigned with forced non-floating right bound in left read: 129 (0,13%)
Realigned with forced non-floating left bound in right read: 129 (0,13%)
====================
Running:
mixcr assemblePartial --report output\001.assemblePartial.report.txt --json-report output\001.assemblePartial.report.json output\001.vdjca output\001.passembled.1.vdjca
Building index: 0%
Searching for overlaps: 0%
picocli.CommandLine$ExecutionException: Error while running command assemblePartial java.lang.NullPointerException
        at com.milaboratory.mixcr.cli.Main.mkCmd$lambda-21(Main.kt:323)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(CommandAnalyze.kt:285)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(MiXCRCommand.kt:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.milaboratory.mixcr.cli.Main.main(Main.kt:76)
Caused by: java.lang.NullPointerException
        at com.milaboratory.mixcr.partialassembler.PartialAlignmentsAssemblerAligner.process0(PartialAlignmentsAssemblerAligner.java:293)
        at com.milaboratory.mixcr.vdjaligners.VDJCAligner.process(VDJCAligner.java:69)
        at com.milaboratory.mixcr.partialassembler.PartialAlignmentsAssembler.searchOverlaps(PartialAlignmentsAssembler.java:165)
        at com.milaboratory.mixcr.cli.CommandAssemblePartial$Cmd.run0(CommandAssemblePartial.kt:186)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(MiXCRCommand.kt:42)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run(MiXCRCommandWithOutputs.kt:67)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 11 more
        Suppressed: java.lang.IllegalStateException: Footer not set
                at com.milaboratory.mixcr.basictypes.VDJCAlignmentsWriter.close(VDJCAlignmentsWriter.java:198)
                at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:64)
                at com.milaboratory.mixcr.cli.CommandAssemblePartial$Cmd.run0(CommandAssemblePartial.kt:141)
                ... 21 more '''

**Comment by dbolotin** [comment]
This seems to be a known bug that is already fixed in development branch. Please try pre-release version (here is the link for the [latest dev build](https://link.milaboratory.com/software/mixcr/mixcr-develop.zip)).

If I correctly understand, Nextera Flex DNA is a standard WGS preparation kit and has no UMIs, if this is correct, I confirm that the `exom-full-length` is the best preset for your case.

**Comment by MarzenaWojtaszewska** [comment]
> This seems to be a known bug that is already fixed in development branch. Please try pre-release version (here is the link for the [latest dev build](https://link.milaboratory.com/software/mixcr/mixcr-develop.zip)).
> 
> If I correctly understand, Nextera Flex DNA is a standard WGS preparation kit and has no UMIs, if this is correct, I confirm that the `exom-full-length` is the best preset for your case.

Thank You very much. I will try the new version.
This is not the PCR-free WGS, I use the PCR amplicon fragmentation. In principal- it is the same, however the IGH reads coverage is much higher than WES/WGS, it is around 50-100k and there is some level of duplicates....

**Comment by PoslavskySV** [comment]
Closing this issue so far. Please, feel free to re-open if any issues arise.
