### ISSUE TITLE
OutOfMemoryError in refineTagsAndSort function

### ISSUE THREAD

**Issue by hiro-aoki-mriid** [milaboratory/mixcr#939]
## Checklist before submitting the issue:

 - [✓] The issue is strongly related to the MiXCR software
 - [✓] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [✓] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [✓] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

I ran "refineTagsAndSort" function to produce "*.refined.vdjca" file.
Heap size of my java environment is the following.
![image](https://user-images.githubusercontent.com/99735120/209791184-3f79fd92-57d0-44ae-af11-49eb455db102.png)

## Actual Result

I faced the "java.lang.OutOfMemoryError: java heap space" when "Final sorting" was under progress.

## Exact MiXCR commands 

```
mixcr/mixcr align --preset bd-rhapsody-mouse-bcr-v2 \
    --tag-pattern "^(CELL1:N{9})gtga(CELL2:N{9})gaca(CELL3:N{9})(UMI:N{8})|^a(CELL1:N{9})gtga(CELL2:N{9})gaca(CELL3:N{9})(UMI:N{8})|^gt(CELL1:N{9})gtga(CELL2:N{9})gaca(CELL3:N{9})(UMI:N{8})|^tca(CELL1:N{9})gtga(CELL2:N{9})gaca(CELL3:N{9})(UMI:N{8})\^(R2:*)" \
    --threads 24 \
    --species mmu \
    --force-overwrite \
     test_R1_001.fastq.gz \
     test_R2_001.fastq.gz \
     test.vdjca 

mixcr/mixcr refineTagsAndSort \
    --force-overwrite\
      test.vdjca \
      test.refined.vdjca 

```
## MiXCR report files 

```
============== Align Report ==============
============== Align Report ==============
Total sequencing reads: 79227727
Successfully aligned reads: 71307833 (90%)
Alignment failed, no hits (not TCR/IG?): 3071807 (3.88%)
Alignment failed because of low total score: 119070 (0.15%)
Absent barcode: 4729017 (5.97%)
Overlapped: 0 (0%)
Overlapped and aligned: 0 (0%)
Alignment-aided overlaps: 0 (NaN%)
Overlapped and not aligned: 0 (0%)
No CDR3 parts alignments, percent of successfully aligned: 656354 (0.92%)
Partial aligned reads, percent of successfully aligned: 10401893 (14.59%)
IGK chains: 2 (0%)
IGK non-functional: 0 (0%)
TRA chains: 31391277 (44.02%)
TRA non-functional: 4282173 (13.64%)
TRAD chains: 608462 (0.85%)
TRAD non-functional: 0 (0%)
TRB chains: 39302318 (55.12%)
TRB non-functional: 1757285 (4.47%)
TRD chains: 5774 (0.01%)
TRD non-functional: 78 (1.35%)
Realigned with forced non-floating bound: 0 (0%)
Realigned with forced non-floating right bound in left read: 0 (0%)
Realigned with forced non-floating left bound in right read: 0 (0%)
Tag parsing report:
  Total reads: 79227727
  Matched reads: 74498710 (94.03%)
  Projection +R1 +R2: 74498710 (94.03%)
  For variant 0:
    For projection IntListKey(list=[1, 2]):
      CELL1:Left position:
        0: + 19054681 (25.58%) = 19054681 (25.58%)
        1: + 18313161 (24.58%) = 37367842 (50.16%)
        2: + 21077713 (28.29%) = 58445555 (78.45%)
        3: + 16053155 (21.55%) = 74498710 (100%)
      CELL1:Right position:
        9: + 19054681 (25.58%) = 19054681 (25.58%)
        10: + 18313161 (24.58%) = 37367842 (50.16%)
        11: + 21077713 (28.29%) = 58445555 (78.45%)
        12: + 16053155 (21.55%) = 74498710 (100%)
      CELL2:Left position:
        13: + 19054681 (25.58%) = 19054681 (25.58%)
        14: + 18313161 (24.58%) = 37367842 (50.16%)
        15: + 21077713 (28.29%) = 58445555 (78.45%)
        16: + 16053155 (21.55%) = 74498710 (100%)
      CELL2:Right position:
        22: + 19054681 (25.58%) = 19054681 (25.58%)
        23: + 18313161 (24.58%) = 37367842 (50.16%)
        24: + 21077713 (28.29%) = 58445555 (78.45%)
        25: + 16053155 (21.55%) = 74498710 (100%)
      CELL3:Left position:
        26: + 19054681 (25.58%) = 19054681 (25.58%)
        27: + 18313161 (24.58%) = 37367842 (50.16%)
        28: + 21077713 (28.29%) = 58445555 (78.45%)
        29: + 16053155 (21.55%) = 74498710 (100%)
      CELL3:Right position:
        35: + 19054681 (25.58%) = 19054681 (25.58%)
        36: + 18313161 (24.58%) = 37367842 (50.16%)
        37: + 21077713 (28.29%) = 58445555 (78.45%)
        38: + 16053155 (21.55%) = 74498710 (100%)
      UMI:Left position:
        35: + 19054681 (25.58%) = 19054681 (25.58%)
        36: + 18313161 (24.58%) = 37367842 (50.16%)
        37: + 21077713 (28.29%) = 58445555 (78.45%)
        38: + 16053155 (21.55%) = 74498710 (100%)
      Variants: 0
      Cost:
        0: + 69832929 (93.74%) = 69832929 (93.74%)
        4~9: + 4665781 (6.26%) = 74498710 (100%)
      CELL1 length: 9
      CELL2 length: 9
      CELL3 length: 9
      UMI length: 8
      R2 length:
        35~172: + 2455787 (3.3%) = 2455787 (3.3%)
        173: + 11754208 (15.78%) = 14209995 (19.07%)
        174: + 18437672 (24.75%) = 32647667 (43.82%)
        175: + 41851043 (56.18%) = 74498710 (100%)  
```

**Comment by PoslavskySV** [comment]
Hi,

you need to increase memory amount provided to Java. You can do this in the following way:
```
mixcr -Xmx16g ...
```

where `16g` stands for 16 Gigabytes.

**Comment by hiro-aoki-mriid** [comment]
Hi, 

I increased memory to 29G, by
`mixcr -Xmx29g ...`
However, I faced the same out-of-memory error again.

Do I need to increase the upper limit of the heap size of my java virtual machine?

Or, I think applying collection to CELL1, CELL2, and CELL3 (discarding UMI) can reduce memory usage, but can I do it by changing parameters?

**Comment by mizraelson** [comment]
Hi,
Can you please share the version of MiXCR that you use?

**Comment by hiro-aoki-mriid** [comment]
I am using MiXCR v4.1.2
![image](https://user-images.githubusercontent.com/99735120/210310366-b8145089-21a2-4a5d-9650-f27dd7d0370e.png)

**Comment by PoslavskySV** [comment]
Hi Hiroyasu,

according to the report you have a really huge sample (~80M reads). I believe you really need more memory to process such a huge single cell sample. Can you try to increase memory?

Warm regards,
Stan

**Comment by hiro-aoki-mriid** [comment]
Hi Stan,

Thank you for your advice.
I will try to increase memory size. However, the data I used to run was a part of the whole data of the experiment. How much memory size should I need to process whole data (~200M reads) in MiXCR?
Or is there any way to process this data with saving memory usage? I suppose discarding UMI can reduce memory usage.

Best regards,
Hiroyasu

**Comment by PoslavskySV** [comment]
Hi Hiroyasu,

MiXCR requires RAM for correcting sequencing and PCR errors inside barcode sequences: it has to load all barcodes in prefix tree directly in RAM. This step is important to eliminate artificial diversity generated by errors. In our experience for a really diverse (in terms of UMI) and large (~200M of reads) BD Rhapsody sample one need up to 128Gb of RAM to process.

At the same time, there is some room for memory usage optimization, and we will address this in upcoming releases (but still, not dramatically for such huge datasets).

Warm regards,
Stan

**Comment by PoslavskySV** [comment]
Closing this issue so far. Please, feel free to re-open if any issues arise.

**Comment by ejohnson643** [comment]
Well I'm going to bump this again. I have encountered a similar issue with 127 million read data, where even giving 200GB of RAM has resulted in an out of memory error during `refineTagsAndSort`. Interestingly, when I had tried running the full `analyze` pipeline on my MacBook Pro (16GB RAM) I was able to complete `refineTagsAndSort` only for it to fail on `extend`. For context, here was my exact command:

```
#!/usr/bin/bash
mixcr -Xmx100g analyze 10x-sc-xcr-vdj \
	--species hsa \
        --force-overwrite \
	../gdTCR/fastqs/{{a}}_L00{{n}}_R1_001.fastq.gz \
	../gdTCR/fastqs/{{a}}_L00{{n}}_R2_001.fastq.gz \
	../gdTCR/fastqs/MiXCR_10x_scVDJ/SC_CD001_gdTCR
```
Which generated the following error:
```
Writing result: progress unknown
Final sorting: 0.1%
Final sorting: 10.2%  ETA: 00:04:27
Final sorting: 20.6%  ETA: 00:05:09
Final sorting: 30.7%  ETA: 00:04:20
Final sorting: 40.7%  ETA: 00:03:54
Final sorting: 50.8%  ETA: 00:03:08
Final sorting: 60.9%  ETA: 00:02:30
Final sorting: 71%  ETA: 00:01:56
Please copy the following information along with the stacktrace:
   Version: 4.5.0; built=Fri Sep 22 12:39:05 UTC 2023; rev=cdb24b4fb7; lib=repseqio.v3.0.1
        OS: Linux
      Java: 21.0.1-internal
picocli.CommandLine$ExecutionException: Error while running command refineTagsAndSort java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: No space left on device
	at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-12(SourceFile:340)
	at picocli.CommandLine.execute(CommandLine.java:2088)
	at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$PlanBuilder.executeSteps(SourceFile:478)
	at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:421)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-26(SourceFile:447)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.milaboratory.mixcr.cli.Main.main(SourceFile:98)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: No space left on device
	at com.milaboratory.o.Dh.a(SourceFile:134)
	at com.milaboratory.o.Dh.a(SourceFile:107)
	at com.milaboratory.o.Dh.a(SourceFile:93)
	at com.milaboratory.o.gg.a(SourceFile:703)
	at com.milaboratory.o.gg.c(SourceFile:664)
	at com.milaboratory.mixcr.cli.CommandRefineTagsAndSort$Cmd.run1(SourceFile:353)
	at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-26(SourceFile:447)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	... 13 more
	Suppressed: java.io.IOException: No space left on device
		at java.base/java.io.FileOutputStream.writeBytes(Native Method)
		at java.base/java.io.FileOutputStream.write(FileOutputStream.java:367)
		at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:125)
		at java.base/java.io.BufferedOutputStream.implFlush(BufferedOutputStream.java:252)
		at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:240)
		at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:184)
		at org.apache.commons.io.IOUtils.close(IOUtils.java:403)
		at org.apache.commons.io.output.ProxyOutputStream.close(ProxyOutputStream.java:118)
		at com.milaboratory.o.Dh.a(SourceFile:159)
		... 29 more
Caused by: java.lang.RuntimeException: java.io.IOException: No space left on device
	at com.milaboratory.o.AY.writeInt(SourceFile:360)
	at com.milaboratory.mitool.refinement.ITags$Companion$IO.write(SourceFile:2010)
	at com.milaboratory.o.AY.a(SourceFile:236)
	at com.milaboratory.o.AY.a(SourceFile:198)
	at com.milaboratory.o.AY.c(SourceFile:289)
	at com.milaboratory.o.Cd$a.write(SourceFile:67)
	at com.milaboratory.o.Dh.a(SourceFile:141)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.io.IOException: No space left on device
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:367)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:125)
	at java.base/java.io.BufferedOutputStream.implWrite(BufferedOutputStream.java:222)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:200)
	at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:92)
	at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:92)
	at java.base/java.io.DataOutputStream.writeInt(DataOutputStream.java:206)
	at com.milaboratory.o.AY.writeInt(SourceFile:358)
	... 12 more

```

**Comment by ejohnson643** [comment]
For what it's worth, I was monitoring the RAM when this was happening and it was not pushed up hard against the 100GB limit. I'm going to try and run it a 4th time with each part of the pipeline separately and see if we can get past this.

**Comment by PoslavskySV** [comment]
Hi, based on the stacktrace the actual error is "java.io.IOException: No space left on device". On which system you are running it? MiXCR uses temp files to offload sorting from RAM to the hard drive, so there is chance that the default temp provided by the system is limited.

**Comment by ejohnson643** [comment]
I am running this on a brand new Linux server that should have more than enough space, so is there a way to work around this? Where would the temp files be put? I can check to see if there are limits on that location.

Please let me know if there are specs/logs that you need to see that would help.

**Comment by PoslavskySV** [comment]
Could you please running with the option "--use-system-temp" ?

```
mixcr -Xmx100g analyze 10x-sc-xcr-vdj \
	--species hsa \
        --force-overwrite \
        --use-system-temp \
	../gdTCR/fastqs/{{a}}_L00{{n}}_R1_001.fastq.gz \
	../gdTCR/fastqs/{{a}}_L00{{n}}_R2_001.fastq.gz \
	../gdTCR/fastqs/MiXCR_10x_scVDJ/SC_CD001_gdTCR
```

**Comment by PoslavskySV** [comment]
If you already have .vdjca files, you can re-run only refineTagsAndSort

**Comment by ejohnson643** [comment]
Ok I'm going to queue this up. It does seem that it is using a system temp file to offload RAM... is there a way to direct this temp file to another location?

**Comment by dbolotin** [comment]
Hi, sorry, please use `--use-local-temp` instead (this will put all temp files in the same folder as the output), the `--use-system-temp` is default behavior. Or specify standard linux environment variable `TMPDIR` ([wiki](https://en.wikipedia.org/wiki/TMPDIR)) to point to the desired place for temp files. If this will help, and you are running `mixcr` in some sort of HPC environment (i.e. with Slurm or HTCondor), I suggest reporting this to admins of the cluster to properly configure `TMPDIR` for execution nodes.

**Comment by ejohnson643** [comment]
I caught that before running it, thanks! I have now been able to get it all to run.

Thanks for your help and sorry if I put this issue in the wrong place - the previous issue seemed closely related at the time. I will say, if the program is going to use temp directories to offload large RAM uptake, it might make sense to make this flag more prominent in the documentation, especially for other users with large datasets.
