### ISSUE TITLE
Unmatched arguments from index 46

### ISSUE THREAD

**Issue by github-wow** [milaboratory/mixcr#945]
Hi,  
with  
```
mixcr postanalysis individual                            \
      *.clns                                             \
      result.json                                        \
      --default-downsampling count-reads-auto            \
      --default-weight-function read                     \
      --only-productive                                  \
      --drop-outliers                                    \
      --metadata metadata.tsv                            \
      --group group1 group2 group3
```
mixcr returns: `Unmatched arguments from index 46: 'group2,', 'group3'`  

mixcr info:  
```
MiXCR v4.1.2 (built Mon Nov 28 10:16:06 CET 2022; rev=ec9c6fd320; branch=no_branch; host=fv-az165-439)
RepSeq.IO v1.6.0 (rev=43b00498ee)
MiLib v2.2.0 (rev=3fb185f8b2)
Built-in V/D/J/C library: repseqio.v2.0
```

**Comment by PoslavskySV** [comment]
Hi, please separate group1,group2,group3 with comma.

**Comment by github-wow** [comment]
For `--group group1,group2,group3` I get the error:

```
picocli.CommandLine$ExecutionException: Error while running command individual java.lang.NullPointerException
        at com.milaboratory.mixcr.cli.Main.mkCmd$lambda-21(Main.kt:323)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.Main.main(Main.kt:76)
Caused by: java.lang.NullPointerException
        at com.milaboratory.mixcr.cli.postanalysis.CommandPa.groupSamples(CommandPa.kt:283)
        at com.milaboratory.mixcr.cli.postanalysis.CommandPa.run0(CommandPa.kt:305)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(MiXCRCommand.kt:42)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run(MiXCRCommandWithOutputs.kt:67)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        ... 1 more
```

Also tried single and double quotes, spaces, pipes.

In my case `--group` works only with any _single_ group.

**Comment by PoslavskySV** [comment]
Can you please try:

```
--group group1 --group group2 --group group3
```

**Comment by github-wow** [comment]
worked perfectly! thank you

**Comment by zznx** [comment]
Hi,
How can I solve it ?
`/public/software/mixcr-4.0.0/mixcr postanalysis individual *.clna result.json --default-downsampling count-reads-auto --default-weight-function read --only-productive --drop-outliers --metadata datameta.tsv --group group1 --group group2`

```
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.postanalysis.CommandPaIndividual@51850751): java.lang.NullPointerException
	at picocli.CommandLine.executeUserObject(CommandLine.java:1778)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:84)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:73)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:95)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:67)
Caused by: java.lang.NullPointerException
	at com.milaboratory.mixcr.cli.postanalysis.CommandPa.groupSamples(CommandPa.java:292)
	at com.milaboratory.mixcr.cli.postanalysis.CommandPa.run0(CommandPa.java:312)
	at com.milaboratory.cli.ACommand.run(ACommand.java:100)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	... 7 more
```

Thank you for any help

**Comment by zznx** [comment]
versionInfo
```
MagicBytes = MiXCR.VDJC.V16
MiXCR v4.0.0b (built Thu Jul 07 06:14:53 CST 2022; rev=8050699050; branch=400b); RepSeq.IO v1.4.0 (rev=8ad610d516); MiLib v2.0.0 (rev=ee6396596d); Built-in V/D/J/C library: repseqio.v2.0;
```

**Comment by mizraelson** [comment]
Hi, can you please try the latest MiXCR release 4.2 and confirm the error is still there.

**Comment by zznx** [comment]
Hi,
How can I solve it ?
```
picocli.CommandLine$ExecutionException: Error while running command individual java.lang.NullPointerException
	at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-11(Main.kt:301)
	at picocli.CommandLine.execute(CommandLine.java:2088)
	at com.milaboratory.mixcr.cli.Main.main(Main.kt:87)
Caused by: java.lang.NullPointerException
	at com.milaboratory.mixcr.cli.postanalysis.CommandPa.groupSamples(CommandPa.kt:284)
	at com.milaboratory.mixcr.cli.postanalysis.CommandPa.run1(CommandPa.kt:306)
	at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(MiXCRCommandWithOutputs.kt:69)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(MiXCRCommand.kt:36)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-25(Main.kt:387)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	... 1 more
```

**Comment by PoslavskySV** [comment]
@zznx Please, update to the recent MiXCR (4.2) and use the following command:
```
mixcr postanalysis individual \
--default-downsampling count-reads-auto \
--default-weight-function read \
--only-productive \
--drop-outliers \
--metadata datameta.tsv \
--group group1 \
--group group2 \
*.clns i.pa.json 
```
